Renderer: renderer::CommandBuffer Class Reference
renderer::CommandBuffer Class Reference abstract
A command buffer.
Public Member Functions
virtual ~CommandBuffer ()
Destructor.
virtual bool begin (CommandBufferUsageFlags flags=0u) const =0
Starts recording the command buffer.
virtual bool begin (CommandBufferUsageFlags flags, CommandBufferInheritanceInfo const &inheritanceInfo) const =0
Starts recording the command buffer as a secondary command buffer.
virtual bool end () const =0
Ends the command buffer recording.
virtual bool reset (CommandBufferResetFlags flags=0u) const =0
Reset a command buffer to the initial state.
virtual void beginRenderPass (RenderPass const &renderPass, FrameBuffer const &frameBuffer, ClearValueArray const &clearValues, SubpassContents contents) const =0
Begins a new render pass.
virtual void nextSubpass (SubpassContents contents) const =0
Transition to the next subpass of a render pass.
virtual void endRenderPass () const =0
End the current render pass.
virtual void executeCommands (CommandBufferCRefArray const &commands) const =0
Execute a secondary command buffer.
virtual void clear (TextureView const &image, ClearColorValue const &colour) const =0
Clear a color image.
virtual void clear (TextureView const &image, DepthStencilClearValue const &value) const =0
Clear a depth and/or stencil image.
virtual void clearAttachments (ClearAttachmentArray const &clearAttachments, ClearRectArray const &clearRects)=0
Clear regions within currently bound framebuffer attachments.
void memoryBarrier (PipelineStageFlags after, PipelineStageFlags before, BufferMemoryBarrier const &transitionBarrier) const
Defines a memory dependency between commands that were submitted before it, and those submitted after it.
void memoryBarrier (PipelineStageFlags after, PipelineStageFlags before, ImageMemoryBarrier const &transitionBarrier) const
Defines a memory dependency between commands that were submitted before it, and those submitted after it.
virtual void bindPipeline (Pipeline const &pipeline, PipelineBindPoint bindingPoint=PipelineBindPoint::eGraphics) const =0
Binds a pipeline to the command buffer.
virtual void bindPipeline (ComputePipeline const &pipeline, PipelineBindPoint bindingPoint=PipelineBindPoint::eCompute) const =0
Binds a compute pipeline to the command buffer.
virtual void bindVertexBuffers (uint32_t firstBinding, BufferCRefArray const &buffers, UInt64Array offsets) const =0
Binds vertex buffers to the command buffer.
virtual void bindIndexBuffer (BufferBase const &buffer, uint64_t offset, IndexType indexType) const =0
Binds an index buffer to the command buffer.
virtual void bindDescriptorSets (DescriptorSetCRefArray const &descriptorSet, PipelineLayout const &layout, renderer::UInt32Array const &dynamicOffsets, PipelineBindPoint bindingPoint=PipelineBindPoint::eGraphics) const =0
Binds descriptor sets to the command buffer.
virtual void setViewport (Viewport const &viewport) const =0
Defines the currently bound pipeline viewport.
virtual void setScissor (Scissor const &scissor) const =0
Defines the currently bound pipeline scissor.
virtual void draw (uint32_t vtxCount, uint32_t instCount=1u, uint32_t firstVertex=0u, uint32_t firstInstance=0u) const =0
Draws some vertices.
virtual void drawIndexed (uint32_t indexCount, uint32_t instCount=1u, uint32_t firstIndex=0u, uint32_t vertexOffset=0u, uint32_t firstInstance=0u) const =0
Draws some indexed vertices.
virtual void drawIndirect (BufferBase const &buffer, uint32_t offset, uint32_t drawCount, uint32_t stride) const =0
Perform an indirect draw.
virtual void drawIndexedIndirect (BufferBase const &buffer, uint32_t offset, uint32_t drawCount, uint32_t stride) const =0
Perform an indexed indirect draw.
virtual void copyToImage (BufferImageCopyArray const &copyInfo, BufferBase const &src, Texture const &dst) const =0
Copies data from a buffer to an image.
virtual void copyToBuffer (BufferImageCopyArray const &copyInfo, Texture const &src, BufferBase const &dst) const =0
Copies data from a buffer to an image.
virtual void copyBuffer (BufferCopy const &copyInfo, BufferBase const &src, BufferBase const &dst) const =0
Copies data from a buffer to another one.
virtual void copyImage (ImageCopy const &copyInfo, Texture const &src, ImageLayout srcLayout, Texture const &dst, ImageLayout dstLayout) const =0
Copies data from an image to another one.
virtual void blitImage (Texture const &srcImage, ImageLayout srcLayout, Texture const &dstImage, ImageLayout dstLayout, std::vector< ImageBlit > const &regions, Filter filter) const =0
Copy regions of an image to another one.
virtual void resetQueryPool (QueryPool const &pool, uint32_t firstQuery, uint32_t queryCount) const =0
Resets a range of queries in a query pool.
virtual void beginQuery (QueryPool const &pool, uint32_t query, QueryControlFlags flags) const =0
Begins a query.
virtual void endQuery (QueryPool const &pool, uint32_t query) const =0
Ends a query.
virtual void writeTimestamp (PipelineStageFlag pipelineStage, QueryPool const &pool, uint32_t query) const =0
Writes a timestamp to given query result.
virtual void pushConstants (PipelineLayout const &layout, PushConstantsBufferBase const &pcb) const =0
Updates the values of push constants.
virtual void dispatch (uint32_t groupCountX, uint32_t groupCountY, uint32_t groupCountZ) const =0
Dispatch compute work items.
virtual void dispatchIndirect (BufferBase const &buffer, uint32_t offset) const =0
Dispatch compute work items using indirect parameters.
virtual void setLineWidth (float width) const =0
Specifies the lines width, if this is a dynamic state in the pipeline.
virtual void setDepthBias (float constantFactor, float clamp, float slopeFactor) const =0
Specifies the lines width, if this is a dynamic state in the pipeline.
void bindVertexBuffer (uint32_t binding, BufferBase const &buffer, uint64_t offset) const
Binds a vertex buffer to the command buffer.
void copyToImage (BufferImageCopy const &copyInfo, BufferBase const &src, Texture const &dst) const
Copies data from a buffer to an image.
void copyToBuffer (BufferImageCopy const &copyInfo, Texture const &src, BufferBase const &dst) const
Copies data from a buffer to an image.
void copyBuffer (BufferBase const &src, BufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copies data from a buffer to another one.
void bindDescriptorSet (DescriptorSet const &descriptorSet, PipelineLayout const &layout, renderer::UInt32Array const &dynamicOffsets, PipelineBindPoint bindingPoint=PipelineBindPoint::eGraphics) const
Binds a descriptor set to the command buffer.
void bindDescriptorSet (DescriptorSet const &descriptorSet, PipelineLayout const &layout, PipelineBindPoint bindingPoint=PipelineBindPoint::eGraphics) const
Binds a descriptor set to the command buffer.
void bindDescriptorSets (DescriptorSetCRefArray const &descriptorSet, PipelineLayout const &layout, PipelineBindPoint bindingPoint=PipelineBindPoint::eGraphics) const
Binds descriptor sets to the command buffer.
void copyBuffer (BufferBase const &src, VertexBufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copie les données d'un tampon vers un autre tampon.
void copyBuffer (VertexBufferBase const &src, BufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copie les données d'un tampon vers un autre tampon.
void copyBuffer (VertexBufferBase const &src, VertexBufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copie les données d'un tampon vers un autre tampon.
void copyBuffer (BufferBase const &src, UniformBufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copie les données d'un tampon vers un autre tampon.
void copyBuffer (UniformBufferBase const &src, BufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copie les données d'un tampon vers un autre tampon.
void copyBuffer (UniformBufferBase const &src, UniformBufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copie les données d'un tampon vers un autre tampon.
void copyImage (TextureView const &src, TextureView const &dst) const
Copies data from an image to another one.
template<typename T >
void pushConstants (PipelineLayout const &layout, PushConstantsBuffer< T > const &pcb) const
Updates the values of push constants.
Protected Member Functions
CommandBuffer (CommandBuffer const &)=delete
CommandBuffer & operator= (CommandBuffer const &)=delete
CommandBuffer ()=default
CommandBuffer (Device const &device, CommandPool const &pool, bool primary=true)
Constructor.
Detailed Description
A command buffer.
Constructor & Destructor Documentation
CommandBuffer() [1/3]
renderer::CommandBuffer::CommandBuffer (CommandBuffer const &) protected delete
CommandBuffer() [2/3]
renderer::CommandBuffer::CommandBuffer () protected default
CommandBuffer() [3/3]
renderer::CommandBuffer::CommandBuffer (Device const & device, CommandPool const & pool, bool primary = true) protected
Constructor.
Parameters
[in] device The logical device.
[in] pool The parent command buffer pool.
[in] primary Tells if the command buffer is primary (true) or not (false).
~CommandBuffer()
virtual renderer::CommandBuffer::~CommandBuffer () virtual
Destructor.
Member Function Documentation
begin() [1/2]
virtual bool renderer::CommandBuffer::begin (CommandBufferUsageFlags flags = 0u) const pure virtual
Starts recording the command buffer.
Parameters
[in] flags The usage flags for the command buffer.
Returns
false on any problem.
begin() [2/2]
virtual bool renderer::CommandBuffer::begin (CommandBufferUsageFlags flags, CommandBufferInheritanceInfo const & inheritanceInfo) const pure virtual
Starts recording the command buffer as a secondary command buffer.
Parameters
[in] flags The usage flags for the command buffer.
[in] inheritanceInfo The inheritance informations.
Returns
false on any error.
beginQuery()
virtual void renderer::CommandBuffer::beginQuery (QueryPool const & pool, uint32_t query, QueryControlFlags flags) const pure virtual
Begins a query.
Parameters
[in] pool The query pool.
[in] query The query index.
[in] flags The constraints on the types of queries that can be performed.
beginRenderPass()
virtual void renderer::CommandBuffer::beginRenderPass (RenderPass const & renderPass, FrameBuffer const & frameBuffer, ClearValueArray const & clearValues, SubpassContents contents) const pure virtual
Begins a new render pass.
Parameters
[in] renderPass The render pass to begin.
[in] frameBuffer The framebuffer containing the attachments that are used with the render pass.
[in] clearValues The clear values for each attachment that needs to be cleared.
[in] contents Specifies how the commands in the first subpass will be provided.
bindDescriptorSet() [1/2]
void renderer::CommandBuffer::bindDescriptorSet (DescriptorSet const & descriptorSet, PipelineLayout const & layout, renderer::UInt32Array const & dynamicOffsets, PipelineBindPoint bindingPoint = PipelineBindPoint::eGraphics) const inline
Binds a descriptor set to the command buffer.
Parameters
[in] descriptorSet The descriptor set.
[in] layout The pipeline layout used to program the binding.
[in] dynamicOffsets The dynamic offsets for dynamic buffers.
[in] bindingPoint Indicates whether the descriptor wil be used by graphics or compute pipeline.
References bindDescriptorSets().
bindDescriptorSet() [2/2]
void renderer::CommandBuffer::bindDescriptorSet (DescriptorSet const & descriptorSet, PipelineLayout const & layout, PipelineBindPoint bindingPoint = PipelineBindPoint::eGraphics) const inline
Binds a descriptor set to the command buffer.
Parameters
[in] descriptorSet The descriptor set.
[in] layout The pipeline layout used to program the binding.
[in] bindingPoint Indicates whether the descriptor wil be used by graphics or compute pipeline.
References bindDescriptorSets().
bindDescriptorSets() [1/2]
virtual void renderer::CommandBuffer::bindDescriptorSets (DescriptorSetCRefArray const & descriptorSet, PipelineLayout const & layout, renderer::UInt32Array const & dynamicOffsets, PipelineBindPoint bindingPoint = PipelineBindPoint::eGraphics) const pure virtual
Binds descriptor sets to the command buffer.
Parameters
[in] descriptorSet The descriptor sets.
[in] layout The pipeline layout used to program the binding.
[in] dynamicOffsets The dynamic offsets for dynamic buffers.
[in] bindingPoint Indicates whether the descriptor wil be used by graphics or compute pipeline.
Referenced by bindDescriptorSet(), and bindDescriptorSets().
bindDescriptorSets() [2/2]
void renderer::CommandBuffer::bindDescriptorSets (DescriptorSetCRefArray const & descriptorSet, PipelineLayout const & layout, PipelineBindPoint bindingPoint = PipelineBindPoint::eGraphics) const inline
Binds descriptor sets to the command buffer.
Parameters
[in] descriptorSet The descriptor sets.
[in] layout The pipeline layout used to program the binding.
[in] bindingPoint Indicates whether the descriptor wil be used by graphics or compute pipeline.
References bindDescriptorSets(), copyBuffer(), and copyImage().
bindIndexBuffer()
virtual void renderer::CommandBuffer::bindIndexBuffer (BufferBase const & buffer, uint64_t offset, IndexType indexType) const pure virtual
Binds an index buffer to the command buffer.
Parameters
[in] buffer The buffer being bound.
[in] offset The starting offset in bytes within buffer used in index buffer address calculations.
[in] indexType Tells whether the indices are treated as 16 bits or 32 bits.
bindPipeline() [1/2]
virtual void renderer::CommandBuffer::bindPipeline (Pipeline const & pipeline, PipelineBindPoint bindingPoint = PipelineBindPoint::eGraphics) const pure virtual
Binds a pipeline to the command buffer.
Parameters
[in] pipeline The pipeline to be bound.
[in] bindingPoint Specifies whether to bind to the compute or graphics bind point.
bindPipeline() [2/2]
virtual void renderer::CommandBuffer::bindPipeline (ComputePipeline const & pipeline, PipelineBindPoint bindingPoint = PipelineBindPoint::eCompute) const pure virtual
Binds a compute pipeline to the command buffer.
Parameters
[in] pipeline The pipeline to be bound.
[in] bindingPoint Specifies whether to bind to the compute or graphics bind point.
bindVertexBuffer()
void renderer::CommandBuffer::bindVertexBuffer (uint32_t binding, BufferBase const & buffer, uint64_t offset) const
Binds a vertex buffer to the command buffer.
Parameters
[in] binding The index of the vertex input binding whose state is updated by the command.
[in] buffer The buffer handle.
[in] offset The array of buffer offset.
bindVertexBuffers()
virtual void renderer::CommandBuffer::bindVertexBuffers (uint32_t firstBinding, BufferCRefArray const & buffers, UInt64Array offsets) const pure virtual
Binds vertex buffers to the command buffer.
Parameters
[in] firstBinding The index of the first vertex input binding whose state is updated by the command.
[in] buffers The array of buffer handles.
[in] offsets The array of buffer offsets.
blitImage()
virtual void renderer::CommandBuffer::blitImage (Texture const & srcImage, ImageLayout srcLayout, Texture const & dstImage, ImageLayout dstLayout, std::vector< ImageBlit > const & regions, Filter filter) const pure virtual
Copy regions of an image to another one.
Parameters
[in] regions The regions to blit.
[in] srcImage The source image.
[in] srcLayout The source image layout.
[in] dstImage The destination image.
[in] dstLayout The source image layout.
[in] filter The filter applied if the blit requires scaling.
clear() [1/2]
virtual void renderer::CommandBuffer::clear (TextureView const & image, ClearColorValue const & colour) const pure virtual
Clear a color image.
Parameters
[in] image The image to clear.
[in] colour The clear colour.
clear() [2/2]
virtual void renderer::CommandBuffer::clear (TextureView const & image, DepthStencilClearValue const & value) const pure virtual
Clear a depth and/or stencil image.
Parameters
[in] image The image to clear.
[in] value The clear value.
clearAttachments()
virtual void renderer::CommandBuffer::clearAttachments (ClearAttachmentArray const & clearAttachments, ClearRectArray const & clearRects) pure virtual
Clear regions within currently bound framebuffer attachments.
Parameters
[in] clearAttachments The attachments to clear and the clear values to use.
[in] clearRects The regions within each selected attachment to clear.
copyBuffer() [1/8]
virtual void renderer::CommandBuffer::copyBuffer (BufferCopy const & copyInfo, BufferBase const & src, BufferBase const & dst) const pure virtual
Copies data from a buffer to another one.
Parameters
[in] copyInfo The copy informations.
[in] src The source buffer.
[in] dst The destination buffer.
Referenced by bindDescriptorSets().
copyBuffer() [2/8]
void renderer::CommandBuffer::copyBuffer (BufferBase const & src, BufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyBuffer() [3/8]
void renderer::CommandBuffer::copyBuffer (BufferBase const & src, VertexBufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copie les données d'un tampon vers un autre tampon.
Parameters
[in] src Le tampon source.
[in] dst Le tampon destination.
[in] size La taille des données à copier.
[in] offset Le décalage dans le tampon source.
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyBuffer() [4/8]
void renderer::CommandBuffer::copyBuffer (VertexBufferBase const & src, BufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copie les données d'un tampon vers un autre tampon.
Parameters
[in] src Le tampon source.
[in] dst Le tampon destination.
[in] size La taille des données à copier.
[in] offset Le décalage dans le tampon source.
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyBuffer() [5/8]
void renderer::CommandBuffer::copyBuffer (VertexBufferBase const & src, VertexBufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copie les données d'un tampon vers un autre tampon.
Parameters
[in] src Le tampon source.
[in] dst Le tampon destination.
[in] size La taille des données à copier.
[in] offset Le décalage dans le tampon source.
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyBuffer() [6/8]
void renderer::CommandBuffer::copyBuffer (BufferBase const & src, UniformBufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copie les données d'un tampon vers un autre tampon.
Parameters
[in] src Le tampon source.
[in] dst Le tampon destination.
[in] size La taille des données à copier.
[in] offset Le décalage dans le tampon source.
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyBuffer() [7/8]
void renderer::CommandBuffer::copyBuffer (UniformBufferBase const & src, BufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copie les données d'un tampon vers un autre tampon.
Parameters
[in] src Le tampon source.
[in] dst Le tampon destination.
[in] size La taille des données à copier.
[in] offset Le décalage dans le tampon source.
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyBuffer() [8/8]
void renderer::CommandBuffer::copyBuffer (UniformBufferBase const & src, UniformBufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copie les données d'un tampon vers un autre tampon.
Parameters
[in] src Le tampon source.
[in] dst Le tampon destination.
[in] size La taille des données à copier.
[in] offset Le décalage dans le tampon source.
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyImage() [1/2]
virtual void renderer::CommandBuffer::copyImage (ImageCopy const & copyInfo, Texture const & src, ImageLayout srcLayout, Texture const & dst, ImageLayout dstLayout) const pure virtual
Copies data from an image to another one.
Parameters
[in] copyInfo The copy informations.
[in] src The source image.
[in] srcLayout The image layout wanted for the source image.
[in] dst The destination image.
[in] dstLayout The image layout wanted for the destination image.
Referenced by bindDescriptorSets().
copyImage() [2/2]
void renderer::CommandBuffer::copyImage (TextureView const & src, TextureView const & dst) const
Copies data from an image to another one.
Parameters
[in] src The source image.
[in] dst The destination image.
copyToBuffer() [1/2]
virtual void renderer::CommandBuffer::copyToBuffer (BufferImageCopyArray const & copyInfo, Texture const & src, BufferBase const & dst) const pure virtual
Copies data from a buffer to an image.
Parameters
[in] copyInfo The copy informations.
[in] src The source buffer.
[in] dst The destination image.
copyToBuffer() [2/2]
void renderer::CommandBuffer::copyToBuffer (BufferImageCopy const & copyInfo, Texture const & src, BufferBase const & dst) const
Copies data from a buffer to an image.
Parameters
[in] copyInfo The copy informations.
[in] src The source buffer.
[in] dst The destination image.
copyToImage() [1/2]
virtual void renderer::CommandBuffer::copyToImage (BufferImageCopyArray const & copyInfo, BufferBase const & src, Texture const & dst) const pure virtual
Copies data from a buffer to an image.
Parameters
[in] copyInfo The copy informations.
[in] src The source buffer.
[in] dst The destination image.
copyToImage() [2/2]
void renderer::CommandBuffer::copyToImage (BufferImageCopy const & copyInfo, BufferBase const & src, Texture const & dst) const
Copies data from a buffer to an image.
Parameters
[in] copyInfo The copy informations.
[in] src The source buffer.
[in] dst The destination image.
dispatch()
virtual void renderer::CommandBuffer::dispatch (uint32_t groupCountX, uint32_t groupCountY, uint32_t groupCountZ) const pure virtual
Dispatch compute work items.
Parameters
[in] groupCountX,groupCountY,groupCountZ The number of local workgroups to dispatch to the X, Y, and Z dimensions.
dispatchIndirect()
virtual void renderer::CommandBuffer::dispatchIndirect (BufferBase const & buffer, uint32_t offset) const pure virtual
Dispatch compute work items using indirect parameters.
Parameters
[in] buffer The buffer containing dispatch parameters.
[in] offset The byte offset into buffer where parameters begin.
draw()
virtual void renderer::CommandBuffer::draw (uint32_t vtxCount, uint32_t instCount = 1u, uint32_t firstVertex = 0u, uint32_t firstInstance = 0u) const pure virtual
Draws some vertices.
Parameters
[in] vtxCount The vertex count.
[in] instCount The instances count.
[in] firstVertex The first vertex index.
[in] firstInstance The first instance index.
drawIndexed()
virtual void renderer::CommandBuffer::drawIndexed (uint32_t indexCount, uint32_t instCount = 1u, uint32_t firstIndex = 0u, uint32_t vertexOffset = 0u, uint32_t firstInstance = 0u) const pure virtual
Draws some indexed vertices.
Parameters
[in] indexCount The index count.
[in] instCount The instances count.
[in] firstIndex The first index index.
[in] vertexOffset The offset added to the vertex index, before indexing the vertex buffer.
[in] firstInstance The first instance index.
drawIndexedIndirect()
virtual void renderer::CommandBuffer::drawIndexedIndirect (BufferBase const & buffer, uint32_t offset, uint32_t drawCount, uint32_t stride) const pure virtual
Perform an indexed indirect draw.
Parameters
[in] buffer The buffer containing draw parameters.
[in] offset The byte offset into buffer where parameters begin.
[in] drawCount The number of draws to execute, and can be zero.
[in] stride The byte stride between successive sets of draw parameters.
drawIndirect()
virtual void renderer::CommandBuffer::drawIndirect (BufferBase const & buffer, uint32_t offset, uint32_t drawCount, uint32_t stride) const pure virtual
Perform an indirect draw.
Parameters
[in] buffer The buffer containing draw parameters.
[in] offset The byte offset into buffer where parameters begin.
[in] drawCount The number of draws to execute, and can be zero.
[in] stride The byte stride between successive sets of draw parameters.
end()
virtual bool renderer::CommandBuffer::end () const pure virtual
Ends the command buffer recording.
Returns
false on any error.
endQuery()
virtual void renderer::CommandBuffer::endQuery (QueryPool const & pool, uint32_t query) const pure virtual
Ends a query.
Parameters
[in] pool The query pool.
[in] query The query index.
endRenderPass()
virtual void renderer::CommandBuffer::endRenderPass () const pure virtual
End the current render pass.
executeCommands()
virtual void renderer::CommandBuffer::executeCommands (CommandBufferCRefArray const & commands) const pure virtual
Execute a secondary command buffer.
Parameters
[in] commands The secondary command buffers, which are recorded to execute in the order they are listed in the array.
memoryBarrier() [1/2]
void renderer::CommandBuffer::memoryBarrier (PipelineStageFlags after, PipelineStageFlags before, BufferMemoryBarrier const & transitionBarrier) const
Defines a memory dependency between commands that were submitted before it, and those submitted after it.
Parameters
[in] after Specifies the pipeline stages that must be ended before the barrier.
[in] before Specifies the pipeline stages that can be started after the barrier.
[in] transitionBarrier Describes the transition.
memoryBarrier() [2/2]
void renderer::CommandBuffer::memoryBarrier (PipelineStageFlags after, PipelineStageFlags before, ImageMemoryBarrier const & transitionBarrier) const
Defines a memory dependency between commands that were submitted before it, and those submitted after it.
Parameters
[in] after Specifies the pipeline stages that must be ended before the barrier.
[in] before Specifies the pipeline stages that can be started after the barrier.
[in] transitionBarrier Describes the transition.
nextSubpass()
virtual void renderer::CommandBuffer::nextSubpass (SubpassContents contents) const pure virtual
Transition to the next subpass of a render pass.
Parameters
[in] contents Specifies how the commands in the next subpass will be provided.
operator=()
CommandBuffer& renderer::CommandBuffer::operator= (CommandBuffer const &) protected delete
pushConstants() [1/2]
virtual void renderer::CommandBuffer::pushConstants (PipelineLayout const & layout, PushConstantsBufferBase const & pcb) const pure virtual
Updates the values of push constants.
Parameters
[in] layout The pipeline layout used to program the push constants updates.
[in] pcb The push constants buffer.
Referenced by pushConstants().
pushConstants() [2/2]
template<typename T > void renderer::CommandBuffer::pushConstants (PipelineLayout const & layout, PushConstantsBuffer< T > const & pcb) const inline
Updates the values of push constants.
Parameters
[in] layout The pipeline layout used to program the push constants updates.
[in] pcb The push constants buffer.
References renderer::PushConstantsBuffer< T >::getBuffer(), and pushConstants().
reset()
virtual bool renderer::CommandBuffer::reset (CommandBufferResetFlags flags = 0u) const pure virtual
Reset a command buffer to the initial state.
Parameters
[in] flags The flags controlling the reset operation.
Returns
false on any error.
resetQueryPool()
virtual void renderer::CommandBuffer::resetQueryPool (QueryPool const & pool, uint32_t firstQuery, uint32_t queryCount) const pure virtual
Resets a range of queries in a query pool.
Parameters
[in] pool The query pool.
[in] firstQuery The first query index.
[in] queryCount The number of queries (starting at firstQuery).
setDepthBias()
virtual void renderer::CommandBuffer::setDepthBias (float constantFactor, float clamp, float slopeFactor) const pure virtual
Specifies the lines width, if this is a dynamic state in the pipeline.
Parameters
[in] constantFactor The scalar factor controlling the constant depth value added to each fragment.
[in] clamp The maximum (or minimum) depth bias of a fragment.
[in] slopeFactor The scalar factor applied to a fragment’s slope in depth bias calculations.
setLineWidth()
virtual void renderer::CommandBuffer::setLineWidth (float width) const pure virtual
Specifies the lines width, if this is a dynamic state in the pipeline.
Parameters
[in] width The wanted width.
setScissor()
virtual void renderer::CommandBuffer::setScissor (Scissor const & scissor) const pure virtual
Defines the currently bound pipeline scissor.
Remarks
This action is possible only if the scissor is dynamic, in the pipeline.
Parameters
[in] scissor The scissor.
setViewport()
virtual void renderer::CommandBuffer::setViewport (Viewport const & viewport) const pure virtual
Defines the currently bound pipeline viewport.
Remarks
This action is possible only if the viewport is dynamic, in the pipeline.
Parameters
[in] viewport The viewport.
writeTimestamp()
virtual void renderer::CommandBuffer::writeTimestamp (PipelineStageFlag pipelineStage, QueryPool const & pool, uint32_t query) const pure virtual
Writes a timestamp to given query result.
Parameters
[in] pipelineStage Specifies the stage of the pipeline.
[in] pool The query pool.
[in] query The query index.
The documentation for this class was generated from the following file:
Z:/Projets/C++/RenderLib/source/Renderer/Renderer/Src/Command/CommandBuffer.hpp