Renderer: renderer::DeviceMemory Class Reference
renderer::DeviceMemory Class Reference abstract
A device memory object.
Public Member Functions
virtual ~DeviceMemory ()
virtual uint8_t * lock (uint32_t offset, uint32_t size, renderer::MemoryMapFlags flags) const =0
Maps a range of the memory in RAM.
virtual void invalidate (uint32_t offset, uint32_t size) const =0
Invalidates the memory content.
virtual void flush (uint32_t offset, uint32_t size) const =0
Updates the VRAM.
virtual void unlock () const =0
Unmaps the memory from RAM.
Protected Member Functions
DeviceMemory (Device const &device, MemoryPropertyFlags flags)
Protected Attributes
Device const & m_device
MemoryPropertyFlags m_flags
Detailed Description
A device memory object.
Constructor & Destructor Documentation
DeviceMemory()
renderer::DeviceMemory::DeviceMemory (Device const & device, MemoryPropertyFlags flags) inline protected
References m_device, m_flags, and registerObject.
~DeviceMemory()
virtual renderer::DeviceMemory::~DeviceMemory () inline virtual
References flush(), invalidate(), lock(), m_device, unlock(), and unregisterObject.
Member Function Documentation
flush()
virtual void renderer::DeviceMemory::flush (uint32_t offset, uint32_t size) const pure virtual
Updates the VRAM.
Parameters
[in] offset The mapped memory starting offset.
[in] size The range size.
Referenced by ~DeviceMemory().
invalidate()
virtual void renderer::DeviceMemory::invalidate (uint32_t offset, uint32_t size) const pure virtual
Invalidates the memory content.
Parameters
[in] offset The mapped memory starting offset.
[in] size The range size.
Referenced by ~DeviceMemory().
lock()
virtual uint8_t* renderer::DeviceMemory::lock (uint32_t offset, uint32_t size, renderer::MemoryMapFlags flags) const pure virtual
Maps a range of the memory in RAM.
Parameters
[in] offset The range beginning offset.
[in] size The range size.
[in] flags The mapping flags.
Returns
nullptr if mapping failed.
Referenced by ~DeviceMemory().
unlock()
virtual void renderer::DeviceMemory::unlock () const pure virtual
Unmaps the memory from RAM.
Referenced by ~DeviceMemory().
Member Data Documentation
m_device
Device const& renderer::DeviceMemory::m_device protected
Referenced by DeviceMemory(), and ~DeviceMemory().
m_flags
MemoryPropertyFlags renderer::DeviceMemory::m_flags protected
Referenced by DeviceMemory().
The documentation for this class was generated from the following file:
Z:/Projets/C++/RenderLib/source/Renderer/Renderer/Src/Miscellaneous/DeviceMemory.hpp