ashespp: ashes::UniformBufferBase Class Reference
ashes::UniformBufferBase Class Reference
Public Member Functions
UniformBufferBase (Device const &device, VkDeviceSize count, VkDeviceSize size, VkBufferUsageFlags target)
~UniformBufferBase ()
Destructor.
void bindMemory (DeviceMemoryPtr memory)
Binds this buffer to given device memory object.
VkMemoryRequirements getMemoryRequirements () const
VkDeviceSize getAlignedSize (VkDeviceSize size) const
Retrieves the aligned size for an element.
BufferBase const & getBuffer () const
VkDeviceSize getElementSize () const
Protected Attributes
Device const & m_device
VkDeviceSize m_count
VkDeviceSize m_size
BufferBasePtr m_buffer
Constructor & Destructor Documentation
UniformBufferBase()
ashes::UniformBufferBase::UniformBufferBase (Device const & device, VkDeviceSize count, VkDeviceSize size, VkBufferUsageFlags target)
Constructor.
Parameters
[in] device The logical device.
[in] count The number of instances of the data.
[in] size The size of an instance, in bytes.
[in] target The buffer usage flags.
~UniformBufferBase()
ashes::UniformBufferBase::~UniformBufferBase ()
Destructor.
Member Function Documentation
bindMemory()
void ashes::UniformBufferBase::bindMemory (DeviceMemoryPtr memory)
Binds this buffer to given device memory object.
Parameters
[in] memory The memory object.
Referenced by ashes::UniformBuffer< T >::bindMemory().
getAlignedSize()
VkDeviceSize ashes::UniformBufferBase::getAlignedSize (VkDeviceSize size) const
Retrieves the aligned size for an element.
Parameters
[in] size The size of an element.
Returns
The aligned size.
Referenced by ashes::UniformBuffer< T >::getAlignedSize().
getBuffer()
BufferBase const& ashes::UniformBufferBase::getBuffer () const inline
Returns
The GPU buffer.
References m_buffer.
Referenced by ashes::UniformBuffer< T >::upload().
getElementSize()
VkDeviceSize ashes::UniformBufferBase::getElementSize () const inline
Returns
The size of one element in the buffer.
References m_size.
getMemoryRequirements()
VkMemoryRequirements ashes::UniformBufferBase::getMemoryRequirements () const
Returns
The memory requirements for this buffer.
Referenced by ashes::UniformBuffer< T >::getMemoryRequirements().
Member Data Documentation
m_buffer
BufferBasePtr ashes::UniformBufferBase::m_buffer protected
Referenced by getBuffer().
m_count
VkDeviceSize ashes::UniformBufferBase::m_count protected
m_device
Device const& ashes::UniformBufferBase::m_device protected
m_size
VkDeviceSize ashes::UniformBufferBase::m_size protected
Referenced by getElementSize().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Ashes/include/ashespp/Buffer/UniformBuffer.hpp