/*
This file belongs to Ashes.
See LICENSE file in root folder.
*/
#if defined( CreateSemaphore )
#	undef CreateSemaphore
#endif

#if defined( CreateEvent )
#	undef CreateEvent
#endif

#ifndef VK_LIB_GLOBAL_FUNCTION
#	define VK_LIB_GLOBAL_FUNCTION( x )
#endif

#ifndef VK_LIB_GLOBAL_FUNCTION_EXT
#	define VK_LIB_GLOBAL_FUNCTION_EXT( n, x ) VK_LIB_GLOBAL_FUNCTION( x )
#endif

#ifdef VK_VERSION_1_0
	VK_LIB_GLOBAL_FUNCTION( CreateInstance )
	VK_LIB_GLOBAL_FUNCTION( EnumerateInstanceExtensionProperties )
	VK_LIB_GLOBAL_FUNCTION( EnumerateInstanceLayerProperties )
#endif

#ifdef VK_VERSION_1_1
	VK_LIB_GLOBAL_FUNCTION( EnumerateInstanceVersion )
#endif

#undef VK_LIB_GLOBAL_FUNCTION
#undef VK_LIB_GLOBAL_FUNCTION_EXT

#ifndef VK_LIB_INSTANCE_FUNCTION
#	define VK_LIB_INSTANCE_FUNCTION( x )
#endif

#ifndef VK_LIB_INSTANCE_FUNCTION_MANDATORY_EXT
#	define VK_LIB_INSTANCE_FUNCTION_MANDATORY_EXT( n, x ) VK_LIB_INSTANCE_FUNCTION( x )
#endif

#ifndef VK_LIB_INSTANCE_FUNCTION_EXT
#	define VK_LIB_INSTANCE_FUNCTION_EXT( n, x ) VK_LIB_INSTANCE_FUNCTION( x )
#endif

#ifdef VK_VERSION_1_0
	VK_LIB_INSTANCE_FUNCTION(  CreateDevice )
	VK_LIB_INSTANCE_FUNCTION(  DestroyInstance )
	VK_LIB_INSTANCE_FUNCTION(  EnumeratePhysicalDevices )
	VK_LIB_INSTANCE_FUNCTION(  EnumerateDeviceExtensionProperties )
	VK_LIB_INSTANCE_FUNCTION(  EnumerateDeviceLayerProperties )
	VK_LIB_INSTANCE_FUNCTION(  GetDeviceProcAddr )
	VK_LIB_INSTANCE_FUNCTION(  GetPhysicalDeviceFeatures )
	VK_LIB_INSTANCE_FUNCTION(  GetPhysicalDeviceFormatProperties )
	VK_LIB_INSTANCE_FUNCTION(  GetPhysicalDeviceImageFormatProperties )
	VK_LIB_INSTANCE_FUNCTION(  GetPhysicalDeviceMemoryProperties )
	VK_LIB_INSTANCE_FUNCTION(  GetPhysicalDeviceProperties )
	VK_LIB_INSTANCE_FUNCTION(  GetPhysicalDeviceQueueFamilyProperties )
#endif

#ifdef VK_VERSION_1_1
	VK_LIB_INSTANCE_FUNCTION( EnumeratePhysicalDeviceGroups )
	VK_LIB_INSTANCE_FUNCTION( GetPhysicalDeviceFeatures2 )
	VK_LIB_INSTANCE_FUNCTION( GetPhysicalDeviceProperties2 )
	VK_LIB_INSTANCE_FUNCTION( GetPhysicalDeviceFormatProperties2 )
	VK_LIB_INSTANCE_FUNCTION( GetPhysicalDeviceImageFormatProperties2 )
	VK_LIB_INSTANCE_FUNCTION( GetPhysicalDeviceQueueFamilyProperties2 )
	VK_LIB_INSTANCE_FUNCTION( GetPhysicalDeviceMemoryProperties2 )
	VK_LIB_INSTANCE_FUNCTION( GetPhysicalDeviceSparseImageFormatProperties2 )
	VK_LIB_INSTANCE_FUNCTION( GetPhysicalDeviceExternalBufferProperties )
	VK_LIB_INSTANCE_FUNCTION( GetPhysicalDeviceExternalFenceProperties )
	VK_LIB_INSTANCE_FUNCTION( GetPhysicalDeviceExternalSemaphoreProperties )
#endif

#ifdef VK_KHR_surface
	VK_LIB_INSTANCE_FUNCTION_MANDATORY_EXT( VK_KHR_SURFACE_EXTENSION_NAME, DestroySurfaceKHR )
	VK_LIB_INSTANCE_FUNCTION_MANDATORY_EXT( VK_KHR_SURFACE_EXTENSION_NAME, GetPhysicalDeviceSurfaceCapabilitiesKHR )
	VK_LIB_INSTANCE_FUNCTION_MANDATORY_EXT( VK_KHR_SURFACE_EXTENSION_NAME, GetPhysicalDeviceSurfaceFormatsKHR )
	VK_LIB_INSTANCE_FUNCTION_MANDATORY_EXT( VK_KHR_SURFACE_EXTENSION_NAME, GetPhysicalDeviceSurfaceSupportKHR )
	VK_LIB_INSTANCE_FUNCTION_MANDATORY_EXT( VK_KHR_SURFACE_EXTENSION_NAME, GetPhysicalDeviceSurfacePresentModesKHR )
#endif

#ifdef VK_KHR_swapchain
	VK_LIB_INSTANCE_FUNCTION_MANDATORY_EXT( VK_KHR_SWAPCHAIN_EXTENSION_NAME, GetPhysicalDevicePresentRectanglesKHR )
#endif

#ifdef VK_KHR_display
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_DISPLAY_EXTENSION_NAME, GetPhysicalDeviceDisplayPropertiesKHR )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_DISPLAY_EXTENSION_NAME, GetPhysicalDeviceDisplayPlanePropertiesKHR )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_DISPLAY_EXTENSION_NAME, GetDisplayPlaneSupportedDisplaysKHR )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_DISPLAY_EXTENSION_NAME, GetDisplayModePropertiesKHR )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_DISPLAY_EXTENSION_NAME, CreateDisplayModeKHR )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_DISPLAY_EXTENSION_NAME, GetDisplayPlaneCapabilitiesKHR )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_DISPLAY_EXTENSION_NAME, CreateDisplayPlaneSurfaceKHR )
#endif

#ifdef VK_KHR_get_display_properties2
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_GET_DISPLAY_PROPERTIES_2_EXTENSION_NAME, GetPhysicalDeviceDisplayProperties2KHR )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_GET_DISPLAY_PROPERTIES_2_EXTENSION_NAME, GetPhysicalDeviceDisplayPlaneProperties2KHR )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_GET_DISPLAY_PROPERTIES_2_EXTENSION_NAME, GetDisplayModeProperties2KHR )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_GET_DISPLAY_PROPERTIES_2_EXTENSION_NAME, GetDisplayPlaneCapabilities2KHR )
#endif

#ifdef VK_KHR_display_swapchain
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_DISPLAY_SWAPCHAIN_EXTENSION_NAME, GetPhysicalDeviceFeatures2KHR )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_DISPLAY_SWAPCHAIN_EXTENSION_NAME, GetPhysicalDeviceProperties2KHR )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_DISPLAY_SWAPCHAIN_EXTENSION_NAME, GetPhysicalDeviceFormatProperties2KHR )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_DISPLAY_SWAPCHAIN_EXTENSION_NAME, GetPhysicalDeviceImageFormatProperties2KHR )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_DISPLAY_SWAPCHAIN_EXTENSION_NAME, GetPhysicalDeviceQueueFamilyProperties2KHR )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_DISPLAY_SWAPCHAIN_EXTENSION_NAME, GetPhysicalDeviceMemoryProperties2KHR )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_DISPLAY_SWAPCHAIN_EXTENSION_NAME, GetPhysicalDeviceSparseImageFormatProperties2KHR )
#endif

#ifdef VK_KHR_device_group_creation
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_DEVICE_GROUP_CREATION_EXTENSION_NAME, EnumeratePhysicalDeviceGroupsKHR )
#endif

#ifdef VK_KHR_external_memory_capabilities
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_EXTERNAL_MEMORY_CAPABILITIES_EXTENSION_NAME, GetPhysicalDeviceExternalBufferPropertiesKHR )
#endif

#ifdef VK_KHR_external_semaphore_capabilities
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_EXTERNAL_SEMAPHORE_CAPABILITIES_EXTENSION_NAME, GetPhysicalDeviceExternalSemaphorePropertiesKHR )
#endif

#ifdef VK_KHR_external_fence_capabilities
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_EXTERNAL_FENCE_CAPABILITIES_EXTENSION_NAME, GetPhysicalDeviceExternalFencePropertiesKHR )
#endif

#ifdef VK_KHR_get_surface_capabilities2
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_GET_SURFACE_CAPABILITIES_2_EXTENSION_NAME, GetPhysicalDeviceSurfaceCapabilities2KHR )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_KHR_GET_SURFACE_CAPABILITIES_2_EXTENSION_NAME, GetPhysicalDeviceSurfaceFormats2KHR )
#endif

#ifdef VK_EXT_debug_report
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_EXT_DEBUG_REPORT_EXTENSION_NAME, CreateDebugReportCallbackEXT )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_EXT_DEBUG_REPORT_EXTENSION_NAME, DestroyDebugReportCallbackEXT )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_EXT_DEBUG_REPORT_EXTENSION_NAME, DebugReportMessageEXT )
#endif

#ifdef VK_NV_external_memory_capabilities
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_NV_EXTERNAL_MEMORY_CAPABILITIES_EXTENSION_NAME, GetPhysicalDeviceExternalImageFormatPropertiesNV )
#endif

#ifdef VK_EXT_direct_mode_display
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_EXT_DIRECT_MODE_DISPLAY_EXTENSION_NAME, ReleaseDisplayEXT )
#endif

#ifdef VK_NVX_device_generated_commands
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_NVX_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME, GetPhysicalDeviceGeneratedCommandsPropertiesNVX )
#endif

#ifdef VK_EXT_display_surface_counter
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_EXT_DISPLAY_SURFACE_COUNTER_EXTENSION_NAME, GetPhysicalDeviceSurfaceCapabilities2EXT )
#endif

#ifdef VK_EXT_debug_utils
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_EXT_DEBUG_UTILS_EXTENSION_NAME, CreateDebugUtilsMessengerEXT )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_EXT_DEBUG_UTILS_EXTENSION_NAME, DestroyDebugUtilsMessengerEXT )
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_EXT_DEBUG_UTILS_EXTENSION_NAME, SubmitDebugUtilsMessageEXT )
#endif

#ifdef VK_EXT_sample_locations
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_EXT_SAMPLE_LOCATIONS_EXTENSION_NAME, GetPhysicalDeviceMultisamplePropertiesEXT )
#endif

#ifdef VK_EXT_calibrated_timestamps
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_EXT_CALIBRATED_TIMESTAMPS_EXTENSION_NAME, GetPhysicalDeviceCalibrateableTimeDomainsEXT )
#endif

#ifdef VK_NV_cooperative_matrix
	VK_LIB_INSTANCE_FUNCTION_EXT( VK_NV_COOPERATIVE_MATRIX_EXTENSION_NAME, GetPhysicalDeviceCooperativeMatrixPropertiesNV )
#endif

#ifdef VK_USE_PLATFORM_ANDROID_KHR
#	ifdef VK_KHR_android_surface
	VK_LIB_INSTANCE_FUNCTION( CreateAndroidSurfaceKHR )
#	endif
#endif

#ifdef VK_USE_PLATFORM_MIR_KHR
#	ifdef VK_KHR_mir_surface
	VK_LIB_INSTANCE_FUNCTION( CreateMirSurfaceKHR )
	VK_LIB_INSTANCE_FUNCTION( GetPhysicalDeviceMirPresentationSupportKHR )
#	endif
#endif

#ifdef VK_USE_PLATFORM_XCB_KHR
#	ifdef VK_KHR_xcb_surface
	VK_LIB_INSTANCE_FUNCTION( CreateXcbSurfaceKHR )
	VK_LIB_INSTANCE_FUNCTION( GetPhysicalDeviceXcbPresentationSupportKHR )
#	endif
#endif

#ifdef VK_USE_PLATFORM_XLIB_KHR
#	ifdef VK_KHR_xlib_surface
	VK_LIB_INSTANCE_FUNCTION( CreateXlibSurfaceKHR )
	VK_LIB_INSTANCE_FUNCTION( GetPhysicalDeviceXlibPresentationSupportKHR )
#	endif
#endif

#ifdef VK_USE_PLATFORM_WAYLAND_KHR
#	ifdef VK_KHR_wayland_surface
	VK_LIB_INSTANCE_FUNCTION( CreateWaylandSurfaceKHR )
	VK_LIB_INSTANCE_FUNCTION( GetPhysicalDeviceWaylandPresentationSupportKHR )
#	endif
#endif

#ifdef VK_USE_PLATFORM_WIN32_KHR
#	ifdef VK_KHR_win32_surface
	VK_LIB_INSTANCE_FUNCTION( CreateWin32SurfaceKHR )
	VK_LIB_INSTANCE_FUNCTION( GetPhysicalDeviceWin32PresentationSupportKHR )
#	endif
#endif

#undef VK_LIB_INSTANCE_FUNCTION
#undef VK_LIB_INSTANCE_FUNCTION_EXT
#undef VK_LIB_INSTANCE_FUNCTION_MANDATORY_EXT

#ifndef VK_LIB_DEVICE_FUNCTION
#	define VK_LIB_DEVICE_FUNCTION( x )
#endif

#ifndef VK_LIB_DEVICE_FUNCTION_EXT
#	define VK_LIB_DEVICE_FUNCTION_EXT( n, x ) VK_LIB_DEVICE_FUNCTION( x )
#endif

#ifndef VK_LIB_DEVICE_FUNCTION_MANDATORY_EXT
#	define VK_LIB_DEVICE_FUNCTION_MANDATORY_EXT( n, x ) VK_LIB_DEVICE_FUNCTION( x )
#endif

#ifdef VK_VERSION_1_0
	VK_LIB_DEVICE_FUNCTION( AllocateCommandBuffers )
	VK_LIB_DEVICE_FUNCTION( AllocateDescriptorSets )
	VK_LIB_DEVICE_FUNCTION( AllocateMemory )
	VK_LIB_DEVICE_FUNCTION( BeginCommandBuffer )
	VK_LIB_DEVICE_FUNCTION( BindBufferMemory )
	VK_LIB_DEVICE_FUNCTION( BindImageMemory )
	VK_LIB_DEVICE_FUNCTION( CmdBeginQuery )
	VK_LIB_DEVICE_FUNCTION( CmdBeginRenderPass )
	VK_LIB_DEVICE_FUNCTION( CmdBindDescriptorSets )
	VK_LIB_DEVICE_FUNCTION( CmdBindIndexBuffer )
	VK_LIB_DEVICE_FUNCTION( CmdBindPipeline )
	VK_LIB_DEVICE_FUNCTION( CmdBindVertexBuffers )
	VK_LIB_DEVICE_FUNCTION( CmdBlitImage )
	VK_LIB_DEVICE_FUNCTION( CmdClearAttachments )
	VK_LIB_DEVICE_FUNCTION( CmdClearColorImage )
	VK_LIB_DEVICE_FUNCTION( CmdClearDepthStencilImage )
	VK_LIB_DEVICE_FUNCTION( CmdCopyBuffer )
	VK_LIB_DEVICE_FUNCTION( CmdCopyBufferToImage )
	VK_LIB_DEVICE_FUNCTION( CmdCopyImage )
	VK_LIB_DEVICE_FUNCTION( CmdDispatch )
	VK_LIB_DEVICE_FUNCTION( CmdDispatchIndirect )
	VK_LIB_DEVICE_FUNCTION( CmdDraw )
	VK_LIB_DEVICE_FUNCTION( CmdDrawIndexed )
	VK_LIB_DEVICE_FUNCTION( CmdDrawIndirect )
	VK_LIB_DEVICE_FUNCTION( CmdDrawIndexedIndirect )
	VK_LIB_DEVICE_FUNCTION( CmdEndQuery )
	VK_LIB_DEVICE_FUNCTION( CmdEndRenderPass )
	VK_LIB_DEVICE_FUNCTION( CmdExecuteCommands )
	VK_LIB_DEVICE_FUNCTION( CmdCopyImageToBuffer )
	VK_LIB_DEVICE_FUNCTION( CmdNextSubpass )
	VK_LIB_DEVICE_FUNCTION( CmdPipelineBarrier )
	VK_LIB_DEVICE_FUNCTION( CmdPushConstants )
	VK_LIB_DEVICE_FUNCTION( CmdResetEvent )
	VK_LIB_DEVICE_FUNCTION( CmdResetQueryPool )
	VK_LIB_DEVICE_FUNCTION( CmdSetDepthBias )
	VK_LIB_DEVICE_FUNCTION( CmdSetEvent )
	VK_LIB_DEVICE_FUNCTION( CmdSetLineWidth )
	VK_LIB_DEVICE_FUNCTION( CmdSetScissor )
	VK_LIB_DEVICE_FUNCTION( CmdSetViewport )
	VK_LIB_DEVICE_FUNCTION( CmdWaitEvents )
	VK_LIB_DEVICE_FUNCTION( CmdWriteTimestamp )
	VK_LIB_DEVICE_FUNCTION( CreateBuffer )
	VK_LIB_DEVICE_FUNCTION( CreateBufferView )
	VK_LIB_DEVICE_FUNCTION( CreateCommandPool )
	VK_LIB_DEVICE_FUNCTION( CreateComputePipelines )
	VK_LIB_DEVICE_FUNCTION( CreateDescriptorPool )
	VK_LIB_DEVICE_FUNCTION( CreateDescriptorSetLayout )
	VK_LIB_DEVICE_FUNCTION( CreateEvent )
	VK_LIB_DEVICE_FUNCTION( CreateFence )
	VK_LIB_DEVICE_FUNCTION( CreateFramebuffer )
	VK_LIB_DEVICE_FUNCTION( CreateGraphicsPipelines )
	VK_LIB_DEVICE_FUNCTION( CreateImage )
	VK_LIB_DEVICE_FUNCTION( CreateImageView )
	VK_LIB_DEVICE_FUNCTION( CreatePipelineLayout )
	VK_LIB_DEVICE_FUNCTION( CreateRenderPass )
	VK_LIB_DEVICE_FUNCTION( CreateQueryPool )
	VK_LIB_DEVICE_FUNCTION( CreateSampler )
	VK_LIB_DEVICE_FUNCTION( CreateSemaphore )
	VK_LIB_DEVICE_FUNCTION( CreateShaderModule )
	VK_LIB_DEVICE_FUNCTION( DestroyBuffer )
	VK_LIB_DEVICE_FUNCTION( DestroyBufferView )
	VK_LIB_DEVICE_FUNCTION( DestroyCommandPool )
	VK_LIB_DEVICE_FUNCTION( DestroyDescriptorPool )
	VK_LIB_DEVICE_FUNCTION( DestroyDescriptorSetLayout )
	VK_LIB_DEVICE_FUNCTION( DestroyDevice )
	VK_LIB_DEVICE_FUNCTION( DestroyEvent )
	VK_LIB_DEVICE_FUNCTION( DestroyFence )
	VK_LIB_DEVICE_FUNCTION( DestroyFramebuffer )
	VK_LIB_DEVICE_FUNCTION( DestroyImage )
	VK_LIB_DEVICE_FUNCTION( DestroyImageView )
	VK_LIB_DEVICE_FUNCTION( DestroyPipeline )
	VK_LIB_DEVICE_FUNCTION( DestroyPipelineLayout )
	VK_LIB_DEVICE_FUNCTION( DestroyQueryPool )
	VK_LIB_DEVICE_FUNCTION( DestroyRenderPass )
	VK_LIB_DEVICE_FUNCTION( DestroySampler )
	VK_LIB_DEVICE_FUNCTION( DestroySemaphore )
	VK_LIB_DEVICE_FUNCTION( DestroyShaderModule )
	VK_LIB_DEVICE_FUNCTION( DeviceWaitIdle )
	VK_LIB_DEVICE_FUNCTION( EndCommandBuffer )
	VK_LIB_DEVICE_FUNCTION( FlushMappedMemoryRanges )
	VK_LIB_DEVICE_FUNCTION( FreeCommandBuffers )
	VK_LIB_DEVICE_FUNCTION( FreeDescriptorSets )
	VK_LIB_DEVICE_FUNCTION( FreeMemory )
	VK_LIB_DEVICE_FUNCTION( GetBufferMemoryRequirements )
	VK_LIB_DEVICE_FUNCTION( GetDeviceQueue )
	VK_LIB_DEVICE_FUNCTION( GetEventStatus )
	VK_LIB_DEVICE_FUNCTION( GetImageMemoryRequirements )
	VK_LIB_DEVICE_FUNCTION( GetImageSparseMemoryRequirements )
	VK_LIB_DEVICE_FUNCTION( GetPhysicalDeviceSparseImageFormatProperties )
	VK_LIB_DEVICE_FUNCTION( GetImageSubresourceLayout )
	VK_LIB_DEVICE_FUNCTION( GetQueryPoolResults )
	VK_LIB_DEVICE_FUNCTION( InvalidateMappedMemoryRanges )
	VK_LIB_DEVICE_FUNCTION( GetDeviceMemoryCommitment )
	VK_LIB_DEVICE_FUNCTION( MapMemory )
	VK_LIB_DEVICE_FUNCTION( QueueSubmit )
	VK_LIB_DEVICE_FUNCTION( QueueWaitIdle )
	VK_LIB_DEVICE_FUNCTION( ResetCommandBuffer )
	VK_LIB_DEVICE_FUNCTION( ResetEvent )
	VK_LIB_DEVICE_FUNCTION( ResetFences )
	VK_LIB_DEVICE_FUNCTION( SetEvent )
	VK_LIB_DEVICE_FUNCTION( UnmapMemory )
	VK_LIB_DEVICE_FUNCTION( UpdateDescriptorSets )
	VK_LIB_DEVICE_FUNCTION( WaitForFences )
	VK_LIB_DEVICE_FUNCTION( CreatePipelineCache )
	VK_LIB_DEVICE_FUNCTION( DestroyPipelineCache )
	VK_LIB_DEVICE_FUNCTION( GetPipelineCacheData )
	VK_LIB_DEVICE_FUNCTION( MergePipelineCaches )
	VK_LIB_DEVICE_FUNCTION( ResetDescriptorPool )
	VK_LIB_DEVICE_FUNCTION( GetRenderAreaGranularity )
	VK_LIB_DEVICE_FUNCTION( CmdSetBlendConstants )
	VK_LIB_DEVICE_FUNCTION( CmdSetDepthBounds )
	VK_LIB_DEVICE_FUNCTION( CmdSetStencilCompareMask )
	VK_LIB_DEVICE_FUNCTION( CmdSetStencilWriteMask )
	VK_LIB_DEVICE_FUNCTION( CmdSetStencilReference )
	VK_LIB_DEVICE_FUNCTION( CmdUpdateBuffer )
	VK_LIB_DEVICE_FUNCTION( CmdFillBuffer )
	VK_LIB_DEVICE_FUNCTION( CmdResolveImage )
	VK_LIB_DEVICE_FUNCTION( QueueBindSparse )
	VK_LIB_DEVICE_FUNCTION( GetFenceStatus )
	VK_LIB_DEVICE_FUNCTION( ResetCommandPool )
	VK_LIB_DEVICE_FUNCTION( CmdCopyQueryPoolResults )
#endif

#ifdef VK_VERSION_1_1
	VK_LIB_DEVICE_FUNCTION( BindBufferMemory2 )
	VK_LIB_DEVICE_FUNCTION( BindImageMemory2 )
	VK_LIB_DEVICE_FUNCTION( GetDeviceGroupPeerMemoryFeatures )
	VK_LIB_DEVICE_FUNCTION( CmdSetDeviceMask )
	VK_LIB_DEVICE_FUNCTION( CmdDispatchBase )
	VK_LIB_DEVICE_FUNCTION( GetImageMemoryRequirements2 )
	VK_LIB_DEVICE_FUNCTION( GetBufferMemoryRequirements2 )
	VK_LIB_DEVICE_FUNCTION( GetImageSparseMemoryRequirements2 )
	VK_LIB_DEVICE_FUNCTION( TrimCommandPool )
	VK_LIB_DEVICE_FUNCTION( GetDeviceQueue2 )
	VK_LIB_DEVICE_FUNCTION( CreateSamplerYcbcrConversion )
	VK_LIB_DEVICE_FUNCTION( DestroySamplerYcbcrConversion )
	VK_LIB_DEVICE_FUNCTION( CreateDescriptorUpdateTemplate )
	VK_LIB_DEVICE_FUNCTION( DestroyDescriptorUpdateTemplate )
	VK_LIB_DEVICE_FUNCTION( UpdateDescriptorSetWithTemplate )
	VK_LIB_DEVICE_FUNCTION( GetDescriptorSetLayoutSupport )
#endif

#ifdef VK_KHR_swapchain
	VK_LIB_DEVICE_FUNCTION_MANDATORY_EXT( VK_KHR_SWAPCHAIN_EXTENSION_NAME, CreateSwapchainKHR )
	VK_LIB_DEVICE_FUNCTION_MANDATORY_EXT( VK_KHR_SWAPCHAIN_EXTENSION_NAME, DestroySwapchainKHR )
	VK_LIB_DEVICE_FUNCTION_MANDATORY_EXT( VK_KHR_SWAPCHAIN_EXTENSION_NAME, GetSwapchainImagesKHR )
	VK_LIB_DEVICE_FUNCTION_MANDATORY_EXT( VK_KHR_SWAPCHAIN_EXTENSION_NAME, AcquireNextImageKHR )
	VK_LIB_DEVICE_FUNCTION_MANDATORY_EXT( VK_KHR_SWAPCHAIN_EXTENSION_NAME, QueuePresentKHR )
	VK_LIB_DEVICE_FUNCTION_MANDATORY_EXT( VK_KHR_SWAPCHAIN_EXTENSION_NAME, GetDeviceGroupPresentCapabilitiesKHR )
	VK_LIB_DEVICE_FUNCTION_MANDATORY_EXT( VK_KHR_SWAPCHAIN_EXTENSION_NAME, GetDeviceGroupSurfacePresentModesKHR )
	VK_LIB_DEVICE_FUNCTION_MANDATORY_EXT( VK_KHR_SWAPCHAIN_EXTENSION_NAME, AcquireNextImage2KHR )
#endif

#ifdef VK_KHR_device_group
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_DEVICE_GROUP_EXTENSION_NAME, GetDeviceGroupPeerMemoryFeaturesKHR )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_DEVICE_GROUP_EXTENSION_NAME, CmdSetDeviceMaskKHR )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_DEVICE_GROUP_EXTENSION_NAME, CmdDispatchBaseKHR )
#endif

#ifdef VK_KHR_shader_draw_parameters
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_SHADER_DRAW_PARAMETERS_EXTENSION_NAME, TrimCommandPoolKHR )
#endif

#ifdef VK_KHR_external_memory_fd
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_EXTERNAL_MEMORY_FD_EXTENSION_NAME, GetMemoryFdKHR )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_EXTERNAL_MEMORY_FD_EXTENSION_NAME, GetMemoryFdPropertiesKHR )
#endif

#ifdef VK_KHR_external_semaphore_fd
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_EXTERNAL_SEMAPHORE_FD_EXTENSION_NAME, ImportSemaphoreFdKHR )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_EXTERNAL_SEMAPHORE_FD_EXTENSION_NAME, GetSemaphoreFdKHR )
#endif

#ifdef VK_KHR_push_descriptor
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_PUSH_DESCRIPTOR_EXTENSION_NAME, CmdPushDescriptorSetKHR )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_PUSH_DESCRIPTOR_EXTENSION_NAME, CmdPushDescriptorSetWithTemplateKHR )
#endif

#ifdef VK_KHR_descriptor_update_template
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_DESCRIPTOR_UPDATE_TEMPLATE_EXTENSION_NAME, CreateDescriptorUpdateTemplateKHR )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_DESCRIPTOR_UPDATE_TEMPLATE_EXTENSION_NAME, DestroyDescriptorUpdateTemplateKHR )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_DESCRIPTOR_UPDATE_TEMPLATE_EXTENSION_NAME, UpdateDescriptorSetWithTemplateKHR )
#endif

#ifdef VK_KHR_create_renderpass2
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_CREATE_RENDERPASS_2_EXTENSION_NAME, CreateRenderPass2KHR )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_CREATE_RENDERPASS_2_EXTENSION_NAME, CmdBeginRenderPass2KHR )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_CREATE_RENDERPASS_2_EXTENSION_NAME, CmdNextSubpass2KHR )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_CREATE_RENDERPASS_2_EXTENSION_NAME, CmdEndRenderPass2KHR )
#endif

#ifdef VK_KHR_shared_presentable_image
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_SHARED_PRESENTABLE_IMAGE_EXTENSION_NAME, GetSwapchainStatusKHR )
#endif

#ifdef VK_KHR_external_fence_fd
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_EXTERNAL_FENCE_FD_EXTENSION_NAME, ImportFenceFdKHR )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_EXTERNAL_FENCE_FD_EXTENSION_NAME, GetFenceFdKHR )
#endif

#ifdef VK_KHR_get_memory_requirements2
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_GET_MEMORY_REQUIREMENTS_2_EXTENSION_NAME, GetImageMemoryRequirements2KHR )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_GET_MEMORY_REQUIREMENTS_2_EXTENSION_NAME, GetBufferMemoryRequirements2KHR )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_GET_MEMORY_REQUIREMENTS_2_EXTENSION_NAME, GetImageSparseMemoryRequirements2KHR )
#endif

#ifdef VK_KHR_sampler_ycbcr_conversion
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION_NAME, CreateSamplerYcbcrConversionKHR )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION_NAME, DestroySamplerYcbcrConversionKHR )
#endif

#ifdef VK_KHR_bind_memory2
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_BIND_MEMORY_2_EXTENSION_NAME, BindBufferMemory2KHR )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_BIND_MEMORY_2_EXTENSION_NAME, BindImageMemory2KHR )
#endif

#ifdef VK_KHR_maintenance3
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_MAINTENANCE3_EXTENSION_NAME, GetDescriptorSetLayoutSupportKHR )
#endif

#ifdef VK_KHR_draw_indirect_count
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_DRAW_INDIRECT_COUNT_EXTENSION_NAME, CmdDrawIndirectCountKHR )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_KHR_DRAW_INDIRECT_COUNT_EXTENSION_NAME, CmdDrawIndexedIndirectCountKHR )
#endif

#ifdef VK_EXT_debug_marker
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_DEBUG_MARKER_EXTENSION_NAME, DebugMarkerSetObjectTagEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_DEBUG_MARKER_EXTENSION_NAME, DebugMarkerSetObjectNameEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_DEBUG_MARKER_EXTENSION_NAME, CmdDebugMarkerBeginEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_DEBUG_MARKER_EXTENSION_NAME, CmdDebugMarkerEndEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_DEBUG_MARKER_EXTENSION_NAME, CmdDebugMarkerInsertEXT )
#endif

#ifdef VK_EXT_transform_feedback
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_TRANSFORM_FEEDBACK_EXTENSION_NAME, CmdBindTransformFeedbackBuffersEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_TRANSFORM_FEEDBACK_EXTENSION_NAME, CmdBeginTransformFeedbackEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_TRANSFORM_FEEDBACK_EXTENSION_NAME, CmdEndTransformFeedbackEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_TRANSFORM_FEEDBACK_EXTENSION_NAME, CmdBeginQueryIndexedEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_TRANSFORM_FEEDBACK_EXTENSION_NAME, CmdEndQueryIndexedEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_TRANSFORM_FEEDBACK_EXTENSION_NAME, CmdDrawIndirectByteCountEXT )
#endif

#ifdef VK_AMD_draw_indirect_count
	VK_LIB_DEVICE_FUNCTION_EXT( VK_AMD_DRAW_INDIRECT_COUNT_EXTENSION_NAME, CmdDrawIndirectCountAMD )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_AMD_DRAW_INDIRECT_COUNT_EXTENSION_NAME, CmdDrawIndexedIndirectCountAMD )
#endif

#ifdef VK_AMD_shader_info
	VK_LIB_DEVICE_FUNCTION_EXT( VK_AMD_SHADER_INFO_EXTENSION_NAME, GetShaderInfoAMD )
#endif

#ifdef VK_EXT_conditional_rendering
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_CONDITIONAL_RENDERING_EXTENSION_NAME, CmdBeginConditionalRenderingEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_CONDITIONAL_RENDERING_EXTENSION_NAME, CmdEndConditionalRenderingEXT )
#endif

#ifdef VK_NVX_device_generated_commands
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NVX_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME, CmdProcessCommandsNVX )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NVX_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME, CmdReserveSpaceForCommandsNVX )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NVX_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME, CreateIndirectCommandsLayoutNVX )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NVX_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME, DestroyIndirectCommandsLayoutNVX )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NVX_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME, CreateObjectTableNVX )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NVX_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME, DestroyObjectTableNVX )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NVX_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME, RegisterObjectsNVX )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NVX_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME, UnregisterObjectsNVX )
#endif

#ifdef VK_NV_clip_space_w_scaling
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_CLIP_SPACE_W_SCALING_EXTENSION_NAME, CmdSetViewportWScalingNV )
#endif

#ifdef VK_EXT_display_control
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_DISPLAY_CONTROL_EXTENSION_NAME, DisplayPowerControlEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_DISPLAY_CONTROL_EXTENSION_NAME, RegisterDeviceEventEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_DISPLAY_CONTROL_EXTENSION_NAME, RegisterDisplayEventEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_DISPLAY_CONTROL_EXTENSION_NAME, GetSwapchainCounterEXT )
#endif

#ifdef VK_GOOGLE_display_timing
	VK_LIB_DEVICE_FUNCTION_EXT( VK_GOOGLE_DISPLAY_TIMING_EXTENSION_NAME, GetRefreshCycleDurationGOOGLE )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_GOOGLE_DISPLAY_TIMING_EXTENSION_NAME, GetPastPresentationTimingGOOGLE )
#endif

#ifdef VK_EXT_discard_rectangles
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_DISCARD_RECTANGLES_EXTENSION_NAME, CmdSetDiscardRectangleEXT )
#endif

#ifdef VK_EXT_hdr_metadata
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_HDR_METADATA_EXTENSION_NAME, SetHdrMetadataEXT )
#endif

#ifdef VK_EXT_debug_utils
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_DEBUG_UTILS_EXTENSION_NAME, SetDebugUtilsObjectNameEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_DEBUG_UTILS_EXTENSION_NAME, SetDebugUtilsObjectTagEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_DEBUG_UTILS_EXTENSION_NAME, QueueBeginDebugUtilsLabelEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_DEBUG_UTILS_EXTENSION_NAME, QueueEndDebugUtilsLabelEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_DEBUG_UTILS_EXTENSION_NAME, QueueInsertDebugUtilsLabelEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_DEBUG_UTILS_EXTENSION_NAME, CmdBeginDebugUtilsLabelEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_DEBUG_UTILS_EXTENSION_NAME, CmdEndDebugUtilsLabelEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_DEBUG_UTILS_EXTENSION_NAME, CmdInsertDebugUtilsLabelEXT )
#endif

#ifdef VK_EXT_sample_locations
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_SAMPLE_LOCATIONS_EXTENSION_NAME, CmdSetSampleLocationsEXT )
#endif

#ifdef VK_EXT_image_drm_format_modifier
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_IMAGE_DRM_FORMAT_MODIFIER_EXTENSION_NAME, GetImageDrmFormatModifierPropertiesEXT )
#endif

#ifdef VK_EXT_validation_cache
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_VALIDATION_CACHE_EXTENSION_NAME, CreateValidationCacheEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_VALIDATION_CACHE_EXTENSION_NAME, DestroyValidationCacheEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_VALIDATION_CACHE_EXTENSION_NAME, MergeValidationCachesEXT )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_VALIDATION_CACHE_EXTENSION_NAME, GetValidationCacheDataEXT )
#endif

#ifdef VK_NV_shading_rate_image
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_SHADING_RATE_IMAGE_EXTENSION_NAME, CmdBindShadingRateImageNV )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_SHADING_RATE_IMAGE_EXTENSION_NAME, CmdSetViewportShadingRatePaletteNV )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_SHADING_RATE_IMAGE_EXTENSION_NAME, CmdSetCoarseSampleOrderNV )
#endif

#ifdef VK_NV_ray_tracing
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_RAY_TRACING_EXTENSION_NAME, CreateAccelerationStructureNV )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_RAY_TRACING_EXTENSION_NAME, DestroyAccelerationStructureNV )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_RAY_TRACING_EXTENSION_NAME, GetAccelerationStructureMemoryRequirementsNV )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_RAY_TRACING_EXTENSION_NAME, BindAccelerationStructureMemoryNV )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_RAY_TRACING_EXTENSION_NAME, CmdBuildAccelerationStructureNV )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_RAY_TRACING_EXTENSION_NAME, CmdCopyAccelerationStructureNV )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_RAY_TRACING_EXTENSION_NAME, CmdTraceRaysNV )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_RAY_TRACING_EXTENSION_NAME, CreateRayTracingPipelinesNV )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_RAY_TRACING_EXTENSION_NAME, GetRayTracingShaderGroupHandlesNV )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_RAY_TRACING_EXTENSION_NAME, GetAccelerationStructureHandleNV )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_RAY_TRACING_EXTENSION_NAME, CmdWriteAccelerationStructuresPropertiesNV )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_RAY_TRACING_EXTENSION_NAME, CompileDeferredNV )
#endif

#ifdef VK_EXT_external_memory_host
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_EXTERNAL_MEMORY_HOST_EXTENSION_NAME, GetMemoryHostPointerPropertiesEXT )
#endif

#ifdef VK_AMD_buffer_marker
	VK_LIB_DEVICE_FUNCTION_EXT( VK_AMD_BUFFER_MARKER_EXTENSION_NAME, CmdWriteBufferMarkerAMD )
#endif

#ifdef VK_EXT_calibrated_timestamps
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_CALIBRATED_TIMESTAMPS_EXTENSION_NAME, GetCalibratedTimestampsEXT )
#endif

#ifdef VK_NV_mesh_shader
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_MESH_SHADER_EXTENSION_NAME, CmdDrawMeshTasksNV )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_MESH_SHADER_EXTENSION_NAME, CmdDrawMeshTasksIndirectNV )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_MESH_SHADER_EXTENSION_NAME, CmdDrawMeshTasksIndirectCountNV )
#endif

#ifdef VK_NV_scissor_exclusive
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_SCISSOR_EXCLUSIVE_EXTENSION_NAME, CmdSetExclusiveScissorNV )
#endif

#ifdef VK_NV_device_diagnostic_checkpoints
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_DEVICE_DIAGNOSTIC_CHECKPOINTS_EXTENSION_NAME, CmdSetCheckpointNV )
	VK_LIB_DEVICE_FUNCTION_EXT( VK_NV_DEVICE_DIAGNOSTIC_CHECKPOINTS_EXTENSION_NAME, GetQueueCheckpointDataNV )
#endif

#ifdef VK_EXT_buffer_device_address
	VK_LIB_DEVICE_FUNCTION_EXT( VK_EXT_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME, GetBufferDeviceAddressEXT )
#endif

#undef VK_LIB_DEVICE_FUNCTION_EXT
#undef VK_LIB_DEVICE_FUNCTION
