ashespp: ashes::PushConstantsBuffer< T > Class Template Reference
ashes::PushConstantsBuffer< T > Class Template Reference
Template class wrapping a PushConstantsBufferBase.
Public Member Functions
PushConstantsBuffer (VkShaderStageFlags stageFlags, PushConstantArray const &variables)
Constructor.
uint32_t getOffset () const
uint32_t getSize () const
VkShaderStageFlags getStageFlags () const
T const * getData () const
A pointer to the buffer data.
T * getData ()
A pointer to the buffer data.
PushConstantArray::const_iterator begin () const
PushConstantArray::const_iterator end () const
PushConstantsBufferBase const & getBuffer () const
The internal PCB.
PushConstantsBufferBase & getBuffer ()
The internal PCB.
Detailed Description
template<typename T>
class ashes::PushConstantsBuffer< T >
Template class wrapping a PushConstantsBufferBase.
Constructor & Destructor Documentation
PushConstantsBuffer()
template<typename T> ashes::PushConstantsBuffer< T >::PushConstantsBuffer (VkShaderStageFlags stageFlags, PushConstantArray const & variables) inline
Constructor.
Parameters
[in] stageFlags Specifies the shader stages that will use the push constants in the updated range.
[in] variables The constants contained in the buffer.
Member Function Documentation
begin()
template<typename T> PushConstantArray::const_iterator ashes::PushConstantsBuffer< T >::begin () const inline
Returns
The beginning of the constants array.
References ashes::PushConstantsBufferBase::begin(), and ashes::PushConstantsBuffer< T >::getBuffer().
end()
template<typename T> PushConstantArray::const_iterator ashes::PushConstantsBuffer< T >::end () const inline
Returns
The end of the constants array.
References ashes::PushConstantsBufferBase::end(), and ashes::PushConstantsBuffer< T >::getBuffer().
getBuffer() [1/2]
template<typename T> PushConstantsBufferBase const& ashes::PushConstantsBuffer< T >::getBuffer () const inline
The internal PCB.
Referenced by ashes::PushConstantsBuffer< T >::begin(), ashes::PushConstantsBuffer< T >::end(), ashes::PushConstantsBuffer< T >::getData(), ashes::PushConstantsBuffer< T >::getOffset(), ashes::PushConstantsBuffer< T >::getSize(), ashes::PushConstantsBuffer< T >::getStageFlags(), and ashes::CommandBuffer::pushConstants().
getBuffer() [2/2]
template<typename T> PushConstantsBufferBase& ashes::PushConstantsBuffer< T >::getBuffer () inline
The internal PCB.
getData() [1/2]
template<typename T> T const* ashes::PushConstantsBuffer< T >::getData () const inline
A pointer to the buffer data.
References ashes::PushConstantsBuffer< T >::getBuffer().
Referenced by ashes::PushConstantsBuffer< T >::getData().
getData() [2/2]
template<typename T> T* ashes::PushConstantsBuffer< T >::getData () inline
A pointer to the buffer data.
References ashes::PushConstantsBuffer< T >::getBuffer(), and ashes::PushConstantsBuffer< T >::getData().
getOffset()
template<typename T> uint32_t ashes::PushConstantsBuffer< T >::getOffset () const inline
Returns
The base offset.
References ashes::PushConstantsBuffer< T >::getBuffer(), and ashes::PushConstantsBufferBase::getOffset().
getSize()
template<typename T> uint32_t ashes::PushConstantsBuffer< T >::getSize () const inline
Returns
The data size.
References ashes::PushConstantsBuffer< T >::getBuffer(), and ashes::PushConstantsBufferBase::getSize().
getStageFlags()
template<typename T> VkShaderStageFlags ashes::PushConstantsBuffer< T >::getStageFlags () const inline
Returns
The shader stages that will use the push constants in the updated range.
References ashes::PushConstantsBuffer< T >::getBuffer(), and ashes::PushConstantsBufferBase::getStageFlags().
The documentation for this class was generated from the following files:
Z:/Projets/C++/Ashes/include/ashespp/AshesPPPrerequisites.hpp
Z:/Projets/C++/Ashes/include/ashespp/Buffer/PushConstantsBuffer.hpp