ashespp: ashes::UniformBuffer< T > Class Template Reference
ashes::UniformBuffer< T > Class Template Reference
Public Member Functions
UniformBuffer (Device const &device, VkDeviceSize count, VkBufferUsageFlags target)
void bindMemory (DeviceMemoryPtr memory)
Binds this buffer to given device memory object.
VkMemoryRequirements getMemoryRequirements () const
T const & getData (VkDeviceSize index=0) const
T & getData (VkDeviceSize index=0)
std::vector< T > const & getDatas (VkDeviceSize index=0) const
std::vector< T > & getDatas (VkDeviceSize index=0)
VkDeviceSize getAlignedSize () const
Retrieves the aligned size for an element.
UniformBufferBase const & getUbo () const
void upload (VkDeviceSize offset=0u, VkDeviceSize range=1u)
Uploads the buffer data to VRAM.
Constructor & Destructor Documentation
UniformBuffer()
template<typename T> ashes::UniformBuffer< T >::UniformBuffer (Device const & device, VkDeviceSize count, VkBufferUsageFlags target) inline
Constructor.
Parameters
[in] device The logical device.
[in] count The number of instances of the data.
[in] target The buffer usage flags.
[in] flags The memory property flags.
Member Function Documentation
bindMemory()
template<typename T> void ashes::UniformBuffer< T >::bindMemory (DeviceMemoryPtr memory) inline
Binds this buffer to given device memory object.
Parameters
[in] memory The memory object.
References ashes::UniformBufferBase::bindMemory().
getAlignedSize()
template<typename T> VkDeviceSize ashes::UniformBuffer< T >::getAlignedSize () const inline
Retrieves the aligned size for an element.
Returns
The aligned size.
References ashes::UniformBufferBase::getAlignedSize().
Referenced by ashes::DescriptorSet::createBinding(), ashes::DescriptorSet::createDynamicBinding(), and ashes::UniformBuffer< T >::upload().
getData() [1/2]
template<typename T> T const& ashes::UniformBuffer< T >::getData (VkDeviceSize index = 0) const inline
Returns
The N-th instance of the data.
getData() [2/2]
template<typename T> T& ashes::UniformBuffer< T >::getData (VkDeviceSize index = 0) inline
Returns
The N-th instance of the data.
getDatas() [1/2]
template<typename T> std::vector< T > const& ashes::UniformBuffer< T >::getDatas (VkDeviceSize index = 0) const inline
Returns
The data.
getDatas() [2/2]
template<typename T> std::vector< T >& ashes::UniformBuffer< T >::getDatas (VkDeviceSize index = 0) inline
Returns
The data.
getMemoryRequirements()
template<typename T> VkMemoryRequirements ashes::UniformBuffer< T >::getMemoryRequirements () const inline
Returns
The memory requirements for this buffer.
References ashes::UniformBufferBase::getMemoryRequirements().
getUbo()
template<typename T> UniformBufferBase const& ashes::UniformBuffer< T >::getUbo () const inline
Returns
The GPU buffer.
Referenced by ashes::DescriptorSet::createBinding(), and ashes::DescriptorSet::createDynamicBinding().
upload()
template<typename T> void ashes::UniformBuffer< T >::upload (VkDeviceSize offset = 0u, VkDeviceSize range = 1u) inline
Uploads the buffer data to VRAM.
Parameters
[in] offset The offset in elements from which buffer memory is mapped.
[in] range The number of elements to map.
References ashes::BufferBase::flush(), ashes::UniformBuffer< T >::getAlignedSize(), ashes::UniformBufferBase::getBuffer(), ashes::BufferBase::lock(), and ashes::BufferBase::unlock().
The documentation for this class was generated from the following files:
Z:/Projets/C++/Ashes/include/ashespp/AshesPPPrerequisites.hpp
Z:/Projets/C++/Ashes/include/ashespp/Buffer/UniformBuffer.hpp