ashespp: ashes::Queue Class Reference
ashes::Queue Class Reference
Command buffers queue.
Public Member Functions
Queue (Device const &device, uint32_t familyIndex, uint32_t index)
~Queue ()
void submit (CommandBufferCRefArray const &commandBuffers, SemaphoreCRefArray const &semaphoresToWait, VkPipelineStageFlagsArray const &semaphoresStage, SemaphoreCRefArray const &semaphoresToSignal, Fence const *fence) const
Submits given command buffers.
VkResultArray present (SwapChainCRefArray const &swapChains, UInt32Array const &imagesIndex, SemaphoreCRefArray const &semaphoresToWait) const
Presents the swapchains.
void waitIdle () const
Waits for the queue to be idle.
VkResult present (SwapChain const &swapChain, uint32_t imageIndex, Semaphore const &semaphoreToWait) const
Presents a swapchain.
uint32_t getFamilyIndex () const
uint32_t getIndex () const
void submit (CommandBuffer const &commandBuffer, Fence const *fence) const
Submits given command buffer.
void submit (CommandBuffer const &commandBuffer, Semaphore const &semaphoreToWait, VkPipelineStageFlags const &semaphoreStage, Semaphore const &semaphoreToSignal, Fence const *fence) const
Submits given command buffer.
operator VkQueue const & () const
VkQueue implicit cast operator.
Detailed Description
Command buffers queue.
Constructor & Destructor Documentation
Queue()
ashes::Queue::Queue (Device const & device, uint32_t familyIndex, uint32_t index)
~Queue()
ashes::Queue::~Queue ()
Member Function Documentation
getFamilyIndex()
uint32_t ashes::Queue::getFamilyIndex () const inline
Returns
The queue family index.
getIndex()
uint32_t ashes::Queue::getIndex () const inline
Returns
The queue index within its family.
operator VkQueue const &()
ashes::Queue::operator VkQueue const & () const inline
VkQueue implicit cast operator.
present() [1/2]
VkResultArray ashes::Queue::present (SwapChainCRefArray const & swapChains, UInt32Array const & imagesIndex, SemaphoreCRefArray const & semaphoresToWait) const
Presents the swapchains.
Parameters
[in] swapChains The swapchains.
[in] imagesIndex The image to present for each swapchain.
[in] semaphoresToWait The semaphore to wait for each presented swapchain.
Returns
The result for each swapchain presentation.
present() [2/2]
VkResult ashes::Queue::present (SwapChain const & swapChain, uint32_t imageIndex, Semaphore const & semaphoreToWait) const
Presents a swapchain.
Parameters
[in] swapChain The swapchain.
[in] imageIndex The image to present.
[in] semaphoreToWait The semaphore to wait.
Returns
The presentation result.
submit() [1/3]
void ashes::Queue::submit (CommandBufferCRefArray const & commandBuffers, SemaphoreCRefArray const & semaphoresToWait, VkPipelineStageFlagsArray const & semaphoresStage, SemaphoreCRefArray const & semaphoresToSignal, Fence const * fence) const
Submits given command buffers.
Parameters
[in] commandBuffers The command buffers.
[in] semaphoresToWait The semaphores to wait.
[in] semaphoresStage The semaphores respective stages.
[in] semaphoresToSignal The semaphores to signal.
[in] fence An optional fence.
Returns
true on ok.
Referenced by submit().
submit() [2/3]
void ashes::Queue::submit (CommandBuffer const & commandBuffer, Fence const * fence) const inline
Submits given command buffer.
Parameters
[in] commandBuffer The command buffer.
[in] fence An optional fence.
Returns
true on ok.
References submit().
submit() [3/3]
void ashes::Queue::submit (CommandBuffer const & commandBuffer, Semaphore const & semaphoreToWait, VkPipelineStageFlags const & semaphoreStage, Semaphore const & semaphoreToSignal, Fence const * fence) const inline
Submits given command buffer.
Parameters
[in] commandBuffer The command buffer.
[in] semaphoreToWait The semaphore to wait.
[in] semaphoreStage The semaphore respective stages.
[in] semaphoreToSignal The semaphore to signal.
[in] fence An optional fence.
Returns
true on ok.
References submit().
waitIdle()
void ashes::Queue::waitIdle () const
Waits for the queue to be idle.
Returns
true on ok.
The documentation for this class was generated from the following file:
Z:/Projets/C++/Ashes/include/ashespp/Command/Queue.hpp