/*
This file belongs to Ashes.
See LICENSE file in root folder
*/
#pragma once

#ifdef GL_SUBPIXEL_BITS
#undef GL_SUBPIXEL_BITS
#endif
#ifdef GL_MAX_TEXTURE_SIZE
#undef GL_MAX_TEXTURE_SIZE
#endif
#ifdef GL_MAX_VIEWPORT_DIMS
#undef GL_MAX_VIEWPORT_DIMS
#endif
#ifdef GL_POINT_SIZE_RANGE
#undef GL_POINT_SIZE_RANGE
#endif
#ifdef GL_POINT_SIZE_GRANULARITY
#undef GL_POINT_SIZE_GRANULARITY
#endif
#ifdef GL_LINE_WIDTH_GRANULARITY
#undef GL_LINE_WIDTH_GRANULARITY
#endif

namespace ashes::gl
{
	enum GlGetParameter
	{
		GL_SMOOTH_LINE_WIDTH_RANGE = 0x0B22,
		GL_ALIASED_LINE_WIDTH_RANGE = 0x846E,
		GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT = 0x8A34,
		GL_MAX_TEXTURE_SIZE = 0x0D33,
		GL_SUBPIXEL_BITS = 0x0D50,
		GL_MAX_3D_TEXTURE_SIZE = 0x8073,
		GL_MAX_ARRAY_TEXTURE_LAYERS = 0x88FF,
		GL_MAX_CLIP_DISTANCES = 0x0D32,
		GL_MAX_COLOR_ATTACHMENTS = 0x8CDF,
		GL_MAX_COLOR_TEXTURE_SAMPLES = 0x910E,
		GL_MAX_COMBINED_ATOMIC_COUNTERS = 0x92D7,
		GL_MAX_COMBINED_CLIP_AND_CULL_DISTANCES = 0x82FA,
		GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS = 0x8266,
		GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS = 0x8A33,
		GL_MAX_COMBINED_IMAGE_UNIFORMS = 0x90CF,
		GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES = 0x8F39,
		GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS = 0x90DC,
		GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS = 0x8E1E,
		GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS = 0x8E1F,
		GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 0x8B4D,
		GL_MAX_COMBINED_UNIFORM_BLOCKS = 0x8A2E,
		GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS = 0x8A31,
		GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS = 0x8264,
		GL_MAX_COMPUTE_ATOMIC_COUNTERS = 0x8265,
		GL_MAX_COMPUTE_FIXED_GROUP_INVOCATIONS = 0x90EB,
		GL_MAX_COMPUTE_FIXED_GROUP_SIZE = 0x91BF,
		GL_MAX_COMPUTE_IMAGE_UNIFORMS = 0x91BD,
		GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS = 0x90DB,
		GL_MAX_COMPUTE_SHARED_MEMORY_SIZE = 0x8262,
		GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS = 0x91BC,
		GL_MAX_COMPUTE_UNIFORM_BLOCKS = 0x91BB,
		GL_MAX_COMPUTE_UNIFORM_COMPONENTS = 0x8263,
		GL_MAX_COMPUTE_VARIABLE_GROUP_INVOCATIONS = 0x9344,
		GL_MAX_COMPUTE_VARIABLE_GROUP_SIZE = 0x9345,
		GL_MAX_COMPUTE_WORK_GROUP_COUNT = 0x91BE,
		GL_MAX_CONVOLUTION_HEIGHT = 0x801B,
		GL_MAX_CONVOLUTION_WIDTH = 0x801A,
		GL_MAX_CUBE_MAP_TEXTURE_SIZE = 0x851C,
		GL_MAX_CULL_DISTANCES = 0x82F9,
		GL_MAX_DEPTH_TEXTURE_SAMPLES = 0x910F,
		GL_MAX_DRAW_BUFFERS = 0x8824,
		GL_MAX_DUAL_SOURCE_DRAW_BUFFERS = 0x88FC,
		GL_MAX_ELEMENTS_INDICES = 0x80E9,
		GL_MAX_ELEMENTS_VERTICES = 0x80E8,
		GL_MAX_FRAGMENT_ATOMIC_COUNTERS = 0x92D6,
		GL_MAX_FRAGMENT_IMAGE_UNIFORMS = 0x90CE,
		GL_MAX_FRAGMENT_INPUT_COMPONENTS = 0x9125,
		GL_MAX_FRAGMENT_INTERPOLATION_OFFSET = 0x8E5C,
		GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS = 0x90DA,
		GL_MAX_FRAGMENT_UNIFORM_BLOCKS = 0x8A2D,
		GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 0x8B49,
		GL_MAX_FRAMEBUFFER_HEIGHT = 0x9316,
		GL_MAX_FRAMEBUFFER_LAYERS = 0x9317,
		GL_MAX_FRAMEBUFFER_SAMPLES = 0x9318,
		GL_MAX_FRAMEBUFFER_WIDTH = 0x9315,
		GL_MAX_GEOMETRY_ATOMIC_COUNTERS = 0x92D5,
		GL_MAX_GEOMETRY_IMAGE_UNIFORMS = 0x90CD,
		GL_MAX_GEOMETRY_INPUT_COMPONENTS = 0x9123,
		GL_MAX_GEOMETRY_OUTPUT_COMPONENTS = 0x9124,
		GL_MAX_GEOMETRY_OUTPUT_VERTICES = 0x8DE0,
		GL_MAX_GEOMETRY_SHADER_INVOCATIONS = 0x8E5A,
		GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS = 0x90D7,
		GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS = 0x8C29,
		GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS = 0x8DE1,
		GL_MAX_GEOMETRY_UNIFORM_BLOCKS = 0x8A2C,
		GL_MAX_GEOMETRY_UNIFORM_COMPONENTS = 0x8DDF,
		GL_MAX_GEOMETRY_VARYING_COMPONENTS = 0x8DDD,
		GL_MAX_IMAGE_SAMPLES = 0x906D,
		GL_MAX_IMAGE_UNITS = 0x8F38,
		GL_MAX_INTEGER_SAMPLES = 0x9110,
		GL_MAX_PATCH_VERTICES = 0x8E7D,
		GL_MAX_PROGRAM_ALU_INSTRUCTIONS = 0x880B,
		GL_MAX_PROGRAM_NATIVE_ALU_INSTRUCTIONS = 0x880E,
		GL_MAX_PROGRAM_NATIVE_TEX_INDIRECTIONS = 0x8810,
		GL_MAX_PROGRAM_NATIVE_TEX_INSTRUCTIONS = 0x880F,
		GL_MAX_PROGRAM_TEX_INDIRECTIONS = 0x880D,
		GL_MAX_PROGRAM_TEX_INSTRUCTIONS = 0x880C,
		GL_MAX_PROGRAM_TEXEL_OFFSET = 0x8905,
		GL_MAX_PROGRAM_TEXTURE_GATHER_COMPONENTS = 0x8F9F,
		GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET = 0x8E5F,
		GL_MAX_RECTANGLE_TEXTURE_SIZE = 0x84F8,
		GL_MAX_SAMPLE_MASK_WORDS = 0x8E59,
		GL_MAX_SAMPLES = 0x8D57,
		GL_MAX_SERVER_WAIT_TIMEOUT = 0x9111,
		GL_MAX_SHADER_STORAGE_BLOCK_SIZE = 0x90DE,
		GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS = 0x90DD,
		GL_MAX_SUBROUTINE_UNIFORM_LOCATIONS = 0x8DE8,
		GL_MAX_SUBROUTINES = 0x8DE7,
		GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS = 0x92D3,
		GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS = 0x90CB,
		GL_MAX_TESS_CONTROL_INPUT_COMPONENTS = 0x886C,
		GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS = 0x8E83,
		GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS = 0x90D8,
		GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS = 0x8E81,
		GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS = 0x8E85,
		GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS = 0x8E89,
		GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS = 0x8E7F,
		GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS = 0x92D4,
		GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS = 0x90CC,
		GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS = 0x886D,
		GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS = 0x8E86,
		GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS = 0x90D9,
		GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS = 0x8E82,
		GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS = 0x8E8A,
		GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS = 0x8E80,
		GL_MAX_TESS_GEN_LEVEL = 0x8E7E,
		GL_MAX_TESS_PATCH_COMPONENTS = 0x8E84,
		GL_MAX_TEXTURE_BUFFER_SIZE = 0x8C2B,
		GL_MAX_TEXTURE_COORDS = 0x8871,
		GL_MAX_TEXTURE_IMAGE_UNITS = 0x8872,
		GL_MAX_TEXTURE_LOD_BIAS = 0x84FD,
		GL_MAX_TEXTURE_MAX_ANISOTROPY = 0x84FF,
		GL_MAX_UNIFORM_BLOCK_SIZE = 0x8A30,
		GL_MAX_UNIFORM_BUFFER_BINDINGS = 0x8A2F,
		GL_UNIFORM_BUFFER_SIZE = 0x8A2A,
		GL_MAX_UNIFORM_LOCATIONS = 0x826E,
		GL_MAX_VARYING_FLOATS = 0x8B4B,
		GL_MAX_VERTEX_ATOMIC_COUNTERS = 0x92D2,
		GL_MAX_VERTEX_ATTRIB_BINDINGS = 0x82DA,
		GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET = 0x82D9,
		GL_MAX_VERTEX_ATTRIB_STRIDE = 0x82E5,
		GL_MAX_VERTEX_ATTRIBS = 0x8869,
		GL_MAX_VERTEX_IMAGE_UNIFORMS = 0x90CA,
		GL_MAX_VERTEX_OUTPUT_COMPONENTS = 0x9122,
		GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS = 0x90D6,
		GL_MAX_VERTEX_STREAMS = 0x8E71,
		GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 0x8B4C,
		GL_MAX_VERTEX_UNIFORM_BLOCKS = 0x8A2B,
		GL_MAX_VERTEX_UNIFORM_COMPONENTS = 0x8B4A,
		GL_MAX_VERTEX_UNITS = 0x86A4,
		GL_MAX_VERTEX_VARYING_COMPONENTS = 0x8DDE,
		GL_MAX_VIEWPORT_DIMS = 0x0D3A,
		GL_MIN_FRAGMENT_INTERPOLATION_OFFSET = 0x8E5B,
		GL_MIN_LOD_WARNING = 0x919C,// AMD
		GL_MIN_PROGRAM_TEXEL_OFFSET = 0x8904,
		GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET = 0x8E5E,
		GL_MIN_SAMPLE_SHADING_VALUE = 0x8C37,
		GL_MIN_SPARSE_LEVEL = 0x919B,// AMD
		GL_MAX_VIEWPORTS = 0x825B,
		GL_POINT_SIZE_RANGE = 0x0B12,
		GL_POINT_SIZE_GRANULARITY = 0x0B13,
		GL_LINE_WIDTH_GRANULARITY = 0x0B23,
		GL_GPU_MEMORY_INFO_TOTAL_AVAILABLE_MEMORY_NVX = 0x9048,
		GL_TEXTURE_FREE_MEMORY_ATI = 0x87FC,
	};
	std::string getName( GlGetParameter value );
	inline std::string toString( GlGetParameter value ) { return getName( value ); }
}
