RendererLib: renderer::Debug Namespace Reference
renderer::Debug Namespace Reference
Classes
struct Backtrace
class Backtraced
Helper class used to enable allocation backtrace retrieval.
Functions
void initialise ()
Initialises debug data.
void cleanup ()
Cleans up debug data.
std::ostream & operator<< (std::ostream &p_stream, Backtrace const &)
Puts the backtrace into a stream.
std::ostream & operator<< (std::ostream &p_stream, Backtraced const &p_traced)
Function Documentation
cleanup()
void renderer::Debug::cleanup ()
Cleans up debug data.
Referenced by renderer::Debug::Backtrace::Backtrace().
initialise()
void renderer::Debug::initialise ()
Initialises debug data.
Referenced by renderer::Debug::Backtrace::Backtrace().
operator<<() [1/2]
std::ostream& renderer::Debug::operator<< (std::ostream & p_stream, Backtrace const &)
Puts the backtrace into a stream.
Parameters
[in,out] p_stream The stream
Referenced by renderer::Debug::Backtrace::Backtrace().
operator<<() [2/2]
std::ostream& renderer::Debug::operator<< (std::ostream & p_stream, Backtraced const & p_traced) inline
References renderer::Debug::Backtraced::m_callStack.