ashespp: ashes::CommandBuffer Class Reference
ashes::CommandBuffer Class Reference
A command buffer.
Public Member Functions
CommandBuffer (Device const &device, CommandPool const &pool, bool primary=true)
Constructor.
~CommandBuffer ()
Destructor.
void begin (VkCommandBufferBeginInfo const &info) const
Starts recording the command buffer.
void begin (VkCommandBufferUsageFlags flags=0u) const
Starts recording the command buffer.
void begin (VkCommandBufferUsageFlags flags, VkCommandBufferInheritanceInfo &inheritanceInfo) const
Starts recording the command buffer as a secondary command buffer.
void end () const
Ends the command buffer recording.
void reset (VkCommandBufferResetFlags flags=0u) const
Reset a command buffer to the initial state.
void beginRenderPass (VkRenderPassBeginInfo const &beginInfo, VkSubpassContents contents) const
Begins a new render pass.
void beginRenderPass (RenderPass const &renderPass, FrameBuffer const &frameBuffer, VkClearValueArray const &clearValues, VkSubpassContents contents) const
Begins a new render pass.
void nextSubpass (VkSubpassContents contents) const
Transition to the next subpass of a render pass.
void endRenderPass () const
End the current render pass.
void executeCommands (CommandBufferCRefArray const &commands) const
Execute a secondary command buffer.
void clear (ImageView const &image, VkClearColorValue const &colour) const
Clear a color image.
void clear (ImageView const &image, VkClearDepthStencilValue const &value) const
Clear a depth and/or stencil image.
void clearAttachments (VkClearAttachmentArray const &clearAttachments, VkClearRectArray const &clearRects)
Clear regions within currently bound framebuffer attachments.
void pipelineBarrier (VkPipelineStageFlags after, VkPipelineStageFlags before, VkDependencyFlags dependencyFlags, VkMemoryBarrierArray const &memoryBarriers, VkBufferMemoryBarrierArray const &bufferMemoryBarriers, VkImageMemoryBarrierArray const &imaegMemoryBarriers) const
Defines a memory dependency between commands that were submitted before it, and those submitted after it.
void memoryBarrier (VkPipelineStageFlags after, VkPipelineStageFlags before, VkBufferMemoryBarrier const &transitionBarrier) const
Defines a memory dependency between commands that were submitted before it, and those submitted after it.
void memoryBarrier (VkPipelineStageFlags after, VkPipelineStageFlags before, VkImageMemoryBarrier const &transitionBarrier) const
Defines a memory dependency between commands that were submitted before it, and those submitted after it.
void bindPipeline (GraphicsPipeline const &pipeline, VkPipelineBindPoint bindingPoint=VkPipelineBindPoint::VK_PIPELINE_BIND_POINT_GRAPHICS) const
Binds a pipeline to the command buffer.
void bindPipeline (ComputePipeline const &pipeline, VkPipelineBindPoint bindingPoint=VkPipelineBindPoint::VK_PIPELINE_BIND_POINT_COMPUTE) const
Binds a compute pipeline to the command buffer.
void bindVertexBuffers (uint32_t firstBinding, BufferCRefArray const &buffers, UInt64Array offsets) const
Binds vertex buffers to the command buffer.
void bindIndexBuffer (BufferBase const &buffer, uint64_t offset, VkIndexType indexType) const
Binds an index buffer to the command buffer.
void bindDescriptorSets (DescriptorSetCRefArray const &descriptorSet, PipelineLayout const &layout, UInt32Array const &dynamicOffsets, VkPipelineBindPoint bindingPoint=VkPipelineBindPoint::VK_PIPELINE_BIND_POINT_GRAPHICS) const
Binds descriptor sets to the command buffer.
void setViewport (uint32_t firstViewport, VkViewportArray const &viewports) const
Defines the currently bound pipeline viewport.
void setViewport (VkViewport const &viewport) const
Defines the currently bound pipeline viewport.
void setScissor (uint32_t firstScissor, VkScissorArray const &scissors) const
Defines the currently bound pipeline scissor.
void setScissor (VkRect2D const &scissor) const
Defines the currently bound pipeline scissor.
void draw (uint32_t vtxCount, uint32_t instCount=1u, uint32_t firstVertex=0u, uint32_t firstInstance=0u) const
Draws some vertices.
void drawIndexed (uint32_t indexCount, uint32_t instCount=1u, uint32_t firstIndex=0u, uint32_t vertexOffset=0u, uint32_t firstInstance=0u) const
Draws some indexed vertices.
void drawIndirect (BufferBase const &buffer, uint32_t offset, uint32_t drawCount, uint32_t stride) const
Perform an indirect draw.
void drawIndexedIndirect (BufferBase const &buffer, uint32_t offset, uint32_t drawCount, uint32_t stride) const
Perform an indexed indirect draw.
void copyToImage (VkBufferImageCopyArray const &copyInfo, BufferBase const &src, Image const &dst) const
Copies data from a buffer to an image.
void copyToBuffer (VkBufferImageCopyArray const &copyInfo, Image const &src, BufferBase const &dst) const
Copies data from a buffer to an image.
void copyBuffer (VkBufferCopy const &copyInfo, BufferBase const &src, BufferBase const &dst) const
Copies data from a buffer to another one.
void copyImage (VkImageCopy const &copyInfo, Image const &src, VkImageLayout srcLayout, Image const &dst, VkImageLayout dstLayout) const
Copies data from an image to another one.
void blitImage (Image const &srcImage, VkImageLayout srcLayout, Image const &dstImage, VkImageLayout dstLayout, std::vector< VkImageBlit > const &regions, VkFilter filter) const
Copy regions of an image to another one.
void resetQueryPool (QueryPool const &pool, uint32_t firstQuery, uint32_t queryCount) const
Resets a range of queries in a query pool.
void beginQuery (QueryPool const &pool, uint32_t query, VkQueryControlFlags flags) const
Begins a query.
void endQuery (QueryPool const &pool, uint32_t query) const
Ends a query.
void writeTimestamp (VkPipelineStageFlagBits pipelineStage, QueryPool const &pool, uint32_t query) const
Writes a timestamp to given query result.
void pushConstants (PipelineLayout const &layout, VkShaderStageFlags stageFlags, uint32_t offset, uint32_t size, void const *data) const
Updates the values of push constants.
void dispatch (uint32_t groupCountX, uint32_t groupCountY, uint32_t groupCountZ) const
Dispatch compute work items.
void dispatchIndirect (BufferBase const &buffer, uint32_t offset) const
Dispatch compute work items using indirect parameters.
void setLineWidth (float width) const
Specifies the lines width, if this is a dynamic state in the pipeline.
void setDepthBias (float constantFactor, float clamp, float slopeFactor) const
Specifies the lines width, if this is a dynamic state in the pipeline.
void setEvent (Event const &event, VkPipelineStageFlags stageMask) const
Sets an event to signaled state.
void resetEvent (Event const &event, VkPipelineStageFlags stageMask) const
Sets an event to signaled state.
void waitEvents (EventCRefArray const &events, VkPipelineStageFlags srcStageMask, VkPipelineStageFlags dstStageMask, VkBufferMemoryBarrierArray const &bufferMemoryBarriers, VkImageMemoryBarrierArray const &imageMemoryBarriers) const
Wait for one or more events to be signaled on a device.
void bindVertexBuffer (uint32_t binding, BufferBase const &buffer, uint64_t offset) const
Binds a vertex buffer to the command buffer.
void copyToImage (VkBufferImageCopy const &copyInfo, BufferBase const &src, Image const &dst) const
Copies data from a buffer to an image.
void copyToBuffer (VkBufferImageCopy const &copyInfo, Image const &src, BufferBase const &dst) const
Copies data from a buffer to an image.
void copyBuffer (BufferBase const &src, BufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copies data from a buffer to another one.
void bindDescriptorSet (DescriptorSet const &descriptorSet, PipelineLayout const &layout, UInt32Array const &dynamicOffsets, VkPipelineBindPoint bindingPoint=VkPipelineBindPoint::VK_PIPELINE_BIND_POINT_GRAPHICS) const
Binds a descriptor set to the command buffer.
void bindDescriptorSet (DescriptorSet const &descriptorSet, PipelineLayout const &layout, VkPipelineBindPoint bindingPoint=VkPipelineBindPoint::VK_PIPELINE_BIND_POINT_GRAPHICS) const
Binds a descriptor set to the command buffer.
void bindDescriptorSets (DescriptorSetCRefArray const &descriptorSet, PipelineLayout const &layout, VkPipelineBindPoint bindingPoint=VkPipelineBindPoint::VK_PIPELINE_BIND_POINT_GRAPHICS) const
Binds descriptor sets to the command buffer.
void copyBuffer (BufferBase const &src, VertexBufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copie les données d'un tampon vers un autre tampon.
void copyBuffer (VertexBufferBase const &src, BufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copie les données d'un tampon vers un autre tampon.
void copyBuffer (VertexBufferBase const &src, VertexBufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copie les données d'un tampon vers un autre tampon.
void copyBuffer (BufferBase const &src, UniformBufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copie les données d'un tampon vers un autre tampon.
void copyBuffer (UniformBufferBase const &src, BufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copie les données d'un tampon vers un autre tampon.
void copyBuffer (UniformBufferBase const &src, UniformBufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copie les données d'un tampon vers un autre tampon.
void copyImage (ImageView const &src, ImageView const &dst) const
Copies data from an image to another one.
void pushConstants (PipelineLayout const &layout, PushConstantsBufferBase const &pcb) const
Updates the values of push constants.
template<typename T >
void pushConstants (PipelineLayout const &layout, PushConstantsBuffer< T > const &pcb) const
Updates the values of push constants.
operator VkCommandBuffer const & () const
VkCommandBuffer implicit cast operator.
Protected Member Functions
CommandBuffer (CommandBuffer const &)=delete
CommandBuffer & operator= (CommandBuffer const &)=delete
CommandBuffer ()=default
Detailed Description
A command buffer.
Constructor & Destructor Documentation
CommandBuffer() [1/3]
ashes::CommandBuffer::CommandBuffer (CommandBuffer const &) protected delete
CommandBuffer() [2/3]
ashes::CommandBuffer::CommandBuffer () protected default
CommandBuffer() [3/3]
ashes::CommandBuffer::CommandBuffer (Device const & device, CommandPool const & pool, bool primary = true)
Constructor.
Parameters
[in] device The logical device.
[in] pool The parent command buffer pool.
[in] primary Tells if the command buffer is primary (true) or not (false).
~CommandBuffer()
ashes::CommandBuffer::~CommandBuffer ()
Destructor.
Member Function Documentation
begin() [1/3]
void ashes::CommandBuffer::begin (VkCommandBufferBeginInfo const & info) const
Starts recording the command buffer.
Referenced by begin().
begin() [2/3]
void ashes::CommandBuffer::begin (VkCommandBufferUsageFlags flags = 0u) const inline
Starts recording the command buffer.
Parameters
[in] flags The usage flags for the command buffer.
Returns
false on any problem.
References begin().
begin() [3/3]
void ashes::CommandBuffer::begin (VkCommandBufferUsageFlags flags, VkCommandBufferInheritanceInfo & inheritanceInfo) const inline
Starts recording the command buffer as a secondary command buffer.
Parameters
[in] flags The usage flags for the command buffer.
[in] inheritanceInfo The inheritance informations.
Returns
false on any error.
References begin().
beginQuery()
void ashes::CommandBuffer::beginQuery (QueryPool const & pool, uint32_t query, VkQueryControlFlags flags) const
Begins a query.
Parameters
[in] pool The query pool.
[in] query The query index.
[in] flags The constraints on the types of queries that can be performed.
beginRenderPass() [1/2]
void ashes::CommandBuffer::beginRenderPass (VkRenderPassBeginInfo const & beginInfo, VkSubpassContents contents) const
Begins a new render pass.
beginRenderPass() [2/2]
void ashes::CommandBuffer::beginRenderPass (RenderPass const & renderPass, FrameBuffer const & frameBuffer, VkClearValueArray const & clearValues, VkSubpassContents contents) const
Begins a new render pass.
Parameters
[in] renderPass The render pass to begin.
[in] frameBuffer The framebuffer containing the attachments that are used with the render pass.
[in] clearValues The clear values for each attachment that needs to be cleared.
[in] contents Specifies how the commands in the first subpass will be provided.
bindDescriptorSet() [1/2]
void ashes::CommandBuffer::bindDescriptorSet (DescriptorSet const & descriptorSet, PipelineLayout const & layout, UInt32Array const & dynamicOffsets, VkPipelineBindPoint bindingPoint = VkPipelineBindPoint::VK_PIPELINE_BIND_POINT_GRAPHICS) const inline
Binds a descriptor set to the command buffer.
Parameters
[in] descriptorSet The descriptor set.
[in] layout The pipeline layout used to program the binding.
[in] dynamicOffsets The dynamic offsets for dynamic buffers.
[in] bindingPoint Indicates whether the descriptor wil be used by graphics or compute pipeline.
References bindDescriptorSets().
bindDescriptorSet() [2/2]
void ashes::CommandBuffer::bindDescriptorSet (DescriptorSet const & descriptorSet, PipelineLayout const & layout, VkPipelineBindPoint bindingPoint = VkPipelineBindPoint::VK_PIPELINE_BIND_POINT_GRAPHICS) const inline
Binds a descriptor set to the command buffer.
Parameters
[in] descriptorSet The descriptor set.
[in] layout The pipeline layout used to program the binding.
[in] bindingPoint Indicates whether the descriptor wil be used by graphics or compute pipeline.
References bindDescriptorSets().
bindDescriptorSets() [1/2]
void ashes::CommandBuffer::bindDescriptorSets (DescriptorSetCRefArray const & descriptorSet, PipelineLayout const & layout, UInt32Array const & dynamicOffsets, VkPipelineBindPoint bindingPoint = VkPipelineBindPoint::VK_PIPELINE_BIND_POINT_GRAPHICS) const
Binds descriptor sets to the command buffer.
Parameters
[in] descriptorSet The descriptor sets.
[in] layout The pipeline layout used to program the binding.
[in] dynamicOffsets The dynamic offsets for dynamic buffers.
[in] bindingPoint Indicates whether the descriptor wil be used by graphics or compute pipeline.
Referenced by bindDescriptorSet(), and bindDescriptorSets().
bindDescriptorSets() [2/2]
void ashes::CommandBuffer::bindDescriptorSets (DescriptorSetCRefArray const & descriptorSet, PipelineLayout const & layout, VkPipelineBindPoint bindingPoint = VkPipelineBindPoint::VK_PIPELINE_BIND_POINT_GRAPHICS) const inline
Binds descriptor sets to the command buffer.
Parameters
[in] descriptorSet The descriptor sets.
[in] layout The pipeline layout used to program the binding.
[in] bindingPoint Indicates whether the descriptor wil be used by graphics or compute pipeline.
References bindDescriptorSets().
bindIndexBuffer()
void ashes::CommandBuffer::bindIndexBuffer (BufferBase const & buffer, uint64_t offset, VkIndexType indexType) const
Binds an index buffer to the command buffer.
Parameters
[in] buffer The buffer being bound.
[in] offset The starting offset in bytes within buffer used in index buffer address calculations.
[in] indexType Tells whether the indices are treated as 16 bits or 32 bits.
bindPipeline() [1/2]
void ashes::CommandBuffer::bindPipeline (GraphicsPipeline const & pipeline, VkPipelineBindPoint bindingPoint = VkPipelineBindPoint::VK_PIPELINE_BIND_POINT_GRAPHICS) const
Binds a pipeline to the command buffer.
Parameters
[in] pipeline The pipeline to be bound.
[in] bindingPoint Specifies whether to bind to the compute or graphics bind point.
bindPipeline() [2/2]
void ashes::CommandBuffer::bindPipeline (ComputePipeline const & pipeline, VkPipelineBindPoint bindingPoint = VkPipelineBindPoint::VK_PIPELINE_BIND_POINT_COMPUTE) const
Binds a compute pipeline to the command buffer.
Parameters
[in] pipeline The pipeline to be bound.
[in] bindingPoint Specifies whether to bind to the compute or graphics bind point.
bindVertexBuffer()
void ashes::CommandBuffer::bindVertexBuffer (uint32_t binding, BufferBase const & buffer, uint64_t offset) const
Binds a vertex buffer to the command buffer.
Parameters
[in] binding The index of the vertex input binding whose state is updated by the command.
[in] buffer The buffer handle.
[in] offset The array of buffer offset.
bindVertexBuffers()
void ashes::CommandBuffer::bindVertexBuffers (uint32_t firstBinding, BufferCRefArray const & buffers, UInt64Array offsets) const
Binds vertex buffers to the command buffer.
Parameters
[in] firstBinding The index of the first vertex input binding whose state is updated by the command.
[in] buffers The array of buffer handles.
[in] offsets The array of buffer offsets.
blitImage()
void ashes::CommandBuffer::blitImage (Image const & srcImage, VkImageLayout srcLayout, Image const & dstImage, VkImageLayout dstLayout, std::vector< VkImageBlit > const & regions, VkFilter filter) const
Copy regions of an image to another one.
Parameters
[in] regions The regions to blit.
[in] srcImage The source image.
[in] srcLayout The source image layout.
[in] dstImage The destination image.
[in] dstLayout The source image layout.
[in] filter The filter applied if the blit requires scaling.
clear() [1/2]
void ashes::CommandBuffer::clear (ImageView const & image, VkClearColorValue const & colour) const
Clear a color image.
Parameters
[in] image The image to clear.
[in] colour The clear colour.
clear() [2/2]
void ashes::CommandBuffer::clear (ImageView const & image, VkClearDepthStencilValue const & value) const
Clear a depth and/or stencil image.
Parameters
[in] image The image to clear.
[in] value The clear value.
clearAttachments()
void ashes::CommandBuffer::clearAttachments (VkClearAttachmentArray const & clearAttachments, VkClearRectArray const & clearRects)
Clear regions within currently bound framebuffer attachments.
Parameters
[in] clearAttachments The attachments to clear and the clear values to use.
[in] clearRects The regions within each selected attachment to clear.
copyBuffer() [1/8]
void ashes::CommandBuffer::copyBuffer (VkBufferCopy const & copyInfo, BufferBase const & src, BufferBase const & dst) const
Copies data from a buffer to another one.
Parameters
[in] copyInfo The copy informations.
[in] src The source buffer.
[in] dst The destination buffer.
copyBuffer() [2/8]
void ashes::CommandBuffer::copyBuffer (BufferBase const & src, BufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyBuffer() [3/8]
void ashes::CommandBuffer::copyBuffer (BufferBase const & src, VertexBufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copie les données d'un tampon vers un autre tampon.
Parameters
[in] src Le tampon source.
[in] dst Le tampon destination.
[in] size La taille des données à copier.
[in] offset Le décalage dans le tampon source.
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyBuffer() [4/8]
void ashes::CommandBuffer::copyBuffer (VertexBufferBase const & src, BufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copie les données d'un tampon vers un autre tampon.
Parameters
[in] src Le tampon source.
[in] dst Le tampon destination.
[in] size La taille des données à copier.
[in] offset Le décalage dans le tampon source.
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyBuffer() [5/8]
void ashes::CommandBuffer::copyBuffer (VertexBufferBase const & src, VertexBufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copie les données d'un tampon vers un autre tampon.
Parameters
[in] src Le tampon source.
[in] dst Le tampon destination.
[in] size La taille des données à copier.
[in] offset Le décalage dans le tampon source.
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyBuffer() [6/8]
void ashes::CommandBuffer::copyBuffer (BufferBase const & src, UniformBufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copie les données d'un tampon vers un autre tampon.
Parameters
[in] src Le tampon source.
[in] dst Le tampon destination.
[in] size La taille des données à copier.
[in] offset Le décalage dans le tampon source.
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyBuffer() [7/8]
void ashes::CommandBuffer::copyBuffer (UniformBufferBase const & src, BufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copie les données d'un tampon vers un autre tampon.
Parameters
[in] src Le tampon source.
[in] dst Le tampon destination.
[in] size La taille des données à copier.
[in] offset Le décalage dans le tampon source.
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyBuffer() [8/8]
void ashes::CommandBuffer::copyBuffer (UniformBufferBase const & src, UniformBufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copie les données d'un tampon vers un autre tampon.
Parameters
[in] src Le tampon source.
[in] dst Le tampon destination.
[in] size La taille des données à copier.
[in] offset Le décalage dans le tampon source.
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyImage() [1/2]
void ashes::CommandBuffer::copyImage (VkImageCopy const & copyInfo, Image const & src, VkImageLayout srcLayout, Image const & dst, VkImageLayout dstLayout) const
Copies data from an image to another one.
Parameters
[in] copyInfo The copy informations.
[in] src The source image.
[in] srcLayout The image layout wanted for the source image.
[in] dst The destination image.
[in] dstLayout The image layout wanted for the destination image.
copyImage() [2/2]
void ashes::CommandBuffer::copyImage (ImageView const & src, ImageView const & dst) const
Copies data from an image to another one.
Parameters
[in] src The source image.
[in] dst The destination image.
copyToBuffer() [1/2]
void ashes::CommandBuffer::copyToBuffer (VkBufferImageCopyArray const & copyInfo, Image const & src, BufferBase const & dst) const
Copies data from a buffer to an image.
Parameters
[in] copyInfo The copy informations.
[in] src The source buffer.
[in] dst The destination image.
copyToBuffer() [2/2]
void ashes::CommandBuffer::copyToBuffer (VkBufferImageCopy const & copyInfo, Image const & src, BufferBase const & dst) const
Copies data from a buffer to an image.
Parameters
[in] copyInfo The copy informations.
[in] src The source buffer.
[in] dst The destination image.
copyToImage() [1/2]
void ashes::CommandBuffer::copyToImage (VkBufferImageCopyArray const & copyInfo, BufferBase const & src, Image const & dst) const
Copies data from a buffer to an image.
Parameters
[in] copyInfo The copy informations.
[in] src The source buffer.
[in] dst The destination image.
copyToImage() [2/2]
void ashes::CommandBuffer::copyToImage (VkBufferImageCopy const & copyInfo, BufferBase const & src, Image const & dst) const
Copies data from a buffer to an image.
Parameters
[in] copyInfo The copy informations.
[in] src The source buffer.
[in] dst The destination image.
dispatch()
void ashes::CommandBuffer::dispatch (uint32_t groupCountX, uint32_t groupCountY, uint32_t groupCountZ) const
Dispatch compute work items.
Parameters
[in] groupCountX,groupCountY,groupCountZ The number of local workgroups to dispatch to the X, Y, and Z dimensions.
dispatchIndirect()
void ashes::CommandBuffer::dispatchIndirect (BufferBase const & buffer, uint32_t offset) const
Dispatch compute work items using indirect parameters.
Parameters
[in] buffer The buffer containing dispatch parameters.
[in] offset The byte offset into buffer where parameters begin.
draw()
void ashes::CommandBuffer::draw (uint32_t vtxCount, uint32_t instCount = 1u, uint32_t firstVertex = 0u, uint32_t firstInstance = 0u) const
Draws some vertices.
Parameters
[in] vtxCount The vertex count.
[in] instCount The instances count.
[in] firstVertex The first vertex index.
[in] firstInstance The first instance index.
drawIndexed()
void ashes::CommandBuffer::drawIndexed (uint32_t indexCount, uint32_t instCount = 1u, uint32_t firstIndex = 0u, uint32_t vertexOffset = 0u, uint32_t firstInstance = 0u) const
Draws some indexed vertices.
Parameters
[in] indexCount The index count.
[in] instCount The instances count.
[in] firstIndex The first index index.
[in] vertexOffset The offset added to the vertex index, before indexing the vertex buffer.
[in] firstInstance The first instance index.
drawIndexedIndirect()
void ashes::CommandBuffer::drawIndexedIndirect (BufferBase const & buffer, uint32_t offset, uint32_t drawCount, uint32_t stride) const
Perform an indexed indirect draw.
Parameters
[in] buffer The buffer containing draw parameters.
[in] offset The byte offset into buffer where parameters begin.
[in] drawCount The number of draws to execute, and can be zero.
[in] stride The byte stride between successive sets of draw parameters.
drawIndirect()
void ashes::CommandBuffer::drawIndirect (BufferBase const & buffer, uint32_t offset, uint32_t drawCount, uint32_t stride) const
Perform an indirect draw.
Parameters
[in] buffer The buffer containing draw parameters.
[in] offset The byte offset into buffer where parameters begin.
[in] drawCount The number of draws to execute, and can be zero.
[in] stride The byte stride between successive sets of draw parameters.
end()
void ashes::CommandBuffer::end () const
Ends the command buffer recording.
Returns
false on any error.
endQuery()
void ashes::CommandBuffer::endQuery (QueryPool const & pool, uint32_t query) const
Ends a query.
Parameters
[in] pool The query pool.
[in] query The query index.
endRenderPass()
void ashes::CommandBuffer::endRenderPass () const
End the current render pass.
executeCommands()
void ashes::CommandBuffer::executeCommands (CommandBufferCRefArray const & commands) const
Execute a secondary command buffer.
Parameters
[in] commands The secondary command buffers, which are recorded to execute in the order they are listed in the array.
memoryBarrier() [1/2]
void ashes::CommandBuffer::memoryBarrier (VkPipelineStageFlags after, VkPipelineStageFlags before, VkBufferMemoryBarrier const & transitionBarrier) const
Defines a memory dependency between commands that were submitted before it, and those submitted after it.
Parameters
[in] after Specifies the pipeline stages that must be ended before the barrier.
[in] before Specifies the pipeline stages that can be started after the barrier.
[in] transitionBarrier Describes the transition.
memoryBarrier() [2/2]
void ashes::CommandBuffer::memoryBarrier (VkPipelineStageFlags after, VkPipelineStageFlags before, VkImageMemoryBarrier const & transitionBarrier) const
Defines a memory dependency between commands that were submitted before it, and those submitted after it.
Parameters
[in] after Specifies the pipeline stages that must be ended before the barrier.
[in] before Specifies the pipeline stages that can be started after the barrier.
[in] transitionBarrier Describes the transition.
nextSubpass()
void ashes::CommandBuffer::nextSubpass (VkSubpassContents contents) const
Transition to the next subpass of a render pass.
Parameters
[in] contents Specifies how the commands in the next subpass will be provided.
operator VkCommandBuffer const &()
ashes::CommandBuffer::operator VkCommandBuffer const & () const inline
VkCommandBuffer implicit cast operator.
operator=()
CommandBuffer& ashes::CommandBuffer::operator= (CommandBuffer const &) protected delete
pipelineBarrier()
void ashes::CommandBuffer::pipelineBarrier (VkPipelineStageFlags after, VkPipelineStageFlags before, VkDependencyFlags dependencyFlags, VkMemoryBarrierArray const & memoryBarriers, VkBufferMemoryBarrierArray const & bufferMemoryBarriers, VkImageMemoryBarrierArray const & imaegMemoryBarriers) const
Defines a memory dependency between commands that were submitted before it, and those submitted after it.
Parameters
[in] after Specifies the pipeline stages that must be ended before the barrier.
[in] before Specifies the pipeline stages that can be started after the barrier.
[in] transitionBarrier Describes the transition.
pushConstants() [1/3]
void ashes::CommandBuffer::pushConstants (PipelineLayout const & layout, VkShaderStageFlags stageFlags, uint32_t offset, uint32_t size, void const * data) const
Updates the values of push constants.
Parameters
[in] layout The pipeline layout used to program the push constants updates.
[in] stageFlags The impacted shader stages.
[in] offset The range offset (in bytes).
[in] size The range size (in bytes).
[in] data The push constants data.
Referenced by pushConstants().
pushConstants() [2/3]
void ashes::CommandBuffer::pushConstants (PipelineLayout const & layout, PushConstantsBufferBase const & pcb) const
Updates the values of push constants.
Parameters
[in] layout The pipeline layout used to program the push constants updates.
[in] pcb The push constants buffer.
pushConstants() [3/3]
template<typename T > void ashes::CommandBuffer::pushConstants (PipelineLayout const & layout, PushConstantsBuffer< T > const & pcb) const inline
Updates the values of push constants.
Parameters
[in] layout The pipeline layout used to program the push constants updates.
[in] pcb The push constants buffer.
References ashes::PushConstantsBuffer< T >::getBuffer(), and pushConstants().
reset()
void ashes::CommandBuffer::reset (VkCommandBufferResetFlags flags = 0u) const
Reset a command buffer to the initial state.
Parameters
[in] flags The flags controlling the reset operation.
Returns
false on any error.
resetEvent()
void ashes::CommandBuffer::resetEvent (Event const & event, VkPipelineStageFlags stageMask) const
Sets an event to signaled state.
Parameters
[in] event The event to be signaled.
[in] stageMask The source stage mask used to determine when the event is signaled.
resetQueryPool()
void ashes::CommandBuffer::resetQueryPool (QueryPool const & pool, uint32_t firstQuery, uint32_t queryCount) const
Resets a range of queries in a query pool.
Parameters
[in] pool The query pool.
[in] firstQuery The first query index.
[in] queryCount The number of queries (starting at firstQuery).
setDepthBias()
void ashes::CommandBuffer::setDepthBias (float constantFactor, float clamp, float slopeFactor) const
Specifies the lines width, if this is a dynamic state in the pipeline.
Parameters
[in] constantFactor The scalar factor controlling the constant depth value added to each fragment.
[in] clamp The maximum (or minimum) depth bias of a fragment.
[in] slopeFactor The scalar factor applied to a fragment’s slope in depth bias calculations.
setEvent()
void ashes::CommandBuffer::setEvent (Event const & event, VkPipelineStageFlags stageMask) const
Sets an event to signaled state.
Parameters
[in] event The event to be signaled.
[in] stageMask The source stage mask used to determine when the event is signaled.
setLineWidth()
void ashes::CommandBuffer::setLineWidth (float width) const
Specifies the lines width, if this is a dynamic state in the pipeline.
Parameters
[in] width The wanted width.
setScissor() [1/2]
void ashes::CommandBuffer::setScissor (uint32_t firstScissor, VkScissorArray const & scissors) const
Defines the currently bound pipeline scissor.
Remarks
This action is possible only if the scissor is dynamic, in the pipeline.
Parameters
[in] scissor The scissor.
Referenced by setScissor().
setScissor() [2/2]
void ashes::CommandBuffer::setScissor (VkRect2D const & scissor) const inline
Defines the currently bound pipeline scissor.
Remarks
This action is possible only if the scissor is dynamic, in the pipeline.
Parameters
[in] scissor The scissor.
References setScissor().
setViewport() [1/2]
void ashes::CommandBuffer::setViewport (uint32_t firstViewport, VkViewportArray const & viewports) const
Defines the currently bound pipeline viewport.
Remarks
This action is possible only if the viewport is dynamic, in the pipeline.
Parameters
[in] viewport The viewport.
Referenced by setViewport().
setViewport() [2/2]
void ashes::CommandBuffer::setViewport (VkViewport const & viewport) const inline
Defines the currently bound pipeline viewport.
Remarks
This action is possible only if the viewport is dynamic, in the pipeline.
Parameters
[in] viewport The viewport.
References setViewport().
waitEvents()
void ashes::CommandBuffer::waitEvents (EventCRefArray const & events, VkPipelineStageFlags srcStageMask, VkPipelineStageFlags dstStageMask, VkBufferMemoryBarrierArray const & bufferMemoryBarriers, VkImageMemoryBarrierArray const & imageMemoryBarriers) const
Wait for one or more events to be signaled on a device.
Parameters
[in] events The events to wait on.
[in] srcStageMask The source stage mask.
[in] dstStageMask destination stage mask.
[in] bufferMemoryBarriers An array of buffer memory barriers.
[in] imageMemoryBarriers An array of image memory barriers.
writeTimestamp()
void ashes::CommandBuffer::writeTimestamp (VkPipelineStageFlagBits pipelineStage, QueryPool const & pool, uint32_t query) const
Writes a timestamp to given query result.
Parameters
[in] pipelineStage Specifies the stage of the pipeline.
[in] pool The query pool.
[in] query The query index.
The documentation for this class was generated from the following file:
Z:/Projets/C++/Ashes/include/ashespp/Command/CommandBuffer.hpp