RendererLib: renderer::DescriptorSet Class Reference
renderer::DescriptorSet Class Reference abstract
A descriptor set.
Public Member Functions
virtual ~DescriptorSet ()
Destructor.
void setBindings (WriteDescriptorSetArray bindings)
Sets the descriptor set's attaches.
void createBinding (DescriptorSetLayoutBinding const &layoutBinding, TextureView const &view, Sampler const &sampler, ImageLayout layout=ImageLayout::eShaderReadOnlyOptimal, uint32_t index=0u)
Creates a combined image and sampler binding.
void createBinding (DescriptorSetLayoutBinding const &layoutBinding, Sampler const &sampler, uint32_t index=0u)
Creates a sampler binding.
void createBinding (DescriptorSetLayoutBinding const &layoutBinding, TextureView const &view, ImageLayout layout, uint32_t index=0u)
Creates a sampled image binding.
void createBinding (DescriptorSetLayoutBinding const &layoutBinding, TextureView const &view, uint32_t index=0u)
Creates a storage image binding.
void createBinding (DescriptorSetLayoutBinding const &layoutBinding, UniformBufferBase const &uniformBuffer, uint32_t offset, uint32_t range, uint32_t index=0u)
Creates a uniform buffer binding.
void createBinding (DescriptorSetLayoutBinding const &layoutBinding, BufferBase const &buffer, uint32_t offset, uint32_t range, uint32_t index=0u)
Creates a storage or uniform buffer binding.
void createBinding (DescriptorSetLayoutBinding const &layoutBinding, BufferBase const &buffer, BufferView const &view, uint32_t index=0u)
Creates a texel buffer binding.
void createDynamicBinding (DescriptorSetLayoutBinding const &layoutBinding, UniformBufferBase const &uniformBuffer, uint32_t offset, uint32_t range, uint32_t index=0u)
Creates a dynamic uniform buffer binding.
void createDynamicBinding (DescriptorSetLayoutBinding const &layoutBinding, BufferBase const &buffer, uint32_t offset, uint32_t range, uint32_t index=0u)
Creates a dynamic storage or uniform buffer binding.
template<typename T >
void createBinding (DescriptorSetLayoutBinding const &layoutBinding, UniformBuffer< T > const &uniformBuffer, uint32_t offset=0u, uint32_t range=1u, uint32_t index=0u)
Creates a uniform buffer binding.
template<typename T >
void createBinding (DescriptorSetLayoutBinding const &layoutBinding, Buffer< T > const &storageBuffer, uint32_t offset, uint32_t range, uint32_t index=0u)
Creates a storage buffer binding.
template<typename T >
void createBinding (DescriptorSetLayoutBinding const &layoutBinding, UniformBuffer< T > const &buffer, BufferView const &view, uint32_t index=0u)
Creates a texel buffer binding.
template<typename T >
void createBinding (DescriptorSetLayoutBinding const &layoutBinding, Buffer< T > const &buffer, BufferView const &view, uint32_t index=0u)
Creates a texel buffer binding.
template<typename T >
void createDynamicBinding (DescriptorSetLayoutBinding const &layoutBinding, UniformBuffer< T > const &uniformBuffer, uint32_t offset=0u, uint32_t range=1u, uint32_t index=0u)
Creates a dynamic uniform buffer binding.
template<typename T >
void createDynamicBinding (DescriptorSetLayoutBinding const &layoutBinding, Buffer< T > const &storageBuffer, uint32_t offset, uint32_t range, uint32_t index=0u)
Creates a dynamic storage buffer binding.
virtual void update () const =0
Updates all the bindings in the descriptor set.
uint32_t getBindingPoint () const
WriteDescriptorSet const & getBinding (uint32_t index) const
WriteDescriptorSet & getBinding (uint32_t index)
Protected Member Functions
DescriptorSet (DescriptorPool const &pool, uint32_t bindingPoint)
Constructor.
Protected Attributes
WriteDescriptorSetArray m_writes
Detailed Description
A descriptor set.
Constructor & Destructor Documentation
DescriptorSet()
renderer::DescriptorSet::DescriptorSet (DescriptorPool const & pool, uint32_t bindingPoint) protected
Constructor.
Parameters
[in] pool The parent pool.
[in] bindingPoint The binding point for the set.
~DescriptorSet()
virtual renderer::DescriptorSet::~DescriptorSet () virtual
Destructor.
Member Function Documentation
createBinding() [1/11]
void renderer::DescriptorSet::createBinding (DescriptorSetLayoutBinding const & layoutBinding, TextureView const & view, Sampler const & sampler, ImageLayout layout = ImageLayout::eShaderReadOnlyOptimal, uint32_t index = 0u)
Creates a combined image and sampler binding.
Parameters
[in] layoutBinding The layout binding.
[in] view The image.
[in] sampler The sampler.
[in] layout The wanted image layout.
[in] index The array index.
Referenced by createBinding().
createBinding() [2/11]
void renderer::DescriptorSet::createBinding (DescriptorSetLayoutBinding const & layoutBinding, Sampler const & sampler, uint32_t index = 0u)
Creates a sampler binding.
Parameters
[in] layoutBinding The layout binding.
[in] sampler The sampler.
[in] index The array index.
createBinding() [3/11]
void renderer::DescriptorSet::createBinding (DescriptorSetLayoutBinding const & layoutBinding, TextureView const & view, ImageLayout layout, uint32_t index = 0u)
Creates a sampled image binding.
Parameters
[in] layoutBinding The layout binding.
[in] view The image.
[in] layout The image layout.
[in] index The array index.
createBinding() [4/11]
void renderer::DescriptorSet::createBinding (DescriptorSetLayoutBinding const & layoutBinding, TextureView const & view, uint32_t index = 0u)
Creates a storage image binding.
Parameters
[in] layoutBinding The layout binding.
[in] view The image.
[in] index The array index.
createBinding() [5/11]
void renderer::DescriptorSet::createBinding (DescriptorSetLayoutBinding const & layoutBinding, UniformBufferBase const & uniformBuffer, uint32_t offset, uint32_t range, uint32_t index = 0u)
Creates a uniform buffer binding.
Parameters
[in] layoutBinding The layout binding.
[in] uniformBuffer The buffer.
[in] offset The attach's offset in the buffer.
[in] range The amount of data that can be read from the buffer.
[in] index The array index.
createBinding() [6/11]
void renderer::DescriptorSet::createBinding (DescriptorSetLayoutBinding const & layoutBinding, BufferBase const & buffer, uint32_t offset, uint32_t range, uint32_t index = 0u)
Creates a storage or uniform buffer binding.
Parameters
[in] layoutBinding The layout binding.
[in] buffer The buffer.
[in] offset The attach's offset in the buffer.
[in] range The amount of data that can be read from the buffer.
[in] index The array index.
createBinding() [7/11]
void renderer::DescriptorSet::createBinding (DescriptorSetLayoutBinding const & layoutBinding, BufferBase const & buffer, BufferView const & view, uint32_t index = 0u)
Creates a texel buffer binding.
Parameters
[in] layoutBinding The layout binding.
[in] buffer The buffer.
[in] view The view to the buffer.
[in] index The array index.
createBinding() [8/11]
template<typename T > void renderer::DescriptorSet::createBinding (DescriptorSetLayoutBinding const & layoutBinding, UniformBuffer< T > const & uniformBuffer, uint32_t offset = 0u, uint32_t range = 1u, uint32_t index = 0u) inline
Creates a uniform buffer binding.
Parameters
[in] layoutBinding The layout binding.
[in] uniformBuffer The buffer.
[in] offset The attach's offset in the buffer.
[in] range The amount of data that can be read from the buffer.
[in] index The array index.
References createBinding(), renderer::UniformBuffer< T >::getAlignedSize(), and renderer::UniformBuffer< T >::getUbo().
createBinding() [9/11]
template<typename T > void renderer::DescriptorSet::createBinding (DescriptorSetLayoutBinding const & layoutBinding, Buffer< T > const & storageBuffer, uint32_t offset, uint32_t range, uint32_t index = 0u) inline
Creates a storage buffer binding.
Parameters
[in] layoutBinding The layout binding.
[in] storageBuffer The buffer.
[in] offset The attach's offset in the buffer.
[in] range The amount of data that can be read from the buffer.
[in] index The array index.
References createBinding(), and renderer::Buffer< T >::getBuffer().
createBinding() [10/11]
template<typename T > void renderer::DescriptorSet::createBinding (DescriptorSetLayoutBinding const & layoutBinding, UniformBuffer< T > const & buffer, BufferView const & view, uint32_t index = 0u) inline
Creates a texel buffer binding.
Parameters
[in] layoutBinding The layout binding.
[in] buffer The buffer.
[in] view The view to the buffer.
[in] index The array index.
References createBinding(), and renderer::UniformBuffer< T >::getUbo().
createBinding() [11/11]
template<typename T > void renderer::DescriptorSet::createBinding (DescriptorSetLayoutBinding const & layoutBinding, Buffer< T > const & buffer, BufferView const & view, uint32_t index = 0u) inline
Creates a texel buffer binding.
Parameters
[in] layoutBinding The layout binding.
[in] buffer The buffer.
[in] view The view to the buffer.
[in] index The array index.
References createBinding(), and renderer::Buffer< T >::getBuffer().
createDynamicBinding() [1/4]
void renderer::DescriptorSet::createDynamicBinding (DescriptorSetLayoutBinding const & layoutBinding, UniformBufferBase const & uniformBuffer, uint32_t offset, uint32_t range, uint32_t index = 0u)
Creates a dynamic uniform buffer binding.
Remarks
Allow specification of an additional offset at descriptor's binding time.
Parameters
[in] layoutBinding The layout binding.
[in] uniformBuffer The buffer.
[in] offset The attach's offset in the buffer.
[in] range The amount of data that can be read from the buffer.
[in] index The array index.
Referenced by createDynamicBinding().
createDynamicBinding() [2/4]
void renderer::DescriptorSet::createDynamicBinding (DescriptorSetLayoutBinding const & layoutBinding, BufferBase const & buffer, uint32_t offset, uint32_t range, uint32_t index = 0u)
Creates a dynamic storage or uniform buffer binding.
Remarks
Allow specification of an additional offset at descriptor's binding time.
Parameters
[in] layoutBinding The layout binding.
[in] buffer The buffer.
[in] offset The attach's offset in the buffer.
[in] range The amount of data that can be read from the buffer.
[in] index The array index.
createDynamicBinding() [3/4]
template<typename T > void renderer::DescriptorSet::createDynamicBinding (DescriptorSetLayoutBinding const & layoutBinding, UniformBuffer< T > const & uniformBuffer, uint32_t offset = 0u, uint32_t range = 1u, uint32_t index = 0u) inline
Creates a dynamic uniform buffer binding.
Remarks
Allow specification of an additional offset at descriptor's binding time.
Parameters
[in] layoutBinding The layout binding.
[in] uniformBuffer The buffer.
[in] offset The attach's offset in the buffer.
[in] range The amount of data that can be read from the buffer.
[in] index The array index.
References createDynamicBinding(), renderer::UniformBuffer< T >::getAlignedSize(), and renderer::UniformBuffer< T >::getUbo().
createDynamicBinding() [4/4]
template<typename T > void renderer::DescriptorSet::createDynamicBinding (DescriptorSetLayoutBinding const & layoutBinding, Buffer< T > const & storageBuffer, uint32_t offset, uint32_t range, uint32_t index = 0u) inline
Creates a dynamic storage buffer binding.
Remarks
Allow specification of an additional offset at descriptor's binding time.
Parameters
[in] layoutBinding The layout binding.
[in] storageBuffer The buffer.
[in] offset The attach's offset in the buffer.
[in] range The amount of data that can be read from the buffer.
[in] index The array index.
References createDynamicBinding(), renderer::Buffer< T >::getBuffer(), and update().
getBinding() [1/2]
WriteDescriptorSet const& renderer::DescriptorSet::getBinding (uint32_t index) const inline
Returns
The descriptor at given index.
References m_writes.
getBinding() [2/2]
WriteDescriptorSet& renderer::DescriptorSet::getBinding (uint32_t index) inline
Returns
The descriptor at given index.
References m_writes.
getBindingPoint()
uint32_t renderer::DescriptorSet::getBindingPoint () const inline
Returns
The binding point for the set.
setBindings()
void renderer::DescriptorSet::setBindings (WriteDescriptorSetArray bindings)
Sets the descriptor set's attaches.
Parameters
[in] bindings The bindings.
update()
virtual void renderer::DescriptorSet::update () const pure virtual
Updates all the bindings in the descriptor set.
Referenced by createDynamicBinding().
Member Data Documentation
m_writes
WriteDescriptorSetArray renderer::DescriptorSet::m_writes protected
Referenced by getBinding().
The documentation for this class was generated from the following file:
Z:/Projets/C++/RenderLib/source/Renderer/Renderer/Src/Descriptor/DescriptorSet.hpp