Renderer: renderer::CommandBuffer Class Reference
renderer::CommandBuffer Class Reference abstract
A command buffer.
Public Member Functions
virtual ~CommandBuffer ()=default
Destructor.
virtual bool begin (CommandBufferUsageFlags flags=0u) const =0
Starts recording the command buffer.
virtual bool begin (CommandBufferUsageFlags flags, RenderPass const &renderPass, uint32_t subpass, FrameBuffer const &frameBuffer, bool occlusionQueryEnable=false, QueryControlFlags queryFlags=0u, QueryPipelineStatisticFlags pipelineStatistics=0u) const =0
Starts recording the command buffer as a secondary command buffer.
virtual bool end () const =0
Ends the command buffer recording.
virtual bool reset (CommandBufferResetFlags flags=0u) const =0
Reset a command buffer to the initial state.
virtual void beginRenderPass (RenderPass const &renderPass, FrameBuffer const &frameBuffer, ClearValueArray const &clearValues, SubpassContents contents) const =0
Begins a new render pass.
virtual void nextSubpass (SubpassContents contents) const =0
Transition to the next subpass of a render pass.
virtual void endRenderPass () const =0
End the current render pass.
virtual void executeCommands (CommandBufferCRefArray const &commands) const =0
Execute a secondary command buffer.
virtual void clear (TextureView const &image, RgbaColour const &colour) const =0
Clear a color image.
virtual void clear (renderer::TextureView const &image, renderer::DepthStencilClearValue const &value) const =0
Clear a depth and/or stencil image.
virtual void memoryBarrier (PipelineStageFlags after, PipelineStageFlags before, BufferMemoryBarrier const &transitionBarrier) const =0
Defines a memory dependency between commands that were submitted before it, and those submitted after it.
virtual void memoryBarrier (PipelineStageFlags after, PipelineStageFlags before, ImageMemoryBarrier const &transitionBarrier) const =0
Defines a memory dependency between commands that were submitted before it, and those submitted after it.
virtual void bindPipeline (Pipeline const &pipeline, PipelineBindPoint bindingPoint=PipelineBindPoint::eGraphics) const =0
Binds a pipeline to the command buffer.
virtual void bindPipeline (ComputePipeline const &pipeline, PipelineBindPoint bindingPoint=PipelineBindPoint::eCompute) const =0
Binds a compute pipeline to the command buffer.
virtual void bindGeometryBuffers (GeometryBuffers const &geometryBuffers) const =0
Enables geometry buffers (VBO, EBO, ...).
virtual void bindDescriptorSets (DescriptorSetCRefArray const &descriptorSet, PipelineLayout const &layout, PipelineBindPoint bindingPoint=PipelineBindPoint::eGraphics) const =0
Binds descriptor sets to the command buffer.
virtual void setViewport (Viewport const &viewport) const =0
Defines the currently bound pipeline viewport.
virtual void setScissor (Scissor const &scissor) const =0
Defines the currently bound pipeline scissor.
virtual void draw (uint32_t vtxCount, uint32_t instCount=1u, uint32_t firstVertex=0u, uint32_t firstInstance=0u) const =0
Draws some vertices.
virtual void drawIndexed (uint32_t indexCount, uint32_t instCount=1u, uint32_t firstIndex=0u, uint32_t vertexOffset=0u, uint32_t firstInstance=0u) const =0
Draws some indexed vertices.
virtual void copyToImage (BufferImageCopy const &copyInfo, BufferBase const &src, TextureView const &dst) const =0
Copies data from a buffer to an image.
virtual void copyToBuffer (BufferImageCopy const &copyInfo, TextureView const &src, BufferBase const &dst) const =0
Copies data from a buffer to an image.
virtual void copyBuffer (BufferCopy const &copyInfo, BufferBase const &src, BufferBase const &dst) const =0
Copies data from a buffer to another one.
virtual void copyImage (ImageCopy const &copyInfo, TextureView const &src, TextureView const &dst) const =0
Copies data from an image to another one.
virtual void blitImage (ImageBlit const &blit, FrameBufferAttachment const &src, FrameBufferAttachment const &dst, Filter filter) const =0
Blits an image to another one.
virtual void resetQueryPool (QueryPool const &pool, uint32_t firstQuery, uint32_t queryCount) const =0
Resets a range of queries in a query pool.
virtual void beginQuery (QueryPool const &pool, uint32_t query, QueryControlFlags flags) const =0
Begins a query.
virtual void endQuery (QueryPool const &pool, uint32_t query) const =0
Ends a query.
virtual void writeTimestamp (PipelineStageFlag pipelineStage, QueryPool const &pool, uint32_t query) const =0
Writes a timestamp to given query result.
virtual void pushConstants (PipelineLayout const &layout, PushConstantsBufferBase const &pcb) const =0
Updates the values of push constants.
virtual void dispatch (uint32_t groupCountX, uint32_t groupCountY, uint32_t groupCountZ) const =0
Dispatch compute work items.
void copyBuffer (BufferBase const &src, BufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copies data from a buffer to another one.
void bindDescriptorSet (DescriptorSet const &descriptorSet, PipelineLayout const &layout, PipelineBindPoint bindingPoint=PipelineBindPoint::eGraphics) const
Binds a descriptor set to the command buffer.
void copyBuffer (BufferBase const &src, VertexBufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copie les données d'un tampon vers un autre tampon.
void copyBuffer (VertexBufferBase const &src, BufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copie les données d'un tampon vers un autre tampon.
void copyBuffer (VertexBufferBase const &src, VertexBufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copie les données d'un tampon vers un autre tampon.
void copyBuffer (BufferBase const &src, UniformBufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copie les données d'un tampon vers un autre tampon.
void copyBuffer (UniformBufferBase const &src, BufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copie les données d'un tampon vers un autre tampon.
void copyBuffer (UniformBufferBase const &src, UniformBufferBase const &dst, uint32_t size, uint32_t offset=0) const
Copie les données d'un tampon vers un autre tampon.
void copyImage (TextureView const &src, TextureView const &dst) const
Copies data from an image to another one.
template<typename T >
void pushConstants (PipelineLayout const &layout, PushConstantsBuffer< T > const &pcb) const
Updates the values of push constants.
Protected Member Functions
CommandBuffer (CommandBuffer const &)=delete
CommandBuffer & operator= (CommandBuffer const &)=delete
CommandBuffer ()=default
CommandBuffer (Device const &device, CommandPool const &pool, bool primary=true)
Constructor.
Detailed Description
A command buffer.
Constructor & Destructor Documentation
CommandBuffer() [1/3]
renderer::CommandBuffer::CommandBuffer (CommandBuffer const &) protected delete
CommandBuffer() [2/3]
renderer::CommandBuffer::CommandBuffer () protected default
CommandBuffer() [3/3]
renderer::CommandBuffer::CommandBuffer (Device const & device, CommandPool const & pool, bool primary = true) protected
Constructor.
Parameters
[in] device The logical device.
[in] pool The parent command buffer pool.
[in] primary Tells if the command buffer is primary (true) or not (false).
~CommandBuffer()
virtual renderer::CommandBuffer::~CommandBuffer () virtual default
Destructor.
Member Function Documentation
begin() [1/2]
virtual bool renderer::CommandBuffer::begin (CommandBufferUsageFlags flags = 0u) const pure virtual
Starts recording the command buffer.
Parameters
[in] flags The usage flags for the command buffer.
Returns
false on any problem.
begin() [2/2]
virtual bool renderer::CommandBuffer::begin (CommandBufferUsageFlags flags, RenderPass const & renderPass, uint32_t subpass, FrameBuffer const & frameBuffer, bool occlusionQueryEnable = false, QueryControlFlags queryFlags = 0u, QueryPipelineStatisticFlags pipelineStatistics = 0u) const pure virtual
Starts recording the command buffer as a secondary command buffer.
Parameters
[in] flags The usage flags for the command buffer.
[in] renderPass The render pass with which the buffer is compatible, and int which it can execute.
[in] subpass The index of the subpass into which this buffer will be executed.
[in] frameBuffer The frame buffer into which the command buffer will render.
[in] occlusionQueryEnable Tells if the command buffer can be executed while an occlusion query is active on main command buffer.
[in] queryFlags The occlusion query flags that can be used by an active occlusion query on the main command buffer, when this buffer is executed.
[in] pipelineStatistics Tells which pipeline statistics can be counted by an active query on the main command buffer, when this buffer is executed.
Returns
false on any error.
beginQuery()
virtual void renderer::CommandBuffer::beginQuery (QueryPool const & pool, uint32_t query, QueryControlFlags flags) const pure virtual
Begins a query.
Parameters
[in] pool The query pool.
[in] query The query index.
[in] flags The constraints on the types of queries that can be performed.
beginRenderPass()
virtual void renderer::CommandBuffer::beginRenderPass (RenderPass const & renderPass, FrameBuffer const & frameBuffer, ClearValueArray const & clearValues, SubpassContents contents) const pure virtual
Begins a new render pass.
Parameters
[in] renderPass The render pass to begin.
[in] frameBuffer The framebuffer containing the attachments that are used with the render pass.
[in] clearValues The clear values for each attachment that needs to be cleared.
[in] contents Specifies how the commands in the first subpass will be provided.
bindDescriptorSet()
void renderer::CommandBuffer::bindDescriptorSet (DescriptorSet const & descriptorSet, PipelineLayout const & layout, PipelineBindPoint bindingPoint = PipelineBindPoint::eGraphics) const inline
Binds a descriptor set to the command buffer.
Parameters
[in] descriptorSet The descriptor set.
[in] layout The pipeline layout used to program the binding.
[in] bindingPoint Indicates whether the descriptor wil be used by graphics or compute pipeline.
References bindDescriptorSets(), copyBuffer(), and copyImage().
bindDescriptorSets()
virtual void renderer::CommandBuffer::bindDescriptorSets (DescriptorSetCRefArray const & descriptorSet, PipelineLayout const & layout, PipelineBindPoint bindingPoint = PipelineBindPoint::eGraphics) const pure virtual
Binds descriptor sets to the command buffer.
Parameters
[in] descriptorSet The descriptor sets.
[in] layout The pipeline layout used to program the binding.
[in] bindingPoint Indicates whether the descriptor wil be used by graphics or compute pipeline.
Referenced by bindDescriptorSet().
bindGeometryBuffers()
virtual void renderer::CommandBuffer::bindGeometryBuffers (GeometryBuffers const & geometryBuffers) const pure virtual
Enables geometry buffers (VBO, EBO, ...).
Parameters
[in] geometryBuffers Les tampons de géométrie.
bindPipeline() [1/2]
virtual void renderer::CommandBuffer::bindPipeline (Pipeline const & pipeline, PipelineBindPoint bindingPoint = PipelineBindPoint::eGraphics) const pure virtual
Binds a pipeline to the command buffer.
Parameters
[in] pipeline The pipeline to be bound.
[in] bindingPoint Specifies whether to bind to the compute or graphics bind point.
bindPipeline() [2/2]
virtual void renderer::CommandBuffer::bindPipeline (ComputePipeline const & pipeline, PipelineBindPoint bindingPoint = PipelineBindPoint::eCompute) const pure virtual
Binds a compute pipeline to the command buffer.
Parameters
[in] pipeline The pipeline to be bound.
[in] bindingPoint Specifies whether to bind to the compute or graphics bind point.
blitImage()
virtual void renderer::CommandBuffer::blitImage (ImageBlit const & blit, FrameBufferAttachment const & src, FrameBufferAttachment const & dst, Filter filter) const pure virtual
Blits an image to another one.
Parameters
[in] blit The blit configuration.
[in] src The source image.
[in] dst The destination image.
[in] filter The filter applied if the blit requires scaling.
clear() [1/2]
virtual void renderer::CommandBuffer::clear (TextureView const & image, RgbaColour const & colour) const pure virtual
Clear a color image.
Parameters
[in] image The image to clear.
[in] colour The clear colour.
clear() [2/2]
virtual void renderer::CommandBuffer::clear (renderer::TextureView const & image, renderer::DepthStencilClearValue const & value) const pure virtual
Clear a depth and/or stencil image.
Parameters
[in] image The image to clear.
[in] value The clear value.
copyBuffer() [1/8]
virtual void renderer::CommandBuffer::copyBuffer (BufferCopy const & copyInfo, BufferBase const & src, BufferBase const & dst) const pure virtual
Copies data from a buffer to another one.
Parameters
[in] copyInfo The copy informations.
[in] src The source buffer.
[in] dst The destination buffer.
Referenced by bindDescriptorSet().
copyBuffer() [2/8]
void renderer::CommandBuffer::copyBuffer (BufferBase const & src, BufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyBuffer() [3/8]
void renderer::CommandBuffer::copyBuffer (BufferBase const & src, VertexBufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copie les données d'un tampon vers un autre tampon.
Parameters
[in] src Le tampon source.
[in] dst Le tampon destination.
[in] size La taille des données à copier.
[in] offset Le décalage dans le tampon source.
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyBuffer() [4/8]
void renderer::CommandBuffer::copyBuffer (VertexBufferBase const & src, BufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copie les données d'un tampon vers un autre tampon.
Parameters
[in] src Le tampon source.
[in] dst Le tampon destination.
[in] size La taille des données à copier.
[in] offset Le décalage dans le tampon source.
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyBuffer() [5/8]
void renderer::CommandBuffer::copyBuffer (VertexBufferBase const & src, VertexBufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copie les données d'un tampon vers un autre tampon.
Parameters
[in] src Le tampon source.
[in] dst Le tampon destination.
[in] size La taille des données à copier.
[in] offset Le décalage dans le tampon source.
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyBuffer() [6/8]
void renderer::CommandBuffer::copyBuffer (BufferBase const & src, UniformBufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copie les données d'un tampon vers un autre tampon.
Parameters
[in] src Le tampon source.
[in] dst Le tampon destination.
[in] size La taille des données à copier.
[in] offset Le décalage dans le tampon source.
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyBuffer() [7/8]
void renderer::CommandBuffer::copyBuffer (UniformBufferBase const & src, BufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copie les données d'un tampon vers un autre tampon.
Parameters
[in] src Le tampon source.
[in] dst Le tampon destination.
[in] size La taille des données à copier.
[in] offset Le décalage dans le tampon source.
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyBuffer() [8/8]
void renderer::CommandBuffer::copyBuffer (UniformBufferBase const & src, UniformBufferBase const & dst, uint32_t size, uint32_t offset = 0) const
Copie les données d'un tampon vers un autre tampon.
Parameters
[in] src Le tampon source.
[in] dst Le tampon destination.
[in] size La taille des données à copier.
[in] offset Le décalage dans le tampon source.
Copies data from a buffer to another one.
Parameters
[in] src The source buffer.
[in] dst The destination buffer.
[in] size The byte size of the data to copy.
[in] offset The offset in the source buffer.
copyImage() [1/2]
virtual void renderer::CommandBuffer::copyImage (ImageCopy const & copyInfo, TextureView const & src, TextureView const & dst) const pure virtual
Copies data from an image to another one.
Parameters
[in] copyInfo The copy informations.
[in] src The source image.
[in] dst The destination image.
Referenced by bindDescriptorSet().
copyImage() [2/2]
void renderer::CommandBuffer::copyImage (TextureView const & src, TextureView const & dst) const
Copies data from an image to another one.
Parameters
[in] src The source image.
[in] dst The destination image.
copyToBuffer()
virtual void renderer::CommandBuffer::copyToBuffer (BufferImageCopy const & copyInfo, TextureView const & src, BufferBase const & dst) const pure virtual
Copies data from a buffer to an image.
Parameters
[in] copyInfo The copy informations.
[in] src The source buffer.
[in] dst The destination image.
copyToImage()
virtual void renderer::CommandBuffer::copyToImage (BufferImageCopy const & copyInfo, BufferBase const & src, TextureView const & dst) const pure virtual
Copies data from a buffer to an image.
Parameters
[in] copyInfo The copy informations.
[in] src The source buffer.
[in] dst The destination image.
dispatch()
virtual void renderer::CommandBuffer::dispatch (uint32_t groupCountX, uint32_t groupCountY, uint32_t groupCountZ) const pure virtual
Dispatch compute work items.
Parameters
[in] groupCountX,groupCountY,groupCountZ The number of local workgroups to dispatch to the X, Y, and Z dimensions.
draw()
virtual void renderer::CommandBuffer::draw (uint32_t vtxCount, uint32_t instCount = 1u, uint32_t firstVertex = 0u, uint32_t firstInstance = 0u) const pure virtual
Draws some vertices.
Parameters
[in] vtxCount The vertex count.
[in] instCount The instances count.
[in] firstVertex The first vertex index.
[in] firstInstance The first instance index.
drawIndexed()
virtual void renderer::CommandBuffer::drawIndexed (uint32_t indexCount, uint32_t instCount = 1u, uint32_t firstIndex = 0u, uint32_t vertexOffset = 0u, uint32_t firstInstance = 0u) const pure virtual
Draws some indexed vertices.
Parameters
[in] indexCount The index count.
[in] instCount The instances count.
[in] firstIndex The first index index.
[in] vertexOffset The offset added to the vertex index, before indexing the vertex buffer.
[in] firstInstance The first instance index.
end()
virtual bool renderer::CommandBuffer::end () const pure virtual
Ends the command buffer recording.
Returns
false on any error.
endQuery()
virtual void renderer::CommandBuffer::endQuery (QueryPool const & pool, uint32_t query) const pure virtual
Ends a query.
Parameters
[in] pool The query pool.
[in] query The query index.
endRenderPass()
virtual void renderer::CommandBuffer::endRenderPass () const pure virtual
End the current render pass.
executeCommands()
virtual void renderer::CommandBuffer::executeCommands (CommandBufferCRefArray const & commands) const pure virtual
Execute a secondary command buffer.
Parameters
[in] commands The secondary command buffers, which are recorded to execute in the order they are listed in the array.
memoryBarrier() [1/2]
virtual void renderer::CommandBuffer::memoryBarrier (PipelineStageFlags after, PipelineStageFlags before, BufferMemoryBarrier const & transitionBarrier) const pure virtual
Defines a memory dependency between commands that were submitted before it, and those submitted after it.
Parameters
[in] after Specifies the pipeline stages that must be ended before the barrier.
[in] before Specifies the pipeline stages that can be started after the barrier.
[in] transitionBarrier Describes the transition.
memoryBarrier() [2/2]
virtual void renderer::CommandBuffer::memoryBarrier (PipelineStageFlags after, PipelineStageFlags before, ImageMemoryBarrier const & transitionBarrier) const pure virtual
Defines a memory dependency between commands that were submitted before it, and those submitted after it.
Parameters
[in] after Specifies the pipeline stages that must be ended before the barrier.
[in] before Specifies the pipeline stages that can be started after the barrier.
[in] transitionBarrier Describes the transition.
nextSubpass()
virtual void renderer::CommandBuffer::nextSubpass (SubpassContents contents) const pure virtual
Transition to the next subpass of a render pass.
Parameters
[in] contents Specifies how the commands in the next subpass will be provided.
operator=()
CommandBuffer& renderer::CommandBuffer::operator= (CommandBuffer const &) protected delete
pushConstants() [1/2]
virtual void renderer::CommandBuffer::pushConstants (PipelineLayout const & layout, PushConstantsBufferBase const & pcb) const pure virtual
Updates the values of push constants.
Parameters
[in] layout The pipeline layout used to program the push constants updates.
[in] pcb The push constants buffer.
Referenced by pushConstants().
pushConstants() [2/2]
template<typename T > void renderer::CommandBuffer::pushConstants (PipelineLayout const & layout, PushConstantsBuffer< T > const & pcb) const inline
Updates the values of push constants.
Parameters
[in] layout The pipeline layout used to program the push constants updates.
[in] pcb The push constants buffer.
References renderer::PushConstantsBuffer< T >::getBuffer(), and pushConstants().
reset()
virtual bool renderer::CommandBuffer::reset (CommandBufferResetFlags flags = 0u) const pure virtual
Reset a command buffer to the initial state.
Parameters
[in] flags The flags controlling the reset operation.
Returns
false on any error.
resetQueryPool()
virtual void renderer::CommandBuffer::resetQueryPool (QueryPool const & pool, uint32_t firstQuery, uint32_t queryCount) const pure virtual
Resets a range of queries in a query pool.
Parameters
[in] pool The query pool.
[in] firstQuery The first query index.
[in] queryCount The number of queries (starting at firstQuery).
setScissor()
virtual void renderer::CommandBuffer::setScissor (Scissor const & scissor) const pure virtual
Defines the currently bound pipeline scissor.
Remarks
This action is possible only if the scissor is dynamic, in the pipeline.
Parameters
[in] scissor The scissor.
setViewport()
virtual void renderer::CommandBuffer::setViewport (Viewport const & viewport) const pure virtual
Defines the currently bound pipeline viewport.
Remarks
This action is possible only if the viewport is dynamic, in the pipeline.
Parameters
[in] viewport The viewport.
writeTimestamp()
virtual void renderer::CommandBuffer::writeTimestamp (PipelineStageFlag pipelineStage, QueryPool const & pool, uint32_t query) const pure virtual
Writes a timestamp to given query result.
Parameters
[in] pipelineStage Specifies the stage of the pipeline.
[in] pool The query pool.
[in] query The query index.
The documentation for this class was generated from the following file:
Z:/Projets/C++/RenderLib/source/Renderer/Renderer/Src/Command/CommandBuffer.hpp