Renderer: renderer::SignalConnection< SignalT > Class Template Reference
renderer::SignalConnection< SignalT > Class Template Reference
Représente une connexion à un signal.
Public Member Functions
SignalConnection ()
Constructeur.
SignalConnection (SignalConnection< my_signal > &&rhs)
Constructeur par déplacement.
SignalConnection & operator= (SignalConnection< my_signal > &&rhs)
Opérateur d'affectation par déplacement.
SignalConnection (uint32_t connection, my_signal &signal)
Constructeur.
~SignalConnection ()
Destructeur.
void disconnect ()
Déconnecte la fonction du signal.
Detailed Description
template<typename SignalT>
class renderer::SignalConnection< SignalT >
Représente une connexion à un signal.
Constructor & Destructor Documentation
SignalConnection() [1/3]
template<typename SignalT > renderer::SignalConnection< SignalT >::SignalConnection () inline
Constructeur.
SignalConnection() [2/3]
template<typename SignalT > renderer::SignalConnection< SignalT >::SignalConnection (SignalConnection< my_signal > && rhs) inline
Constructeur par déplacement.
Parameters
[in,out] rhs L'objet à déplacer.
SignalConnection() [3/3]
template<typename SignalT > renderer::SignalConnection< SignalT >::SignalConnection (uint32_t connection, my_signal & signal) inline
Constructeur.
Parameters
[in] connection La connection au signal.
[in] signal Le signal.
~SignalConnection()
template<typename SignalT > renderer::SignalConnection< SignalT >::~SignalConnection () inline
Destructeur.
Remarks
Déconnecte la fonction du signal.
References renderer::SignalConnection< SignalT >::disconnect().
Member Function Documentation
disconnect()
template<typename SignalT > void renderer::SignalConnection< SignalT >::disconnect () inline
Déconnecte la fonction du signal.
Referenced by renderer::Signal< OnResetFunc >::operator()(), and renderer::SignalConnection< SignalT >::~SignalConnection().
operator=()
template<typename SignalT > SignalConnection& renderer::SignalConnection< SignalT >::operator= (SignalConnection< my_signal > && rhs) inline
Opérateur d'affectation par déplacement.
Parameters
[in,out] rhs L'objet à déplacer.
The documentation for this class was generated from the following file:
Z:/Projets/C++/RenderLib/source/Renderer/Renderer/Src/Utils/Signal.hpp