RendererLib: renderer::BufferBase Class Reference
renderer::BufferBase Class Reference abstract
GPU buffer class.
Public Member Functions
virtual ~BufferBase ()
Destructor.
void bindMemory (DeviceMemoryPtr memory)
Binds this buffer to given device memory object.
uint8_t * lock (uint32_t offset, uint32_t size, MemoryMapFlags flags) const
Maps a range of the buffer's memory in RAM.
void invalidate (uint32_t offset, uint32_t size) const
Invalidates the buffer content.
void flush (uint32_t offset, uint32_t size) const
Updates the VRAM.
void unlock () const
Unmaps the buffer's memory from RAM.
PipelineStageFlags getCompatibleStageFlags () const
BufferMemoryBarrier makeTransferDestination (uint32_t srcQueueFamily=~(0u), uint32_t dstQueueFamily=~(0u)) const
Prepares a buffer memory barrier, to a transfer destination layout.
BufferMemoryBarrier makeTransferSource (uint32_t srcQueueFamily=~(0u), uint32_t dstQueueFamily=~(0u)) const
Prepares a buffer memory barrier, to a transfer source layout.
BufferMemoryBarrier makeVertexShaderInputResource (uint32_t srcQueueFamily=~(0u), uint32_t dstQueueFamily=~(0u)) const
Prepares a buffer memory barrier, to a vertex shader input layout.
BufferMemoryBarrier makeUniformBufferInput (uint32_t srcQueueFamily=~(0u), uint32_t dstQueueFamily=~(0u)) const
Prepares a buffer memory barrier, to a uniform buffer input layout.
BufferMemoryBarrier makeMemoryTransitionBarrier (AccessFlags dstAccessFlags, uint32_t srcQueueFamily=~(0u), uint32_t dstQueueFamily=~(0u)) const
Prepares a buffer memory barrier, to a given memory layout.
virtual MemoryRequirements getMemoryRequirements () const =0
uint32_t getSize () const
BufferTargets getTargets () const
Protected Member Functions
BufferBase (Device const &device, uint32_t size, BufferTargets target)
Constructor.
Protected Attributes
Device const & m_device
uint32_t m_size
BufferTargets m_target
DeviceMemoryPtr m_storage
AccessFlags m_currentAccessFlags { AccessFlag::eMemoryWrite }
PipelineStageFlags m_compatibleStageFlags { PipelineStageFlag::eHost }
Detailed Description
GPU buffer class.
Constructor & Destructor Documentation
BufferBase()
renderer::BufferBase::BufferBase (Device const & device, uint32_t size, BufferTargets target) protected
Constructor.
Parameters
[in] device The logical device.
[in] size The buffer size.
[in] target The buffer usage flags.
~BufferBase()
virtual renderer::BufferBase::~BufferBase () virtual
Destructor.
Member Function Documentation
bindMemory()
void renderer::BufferBase::bindMemory (DeviceMemoryPtr memory)
Binds this buffer to given device memory object.
Parameters
[in] memory The memory object.
flush()
void renderer::BufferBase::flush (uint32_t offset, uint32_t size) const
Updates the VRAM.
Parameters
[in] offset The mapped memory starting offset.
[in] size The range size.
getCompatibleStageFlags()
PipelineStageFlags renderer::BufferBase::getCompatibleStageFlags () const inline
Returns
The compatible pipeline stage flags for current access.
References getMemoryRequirements(), m_compatibleStageFlags, makeMemoryTransitionBarrier(), makeTransferDestination(), makeTransferSource(), makeUniformBufferInput(), and makeVertexShaderInputResource().
getMemoryRequirements()
virtual MemoryRequirements renderer::BufferBase::getMemoryRequirements () const pure virtual
Returns
The memory requirements for this buffer.
Referenced by getCompatibleStageFlags().
getSize()
uint32_t renderer::BufferBase::getSize () const inline
Returns
The buffer size.
References m_size.
getTargets()
BufferTargets renderer::BufferBase::getTargets () const inline
Returns
The buffer usage flags.
References m_target.
invalidate()
void renderer::BufferBase::invalidate (uint32_t offset, uint32_t size) const
Invalidates the buffer content.
Parameters
[in] offset The mapped memory starting offset.
[in] size The range size.
lock()
uint8_t* renderer::BufferBase::lock (uint32_t offset, uint32_t size, MemoryMapFlags flags) const
Maps a range of the buffer's memory in RAM.
Parameters
[in] offset The range beginning offset.
[in] size The range size.
[in] flags The mapping flags.
Returns
nullptr if mapping failed.
makeMemoryTransitionBarrier()
BufferMemoryBarrier renderer::BufferBase::makeMemoryTransitionBarrier (AccessFlags dstAccessFlags, uint32_t srcQueueFamily = ~(0u), uint32_t dstQueueFamily = ~(0u)) const
Prepares a buffer memory barrier, to a given memory layout.
Parameters
[in] dstAccessFlags The wanted access flags, after the transition.
[in] srcQueueFamily The source queue family, if a responsibility transfer must happen.
[in] dstQueueFamily The destination queue family, if a responsibility transfer must happen.
Returns
The memory barrier.
Referenced by getCompatibleStageFlags().
makeTransferDestination()
BufferMemoryBarrier renderer::BufferBase::makeTransferDestination (uint32_t srcQueueFamily = ~(0u), uint32_t dstQueueFamily = ~(0u)) const
Prepares a buffer memory barrier, to a transfer destination layout.
Returns
The memory barrier.
Referenced by getCompatibleStageFlags().
makeTransferSource()
BufferMemoryBarrier renderer::BufferBase::makeTransferSource (uint32_t srcQueueFamily = ~(0u), uint32_t dstQueueFamily = ~(0u)) const
Prepares a buffer memory barrier, to a transfer source layout.
Returns
The memory barrier.
Referenced by getCompatibleStageFlags().
makeUniformBufferInput()
BufferMemoryBarrier renderer::BufferBase::makeUniformBufferInput (uint32_t srcQueueFamily = ~(0u), uint32_t dstQueueFamily = ~(0u)) const
Prepares a buffer memory barrier, to a uniform buffer input layout.
Returns
The memory barrier.
Referenced by getCompatibleStageFlags().
makeVertexShaderInputResource()
BufferMemoryBarrier renderer::BufferBase::makeVertexShaderInputResource (uint32_t srcQueueFamily = ~(0u), uint32_t dstQueueFamily = ~(0u)) const
Prepares a buffer memory barrier, to a vertex shader input layout.
Returns
The memory barrier.
Referenced by getCompatibleStageFlags().
unlock()
void renderer::BufferBase::unlock () const
Unmaps the buffer's memory from RAM.
Member Data Documentation
m_compatibleStageFlags
PipelineStageFlags renderer::BufferBase::m_compatibleStageFlags { PipelineStageFlag::eHost } mutable protected
Referenced by getCompatibleStageFlags().
m_currentAccessFlags
AccessFlags renderer::BufferBase::m_currentAccessFlags { AccessFlag::eMemoryWrite } mutable protected
m_device
Device const& renderer::BufferBase::m_device protected
m_size
uint32_t renderer::BufferBase::m_size protected
Referenced by getSize().
m_storage
DeviceMemoryPtr renderer::BufferBase::m_storage protected
m_target
BufferTargets renderer::BufferBase::m_target protected
Referenced by getTargets().
The documentation for this class was generated from the following file:
Z:/Projets/C++/RenderLib/source/Renderer/Renderer/Src/Buffer/Buffer.hpp