RendererLib: renderer::Queue Class Reference
renderer::Queue Class Reference abstract
Command buffers queue.
Public Member Functions
virtual ~Queue ()
virtual bool submit (CommandBufferCRefArray const &commandBuffers, SemaphoreCRefArray const &semaphoresToWait, PipelineStageFlagsArray const &semaphoresStage, SemaphoreCRefArray const &semaphoresToSignal, Fence const *fence) const =0
Submits given command buffers.
virtual bool present (SwapChainCRefArray const &swapChains, UInt32Array const &imagesIndex, SemaphoreCRefArray const &semaphoresToWait) const =0
Presents the queue to the rendering API.
virtual bool waitIdle () const =0
Waits for the queue to be idle.
virtual uint32_t getFamilyIndex () const =0
bool submit (CommandBuffer const &commandBuffer, Fence const *fence) const
Submits given command buffer.
bool submit (CommandBuffer const &commandBuffer, Semaphore const &semaphoreToWait, PipelineStageFlags const &semaphoreStage, Semaphore const &semaphoreToSignal, Fence const *fence) const
Submits given command buffer.
Protected Member Functions
Queue (Device const &device)
Detailed Description
Command buffers queue.
Constructor & Destructor Documentation
Queue()
renderer::Queue::Queue (Device const & device) protected
~Queue()
virtual renderer::Queue::~Queue () virtual
Member Function Documentation
getFamilyIndex()
virtual uint32_t renderer::Queue::getFamilyIndex () const pure virtual
Returns
The queue family index.
present()
virtual bool renderer::Queue::present (SwapChainCRefArray const & swapChains, UInt32Array const & imagesIndex, SemaphoreCRefArray const & semaphoresToWait) const pure virtual
Presents the queue to the rendering API.
Returns
true on ok.
submit() [1/3]
virtual bool renderer::Queue::submit (CommandBufferCRefArray const & commandBuffers, SemaphoreCRefArray const & semaphoresToWait, PipelineStageFlagsArray const & semaphoresStage, SemaphoreCRefArray const & semaphoresToSignal, Fence const * fence) const pure virtual
Submits given command buffers.
Parameters
[in] commandBuffers The command buffers.
[in] semaphoresToWait The semaphores to wait.
[in] semaphoresStage The semaphores respective stages.
[in] semaphoresToSignal The semaphores to signal.
[in] fence An optional fence.
Returns
true on ok.
Referenced by submit().
submit() [2/3]
bool renderer::Queue::submit (CommandBuffer const & commandBuffer, Fence const * fence) const inline
Submits given command buffer.
Parameters
[in] commandBuffer The command buffer.
[in] fence An optional fence.
Returns
true on ok.
References submit().
submit() [3/3]
bool renderer::Queue::submit (CommandBuffer const & commandBuffer, Semaphore const & semaphoreToWait, PipelineStageFlags const & semaphoreStage, Semaphore const & semaphoreToSignal, Fence const * fence) const inline
Submits given command buffer.
Parameters
[in] commandBuffer The command buffer.
[in] semaphoreToWait The semaphore to wait.
[in] semaphoreStage The semaphore respective stages.
[in] semaphoreToSignal The semaphore to signal.
[in] fence An optional fence.
Returns
true on ok.
References submit().
waitIdle()
virtual bool renderer::Queue::waitIdle () const pure virtual
Waits for the queue to be idle.
Returns
true on ok.
The documentation for this class was generated from the following file:
Z:/Projets/C++/RenderLib/source/Renderer/Renderer/Src/Command/Queue.hpp