Renderer: renderer::UniformBuffer< T > Class Template Reference
renderer::UniformBuffer< T > Class Template Reference
Public Member Functions
UniformBuffer (Device const &device, uint32_t count, BufferTargets target, MemoryPropertyFlags flags)
T const & getData (uint32_t index=0) const
T & getData (uint32_t index=0)
std::vector< T > const & getDatas (uint32_t index=0) const
std::vector< T > & getDatas (uint32_t index=0)
uint32_t getAlignedSize () const
Retrieves the aligned size for an element.
UniformBufferBase const & getUbo () const
void upload (uint32_t offset=0u, uint32_t range=1u)
Uploads the buffer data to VRAM.
Constructor & Destructor Documentation
UniformBuffer()
template<typename T> renderer::UniformBuffer< T >::UniformBuffer (Device const & device, uint32_t count, BufferTargets target, MemoryPropertyFlags flags) inline
Constructor.
Parameters
[in] device The logical device.
[in] count The number of instances of the data.
[in] target The buffer usage flags.
[in] flags The memory property flags.
Member Function Documentation
getAlignedSize()
template<typename T> uint32_t renderer::UniformBuffer< T >::getAlignedSize () const inline
Retrieves the aligned size for an element.
Returns
The aligned size.
Referenced by renderer::DescriptorSet::createBinding(), and renderer::DescriptorSet::createDynamicBinding().
getData() [1/2]
template<typename T> T const& renderer::UniformBuffer< T >::getData (uint32_t index = 0) const inline
Returns
The N-th instance of the data.
getData() [2/2]
template<typename T> T& renderer::UniformBuffer< T >::getData (uint32_t index = 0) inline
Returns
The N-th instance of the data.
getDatas() [1/2]
template<typename T> std::vector< T > const& renderer::UniformBuffer< T >::getDatas (uint32_t index = 0) const inline
Returns
The data.
getDatas() [2/2]
template<typename T> std::vector< T >& renderer::UniformBuffer< T >::getDatas (uint32_t index = 0) inline
Returns
The data.
getUbo()
template<typename T> UniformBufferBase const& renderer::UniformBuffer< T >::getUbo () const inline
Returns
The GPU buffer.
Referenced by renderer::DescriptorSet::createBinding(), and renderer::DescriptorSet::createDynamicBinding().
upload()
template<typename T> void renderer::UniformBuffer< T >::upload (uint32_t offset = 0u, uint32_t range = 1u) inline
Uploads the buffer data to VRAM.
Parameters
[in] offset The offset in elements from which buffer memory is mapped.
[in] range The number of elements to map.
References renderer::eInvalidateRange, renderer::eWrite, and renderer::UniformBufferBase::getAlignedSize().
The documentation for this class was generated from the following file:
Z:/Projets/C++/RenderLib/source/Renderer/Renderer/Src/Buffer/UniformBuffer.hpp