ashespp: ashes::DescriptorSet Class Reference
ashes::DescriptorSet Class Reference
A descriptor set.
Public Member Functions
DescriptorSet (Device const &device, DescriptorPool const &pool, DescriptorSetLayout const &layout, uint32_t bindingPoint)
Constructor.
~DescriptorSet ()
Destructor.
void setBindings (VkWriteDescriptorSetArray bindings)
Sets the descriptor set's attaches.
void createBinding (VkDescriptorSetLayoutBinding const &layoutBinding, ImageView const &view, Sampler const &sampler, VkImageLayout layout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, uint32_t index=0u)
Creates a combined image and sampler binding.
void createBinding (VkDescriptorSetLayoutBinding const &layoutBinding, Sampler const &sampler, uint32_t index=0u)
Creates a sampler binding.
void createBinding (VkDescriptorSetLayoutBinding const &layoutBinding, ImageView const &view, VkImageLayout layout, uint32_t index=0u)
Creates a sampled image binding.
void createBinding (VkDescriptorSetLayoutBinding const &layoutBinding, ImageView const &view, uint32_t index=0u)
Creates a storage image binding.
void createBinding (VkDescriptorSetLayoutBinding const &layoutBinding, UniformBufferBase const &uniformBuffer, uint32_t offset, uint32_t range, uint32_t index=0u)
Creates a uniform buffer binding.
void createBinding (VkDescriptorSetLayoutBinding const &layoutBinding, BufferBase const &buffer, uint32_t offset, uint32_t range, uint32_t index=0u)
Creates a storage or uniform buffer binding.
void createBinding (VkDescriptorSetLayoutBinding const &layoutBinding, BufferBase const &buffer, BufferView const &view, uint32_t index=0u)
Creates a texel buffer binding.
void createDynamicBinding (VkDescriptorSetLayoutBinding const &layoutBinding, UniformBufferBase const &uniformBuffer, uint32_t offset, uint32_t range, uint32_t index=0u)
Creates a dynamic uniform buffer binding.
void createDynamicBinding (VkDescriptorSetLayoutBinding const &layoutBinding, BufferBase const &buffer, uint32_t offset, uint32_t range, uint32_t index=0u)
Creates a dynamic storage or uniform buffer binding.
template<typename T >
void createBinding (VkDescriptorSetLayoutBinding const &layoutBinding, UniformBuffer< T > const &uniformBuffer, uint32_t offset=0u, uint32_t range=1u, uint32_t index=0u)
Creates a uniform buffer binding.
template<typename T >
void createBinding (VkDescriptorSetLayoutBinding const &layoutBinding, Buffer< T > const &storageBuffer, uint32_t offset, uint32_t range, uint32_t index=0u)
Creates a storage buffer binding.
template<typename T >
void createBinding (VkDescriptorSetLayoutBinding const &layoutBinding, UniformBuffer< T > const &buffer, BufferView const &view, uint32_t index=0u)
Creates a texel buffer binding.
template<typename T >
void createBinding (VkDescriptorSetLayoutBinding const &layoutBinding, Buffer< T > const &buffer, BufferView const &view, uint32_t index=0u)
Creates a texel buffer binding.
template<typename T >
void createDynamicBinding (VkDescriptorSetLayoutBinding const &layoutBinding, UniformBuffer< T > const &uniformBuffer, uint32_t offset=0u, uint32_t range=1u, uint32_t index=0u)
Creates a dynamic uniform buffer binding.
template<typename T >
void createDynamicBinding (VkDescriptorSetLayoutBinding const &layoutBinding, Buffer< T > const &storageBuffer, uint32_t offset, uint32_t range, uint32_t index=0u)
Creates a dynamic storage buffer binding.
void update () const
Updates all the bindings in the descriptor set.
uint32_t getBindingPoint () const
VkWriteDescriptorSet const & getBinding (uint32_t index) const
VkWriteDescriptorSet & getBinding (uint32_t index)
bool empty () const
operator VkDescriptorSet const & () const
VkDescriptorSet implicit cast operator.
Protected Attributes
VkWriteDescriptorSetArray m_writes
Detailed Description
A descriptor set.
Constructor & Destructor Documentation
DescriptorSet()
ashes::DescriptorSet::DescriptorSet (Device const & device, DescriptorPool const & pool, DescriptorSetLayout const & layout, uint32_t bindingPoint)
Constructor.
Parameters
[in] pool The parent pool.
[in] bindingPoint The binding point for the set.
~DescriptorSet()
ashes::DescriptorSet::~DescriptorSet ()
Destructor.
Member Function Documentation
createBinding() [1/11]
void ashes::DescriptorSet::createBinding (VkDescriptorSetLayoutBinding const & layoutBinding, ImageView const & view, Sampler const & sampler, VkImageLayout layout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, uint32_t index = 0u)
Creates a combined image and sampler binding.
Parameters
[in] layoutBinding The layout binding.
[in] view The image.
[in] sampler The sampler.
[in] layout The wanted image layout.
[in] index The array index.
Referenced by createBinding().
createBinding() [2/11]
void ashes::DescriptorSet::createBinding (VkDescriptorSetLayoutBinding const & layoutBinding, Sampler const & sampler, uint32_t index = 0u)
Creates a sampler binding.
Parameters
[in] layoutBinding The layout binding.
[in] sampler The sampler.
[in] index The array index.
createBinding() [3/11]
void ashes::DescriptorSet::createBinding (VkDescriptorSetLayoutBinding const & layoutBinding, ImageView const & view, VkImageLayout layout, uint32_t index = 0u)
Creates a sampled image binding.
Parameters
[in] layoutBinding The layout binding.
[in] view The image.
[in] layout The image layout.
[in] index The array index.
createBinding() [4/11]
void ashes::DescriptorSet::createBinding (VkDescriptorSetLayoutBinding const & layoutBinding, ImageView const & view, uint32_t index = 0u)
Creates a storage image binding.
Parameters
[in] layoutBinding The layout binding.
[in] view The image.
[in] index The array index.
createBinding() [5/11]
void ashes::DescriptorSet::createBinding (VkDescriptorSetLayoutBinding const & layoutBinding, UniformBufferBase const & uniformBuffer, uint32_t offset, uint32_t range, uint32_t index = 0u)
Creates a uniform buffer binding.
Parameters
[in] layoutBinding The layout binding.
[in] uniformBuffer The buffer.
[in] offset The attach's offset in the buffer.
[in] range The amount of data that can be read from the buffer.
[in] index The array index.
createBinding() [6/11]
void ashes::DescriptorSet::createBinding (VkDescriptorSetLayoutBinding const & layoutBinding, BufferBase const & buffer, uint32_t offset, uint32_t range, uint32_t index = 0u)
Creates a storage or uniform buffer binding.
Parameters
[in] layoutBinding The layout binding.
[in] buffer The buffer.
[in] offset The attach's offset in the buffer.
[in] range The amount of data that can be read from the buffer.
[in] index The array index.
createBinding() [7/11]
void ashes::DescriptorSet::createBinding (VkDescriptorSetLayoutBinding const & layoutBinding, BufferBase const & buffer, BufferView const & view, uint32_t index = 0u)
Creates a texel buffer binding.
Parameters
[in] layoutBinding The layout binding.
[in] buffer The buffer.
[in] view The view to the buffer.
[in] index The array index.
createBinding() [8/11]
template<typename T > void ashes::DescriptorSet::createBinding (VkDescriptorSetLayoutBinding const & layoutBinding, UniformBuffer< T > const & uniformBuffer, uint32_t offset = 0u, uint32_t range = 1u, uint32_t index = 0u) inline
Creates a uniform buffer binding.
Parameters
[in] layoutBinding The layout binding.
[in] uniformBuffer The buffer.
[in] offset The attach's offset in the buffer.
[in] range The amount of data that can be read from the buffer.
[in] index The array index.
References createBinding(), ashes::UniformBuffer< T >::getAlignedSize(), and ashes::UniformBuffer< T >::getUbo().
createBinding() [9/11]
template<typename T > void ashes::DescriptorSet::createBinding (VkDescriptorSetLayoutBinding const & layoutBinding, Buffer< T > const & storageBuffer, uint32_t offset, uint32_t range, uint32_t index = 0u) inline
Creates a storage buffer binding.
Parameters
[in] layoutBinding The layout binding.
[in] storageBuffer The buffer.
[in] offset The attach's offset in the buffer.
[in] range The amount of data that can be read from the buffer.
[in] index The array index.
References createBinding(), and ashes::Buffer< T >::getBuffer().
createBinding() [10/11]
template<typename T > void ashes::DescriptorSet::createBinding (VkDescriptorSetLayoutBinding const & layoutBinding, UniformBuffer< T > const & buffer, BufferView const & view, uint32_t index = 0u) inline
Creates a texel buffer binding.
Parameters
[in] layoutBinding The layout binding.
[in] buffer The buffer.
[in] view The view to the buffer.
[in] index The array index.
References createBinding(), and ashes::UniformBuffer< T >::getUbo().
createBinding() [11/11]
template<typename T > void ashes::DescriptorSet::createBinding (VkDescriptorSetLayoutBinding const & layoutBinding, Buffer< T > const & buffer, BufferView const & view, uint32_t index = 0u) inline
Creates a texel buffer binding.
Parameters
[in] layoutBinding The layout binding.
[in] buffer The buffer.
[in] view The view to the buffer.
[in] index The array index.
References createBinding(), and ashes::Buffer< T >::getBuffer().
createDynamicBinding() [1/4]
void ashes::DescriptorSet::createDynamicBinding (VkDescriptorSetLayoutBinding const & layoutBinding, UniformBufferBase const & uniformBuffer, uint32_t offset, uint32_t range, uint32_t index = 0u)
Creates a dynamic uniform buffer binding.
Remarks
Allow specification of an additional offset at descriptor's binding time.
Parameters
[in] layoutBinding The layout binding.
[in] uniformBuffer The buffer.
[in] offset The attach's offset in the buffer.
[in] range The amount of data that can be read from the buffer.
[in] index The array index.
Referenced by createDynamicBinding().
createDynamicBinding() [2/4]
void ashes::DescriptorSet::createDynamicBinding (VkDescriptorSetLayoutBinding const & layoutBinding, BufferBase const & buffer, uint32_t offset, uint32_t range, uint32_t index = 0u)
Creates a dynamic storage or uniform buffer binding.
Remarks
Allow specification of an additional offset at descriptor's binding time.
Parameters
[in] layoutBinding The layout binding.
[in] buffer The buffer.
[in] offset The attach's offset in the buffer.
[in] range The amount of data that can be read from the buffer.
[in] index The array index.
createDynamicBinding() [3/4]
template<typename T > void ashes::DescriptorSet::createDynamicBinding (VkDescriptorSetLayoutBinding const & layoutBinding, UniformBuffer< T > const & uniformBuffer, uint32_t offset = 0u, uint32_t range = 1u, uint32_t index = 0u) inline
Creates a dynamic uniform buffer binding.
Remarks
Allow specification of an additional offset at descriptor's binding time.
Parameters
[in] layoutBinding The layout binding.
[in] uniformBuffer The buffer.
[in] offset The attach's offset in the buffer.
[in] range The amount of data that can be read from the buffer.
[in] index The array index.
References createDynamicBinding(), ashes::UniformBuffer< T >::getAlignedSize(), and ashes::UniformBuffer< T >::getUbo().
createDynamicBinding() [4/4]
template<typename T > void ashes::DescriptorSet::createDynamicBinding (VkDescriptorSetLayoutBinding const & layoutBinding, Buffer< T > const & storageBuffer, uint32_t offset, uint32_t range, uint32_t index = 0u) inline
Creates a dynamic storage buffer binding.
Remarks
Allow specification of an additional offset at descriptor's binding time.
Parameters
[in] layoutBinding The layout binding.
[in] storageBuffer The buffer.
[in] offset The attach's offset in the buffer.
[in] range The amount of data that can be read from the buffer.
[in] index The array index.
References createDynamicBinding(), and ashes::Buffer< T >::getBuffer().
empty()
bool ashes::DescriptorSet::empty () const inline
Returns
Tells if the set is empty.
References m_writes.
getBinding() [1/2]
VkWriteDescriptorSet const& ashes::DescriptorSet::getBinding (uint32_t index) const inline
Returns
The descriptor at given index.
References m_writes.
getBinding() [2/2]
VkWriteDescriptorSet& ashes::DescriptorSet::getBinding (uint32_t index) inline
Returns
The descriptor at given index.
References m_writes.
getBindingPoint()
uint32_t ashes::DescriptorSet::getBindingPoint () const inline
Returns
The binding point for the set.
operator VkDescriptorSet const &()
ashes::DescriptorSet::operator VkDescriptorSet const & () const inline
VkDescriptorSet implicit cast operator.
setBindings()
void ashes::DescriptorSet::setBindings (VkWriteDescriptorSetArray bindings)
Sets the descriptor set's attaches.
Parameters
[in] bindings The bindings.
update()
void ashes::DescriptorSet::update () const
Updates all the bindings in the descriptor set.
Member Data Documentation
m_writes
VkWriteDescriptorSetArray ashes::DescriptorSet::m_writes protected
Referenced by empty(), and getBinding().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Ashes/include/ashespp/Descriptor/DescriptorSet.hpp