Renderer: renderer::PipelineLayout Class Reference
renderer::PipelineLayout Class Reference abstract
The pipeline layout.
Public Member Functions
virtual ~PipelineLayout ()
Destructor.
virtual PipelinePtr createPipeline (GraphicsPipelineCreateInfo createInfo) const =0
Creates a graphics pipeline using this layout.
virtual ComputePipelinePtr createPipeline (ComputePipelineCreateInfo createInfo) const =0
Creates a compute pipeline using this layout.
PipelinePtr createPipeline (std::vector< ShaderStageState > &&stages, VertexLayoutCRefArray const &vertexLayouts, RenderPass const &renderPass, InputAssemblyState const &inputAssemblyState, RasterisationState const &rasterisationState=RasterisationState{}, ColourBlendState const &colourBlendState=ColourBlendState::createDefault()) const
Creates a graphics pipeline using this layout.
ComputePipelinePtr createPipeline (ShaderStageState &&stage) const
Creates a compute pipeline using this layout.
Protected Member Functions
PipelineLayout (Device const &device, DescriptorSetLayoutCRefArray const &setLayouts, PushConstantRangeCRefArray const &pushConstantRanges)
Constructor.
Detailed Description
The pipeline layout.
Constructor & Destructor Documentation
PipelineLayout()
renderer::PipelineLayout::PipelineLayout (Device const & device, DescriptorSetLayoutCRefArray const & setLayouts, PushConstantRangeCRefArray const & pushConstantRanges) protected
Constructor.
Parameters
[in] device The parent LogicalDevice.
[in] setLayouts The descriptor sets layouts.
[in] pushConstantRanges The push constants ranges.
~PipelineLayout()
virtual renderer::PipelineLayout::~PipelineLayout () virtual
Destructor.
Member Function Documentation
createPipeline() [1/4]
virtual PipelinePtr renderer::PipelineLayout::createPipeline (GraphicsPipelineCreateInfo createInfo) const pure virtual
Creates a graphics pipeline using this layout.
Parameters
[in] createInfo The creation informations.
Returns
The created pipeline.
Referenced by createPipeline().
createPipeline() [2/4]
virtual ComputePipelinePtr renderer::PipelineLayout::createPipeline (ComputePipelineCreateInfo createInfo) const pure virtual
Creates a compute pipeline using this layout.
Parameters
[in] createInfo The creation informations.
Returns
The created pipeline.
createPipeline() [3/4]
PipelinePtr renderer::PipelineLayout::createPipeline (std::vector< ShaderStageState > && stages, VertexLayoutCRefArray const & vertexLayouts, RenderPass const & renderPass, InputAssemblyState const & inputAssemblyState, RasterisationState const & rasterisationState = RasterisationState{}, ColourBlendState const & colourBlendState = ColourBlendState::createDefault()) const inline
Creates a graphics pipeline using this layout.
Parameters
[in] stages The shader stages.
[in] vertexLayouts The vertex layout used by the pipeline.
[in] renderPass The render pass.
[in] inputAssemblyState The input assembly state.
[in] rasterisationState The rasterisation state state.
[in] colourBlendState The colour blend state.
Returns
The created pipeline.
References renderer::VertexInputState::create(), renderer::ColourBlendState::createDefault(), and createPipeline().
createPipeline() [4/4]
ComputePipelinePtr renderer::PipelineLayout::createPipeline (ShaderStageState && stage) const inline
Creates a compute pipeline using this layout.
Parameters
[in] stage The shader stage.
Returns
The created pipeline.
References createPipeline().
The documentation for this class was generated from the following file:
Z:/Projets/C++/RenderLib/source/Renderer/Renderer/Src/Pipeline/PipelineLayout.hpp