ashes: ashes::ArrayView< T > Class Template Reference
ashes::ArrayView< T > Class Template Reference
Templated class that provides std::vector style buffer view.
Public Types
using pointer = T *
using reference = T &
using const_reference = T const &
using iterator = T *
using const_iterator = T const *
using reverse_iterator = std::reverse_iterator< iterator >
using const_reverse_iterator = std::reverse_iterator< const_iterator >
Public Member Functions
ArrayView (pointer begin, pointer end) noexcept
template<size_t N>
ArrayView (T(&buffer)[N]) noexcept
ArrayView (T *buffer, size_t count) noexcept
reference operator[] (size_t index) noexcept
const_reference operator[] (size_t index) const noexcept
bool empty () const noexcept
size_t size () const noexcept
pointer data () noexcept
pointer const data () const noexcept
iterator begin () noexcept
reverse_iterator rbegin () noexcept
const_iterator begin () const noexcept
const_reverse_iterator rbegin () const noexcept
const_iterator cbegin () const noexcept
const_reverse_iterator crbegin () const noexcept
iterator end () noexcept
reverse_iterator rend () noexcept
const_iterator end () const noexcept
const_reverse_iterator rend () const noexcept
const_iterator cend () const noexcept
const_reverse_iterator crend () const noexcept
Detailed Description
template<typename T>
class ashes::ArrayView< T >
Templated class that provides std::vector style buffer view.
Member Typedef Documentation
const_iterator
template<typename T> using ashes::ArrayView< T >::const_iterator = T const *
const_reference
template<typename T> using ashes::ArrayView< T >::const_reference = T const &
const_reverse_iterator
template<typename T> using ashes::ArrayView< T >::const_reverse_iterator = std::reverse_iterator< const_iterator >
iterator
template<typename T> using ashes::ArrayView< T >::iterator = T *
pointer
template<typename T> using ashes::ArrayView< T >::pointer = T *
reference
template<typename T> using ashes::ArrayView< T >::reference = T &
reverse_iterator
template<typename T> using ashes::ArrayView< T >::reverse_iterator = std::reverse_iterator< iterator >
Constructor & Destructor Documentation
ArrayView() [1/3]
template<typename T> ashes::ArrayView< T >::ArrayView (pointer begin, pointer end) inline noexcept
ArrayView() [2/3]
template<typename T> template<size_t N> ashes::ArrayView< T >::ArrayView (T(&) buffer[N]) inline explicit noexcept
ArrayView() [3/3]
template<typename T> ashes::ArrayView< T >::ArrayView (T * buffer, size_t count) inline noexcept
Member Function Documentation
begin() [1/2]
template<typename T> iterator ashes::ArrayView< T >::begin () inline noexcept
Referenced by ashes::operator==(), and ashes::ArrayView< T >::rend().
begin() [2/2]
template<typename T> const_iterator ashes::ArrayView< T >::begin () const inline noexcept
cbegin()
template<typename T> const_iterator ashes::ArrayView< T >::cbegin () const inline noexcept
Referenced by ashes::ArrayView< T >::crend().
cend()
template<typename T> const_iterator ashes::ArrayView< T >::cend () const inline noexcept
Referenced by ashes::ArrayView< T >::crbegin().
crbegin()
template<typename T> const_reverse_iterator ashes::ArrayView< T >::crbegin () const inline noexcept
References ashes::ArrayView< T >::cend().
crend()
template<typename T> const_reverse_iterator ashes::ArrayView< T >::crend () const inline noexcept
References ashes::ArrayView< T >::cbegin().
data() [1/2]
template<typename T> pointer ashes::ArrayView< T >::data () inline noexcept
data() [2/2]
template<typename T> pointer const ashes::ArrayView< T >::data () const inline noexcept
empty()
template<typename T> bool ashes::ArrayView< T >::empty () const inline noexcept
end() [1/2]
template<typename T> iterator ashes::ArrayView< T >::end () inline noexcept
Referenced by ashes::operator==(), and ashes::ArrayView< T >::rbegin().
end() [2/2]
template<typename T> const_iterator ashes::ArrayView< T >::end () const inline noexcept
operator[]() [1/2]
template<typename T> reference ashes::ArrayView< T >::operator[] (size_t index) inline noexcept
operator[]() [2/2]
template<typename T> const_reference ashes::ArrayView< T >::operator[] (size_t index) const inline noexcept
rbegin() [1/2]
template<typename T> reverse_iterator ashes::ArrayView< T >::rbegin () inline noexcept
References ashes::ArrayView< T >::end().
rbegin() [2/2]
template<typename T> const_reverse_iterator ashes::ArrayView< T >::rbegin () const inline noexcept
References ashes::ArrayView< T >::end().
rend() [1/2]
template<typename T> reverse_iterator ashes::ArrayView< T >::rend () inline noexcept
References ashes::ArrayView< T >::begin().
rend() [2/2]
template<typename T> const_reverse_iterator ashes::ArrayView< T >::rend () const inline noexcept
References ashes::ArrayView< T >::begin().
size()
template<typename T> size_t ashes::ArrayView< T >::size () const inline noexcept
Referenced by ashes::operator==().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Ashes/include/ashes/common/ArrayView.hpp