ashespp: ashes::PushConstantsBufferBase Class Reference
ashes::PushConstantsBufferBase Class Reference
Wraps the push constants concept.
Public Member Functions
PushConstantsBufferBase (VkShaderStageFlags stageFlags, PushConstantArray const &variables)
Constructor.
~PushConstantsBufferBase ()
Destructor.
uint32_t getOffset () const
uint32_t getSize () const
VkShaderStageFlags getStageFlags () const
uint8_t const * getData () const
A pointer to the buffer data.
uint8_t * getData ()
A pointer to the buffer data.
PushConstantArray::const_iterator begin () const
PushConstantArray::const_iterator end () const
Protected Attributes
VkShaderStageFlags m_stageFlags
PushConstantArray m_variables
uint32_t m_offset
ByteArray m_data
Detailed Description
Wraps the push constants concept.
Constructor & Destructor Documentation
PushConstantsBufferBase()
ashes::PushConstantsBufferBase::PushConstantsBufferBase (VkShaderStageFlags stageFlags, PushConstantArray const & variables)
Constructor.
Parameters
[in] stageFlags Specifies the shader stages that will use the push constants in the updated range.
[in] variables The constants contained in the buffer.
~PushConstantsBufferBase()
ashes::PushConstantsBufferBase::~PushConstantsBufferBase () inline
Destructor.
Member Function Documentation
begin()
PushConstantArray::const_iterator ashes::PushConstantsBufferBase::begin () const inline
Returns
The beginning of the constants array.
References m_variables.
Referenced by ashes::PushConstantsBuffer< T >::begin().
end()
PushConstantArray::const_iterator ashes::PushConstantsBufferBase::end () const inline
Returns
The end of the constants array.
References m_variables.
Referenced by ashes::PushConstantsBuffer< T >::end().
getData() [1/2]
uint8_t const* ashes::PushConstantsBufferBase::getData () const inline
A pointer to the buffer data.
References m_data.
getData() [2/2]
uint8_t* ashes::PushConstantsBufferBase::getData () inline
A pointer to the buffer data.
References m_data.
getOffset()
uint32_t ashes::PushConstantsBufferBase::getOffset () const inline
Returns
The base offset.
References m_offset.
Referenced by ashes::PushConstantsBuffer< T >::getOffset().
getSize()
uint32_t ashes::PushConstantsBufferBase::getSize () const inline
Returns
The data size.
References m_data.
Referenced by ashes::PushConstantsBuffer< T >::getSize().
getStageFlags()
VkShaderStageFlags ashes::PushConstantsBufferBase::getStageFlags () const inline
Returns
The shader stages that will use the push constants in the updated range.
References m_stageFlags.
Referenced by ashes::PushConstantsBuffer< T >::getStageFlags().
Member Data Documentation
m_data
ByteArray ashes::PushConstantsBufferBase::m_data protected
Referenced by getData(), and getSize().
m_offset
uint32_t ashes::PushConstantsBufferBase::m_offset protected
Referenced by getOffset().
m_stageFlags
VkShaderStageFlags ashes::PushConstantsBufferBase::m_stageFlags protected
Referenced by getStageFlags().
m_variables
PushConstantArray ashes::PushConstantsBufferBase::m_variables protected
Referenced by begin(), and end().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Ashes/include/ashespp/Buffer/PushConstantsBuffer.hpp