ashes: ashes Namespace Reference
ashes Namespace Reference
Classes
class ArrayView
Templated class that provides std::vector style buffer view.
class DynamicLibrary
Platform independant shared library (.dll or .so).
class Exception
API exception class.
class FlagCombination
Template class providing implicit conversion from a scoped enum to a basic integer type.
struct FlagIterator
Template iterator class on a binary combination of flags.
class Signal
Classe basique de signal.
class SignalConnection
Représente une connexion à un signal.
Typedefs
using ByteArray = std::vector< uint8_t >
using UInt16Array = std::vector< uint16_t >
using UInt32Array = std::vector< uint32_t >
using UInt64Array = std::vector< uint64_t >
using FloatArray = std::vector< float >
using StringArray = std::vector< std::string >
using CharPtrArray = std::vector< char const * >
using VkAttachmentDescriptionArray = std::vector< VkAttachmentDescription >
using VkAttachmentReferenceArray = std::vector< VkAttachmentReference >
using VkBufferArray = std::vector< VkBuffer >
using VkBufferCopyArray = std::vector< VkBufferCopy >
using VkBufferImageCopyArray = std::vector< VkBufferImageCopy >
using VkBufferMemoryBarrierArray = std::vector< VkBufferMemoryBarrier >
using VkClearAttachmentArray = std::vector< VkClearAttachment >
using VkClearRectArray = std::vector< VkClearRect >
using VkClearValueArray = std::vector< VkClearValue >
using VkCommandBufferArray = std::vector< VkCommandBuffer >
using VkDescriptorPoolSizeArray = std::vector< VkDescriptorPoolSize >
using VkDescriptorSetArray = std::vector< VkDescriptorSet >
using VkDescriptorSetLayoutArray = std::vector< VkDescriptorSetLayout >
using VkDescriptorSetLayoutBindingArray = std::vector< VkDescriptorSetLayoutBinding >
using VkDeviceQueueCreateInfoArray = std::vector< VkDeviceQueueCreateInfo >
using VkDeviceSizeArray = std::vector< VkDeviceSize >
using VkDynamicStateArray = std::vector< VkDynamicState >
using VkEventArray = std::vector< VkEvent >
using VkExtensionPropertiesArray = std::vector< VkExtensionProperties >
using VkImageArray = std::vector< VkImage >
using VkImageBlitArray = std::vector< VkImageBlit >
using VkImageCopyArray = std::vector< VkImageCopy >
using VkImageMemoryBarrierArray = std::vector< VkImageMemoryBarrier >
using VkImageSubresourceRangeArray = std::vector< VkImageSubresourceRange >
using VkImageViewArray = std::vector< VkImageView >
using VkLayerPropertiesArray = std::vector< VkLayerProperties >
using VkMemoryBarrierArray = std::vector< VkMemoryBarrier >
using VkPipelineCacheArray = std::vector< VkPipelineCache >
using VkPipelineColorBlendAttachmentStateArray = std::vector< VkPipelineColorBlendAttachmentState >
using VkPipelineShaderStageCreateInfoArray = std::vector< VkPipelineShaderStageCreateInfo >
using VkPipelineStageFlagsArray = std::vector< VkPipelineStageFlags >
using VkPhysicalDeviceArray = std::vector< VkPhysicalDevice >
using VkPresentModeArrayKHR = std::vector< VkPresentModeKHR >
using VkPushConstantRangeArray = std::vector< VkPushConstantRange >
using VkQueueFamilyPropertiesArray = std::vector< VkQueueFamilyProperties >
using VkResultArray = std::vector< VkResult >
using VkSemaphoreArray = std::vector< VkSemaphore >
using VkScissorArray = std::vector< VkRect2D >
using VkShaderModuleArray = std::vector< VkShaderModule >
using VkSpecializationMapEntryArray = std::vector< VkSpecializationMapEntry >
using VkSubmitInfoArray = std::vector< VkSubmitInfo >
using VkSubpassDependencyArray = std::vector< VkSubpassDependency >
using VkSubpassDescriptionArray = std::vector< VkSubpassDescription >
using VkSurfaceFormatArrayKHR = std::vector< VkSurfaceFormatKHR >
using VkSwapchainArrayKHR = std::vector< VkSwapchainKHR >
using VkVertexInputAttributeDescriptionArray = std::vector< VkVertexInputAttributeDescription >
using VkVertexInputBindingDescriptionArray = std::vector< VkVertexInputBindingDescription >
using VkViewportArray = std::vector< VkViewport >
using VkWriteDescriptorSetArray = std::vector< VkWriteDescriptorSet >
template<typename T >
using Optional = std::optional< T >
Functions
constexpr uint32_t getMajor (uint32_t version)
constexpr uint32_t getMinor (uint32_t version)
constexpr uint32_t getPatch (uint32_t version)
constexpr uint32_t makeVersion (uint32_t major, uint32_t minor, uint32_t patch)
uint32_t checkFlag (uint32_t a, uint32_t b)
template<typename VkType , typename LibType >
std::vector< VkType > makeVkArray (std::vector< LibType > const &input)
template<typename VkType , typename LibType >
std::vector< VkType > makeVkArray (std::vector< std::reference_wrapper< LibType > > const &input)
template<typename VkType , typename LibType >
std::vector< VkType > makeVkArray (std::vector< std::unique_ptr< LibType > > const &input)
template<typename VkType , typename LibType >
std::vector< VkType > makeVkArray (std::vector< std::reference_wrapper< LibType const > > const &input)
CharPtrArray convert (StringArray const &values)
StringArray convert (CharPtrArray const &values)
template<typename VkType , typename LibType >
std::vector< VkType > convert (std::vector< LibType > const &values)
template<typename VkType , typename LibType >
std::vector< VkType > convert (std::vector< std::reference_wrapper< LibType const > > const &values)
template<typename VkType , typename ItType >
std::vector< VkType > convert (ItType begin, ItType end)
VkClearValue makeClearValue (VkClearColorValue v)
VkClearValue makeClearValue (VkClearDepthStencilValue v)
template<typename Type , typename ... Params>
std::vector< Type > makeVector (Type const *ptr, size_t count, Params &&... params)
template<typename Type , typename ... Params>
std::vector< Type > makeVector (Type const *ptr, uint32_t count, Params &&... params)
template<typename Type , typename ... Params>
Optional< Type > makeOptional (Type const *ptr, Params &&... params)
VkSpecializationMapEntry deepCopy (VkSpecializationMapEntry const &rhs)
uint8_t deepCopy (uint8_t const &rhs)
VkSpecializationInfo deepCopy (VkSpecializationInfo const &rhs, VkSpecializationMapEntryArray &entries, ByteArray &data)
VkPipelineShaderStageCreateInfo deepCopy (VkPipelineShaderStageCreateInfo const &rhs, Optional< VkSpecializationInfo > &specializationInfo, VkSpecializationMapEntryArray &entries, ByteArray &data)
VkPipelineColorBlendAttachmentState deepCopy (VkPipelineColorBlendAttachmentState const &rhs)
VkPipelineColorBlendStateCreateInfo deepCopy (VkPipelineColorBlendStateCreateInfo const &rhs, VkPipelineColorBlendAttachmentStateArray &attachments)
VkStencilOpState deepCopy (VkStencilOpState const &rhs)
VkPipelineDepthStencilStateCreateInfo deepCopy (VkPipelineDepthStencilStateCreateInfo const &rhs)
VkDynamicState deepCopy (VkDynamicState const &rhs)
VkPipelineDynamicStateCreateInfo deepCopy (VkPipelineDynamicStateCreateInfo const &rhs, VkDynamicStateArray &states)
VkPipelineInputAssemblyStateCreateInfo deepCopy (VkPipelineInputAssemblyStateCreateInfo const &rhs)
VkPipelineMultisampleStateCreateInfo deepCopy (VkPipelineMultisampleStateCreateInfo const &rhs)
VkPipelineRasterizationStateCreateInfo deepCopy (VkPipelineRasterizationStateCreateInfo const &rhs)
VkPipelineTessellationStateCreateInfo deepCopy (VkPipelineTessellationStateCreateInfo const &rhs)
VkVertexInputAttributeDescription deepCopy (VkVertexInputAttributeDescription const &rhs)
VkVertexInputBindingDescription deepCopy (VkVertexInputBindingDescription const &rhs)
VkPipelineVertexInputStateCreateInfo deepCopy (VkPipelineVertexInputStateCreateInfo const &rhs, VkVertexInputBindingDescriptionArray &bindings, VkVertexInputAttributeDescriptionArray &attributes)
VkViewport deepCopy (VkViewport const &rhs)
VkRect2D deepCopy (VkRect2D const &rhs)
VkPipelineViewportStateCreateInfo deepCopy (VkPipelineViewportStateCreateInfo const &rhs, VkViewportArray &viewports, VkScissorArray &scissors)
template<typename T >
bool operator== (ArrayView< T > const &lhs, ArrayView< T > const &rhs)
template<typename T >
ArrayView< T > makeArrayView (T *begin, uint32_t size)
template<typename T >
ArrayView< T > makeArrayView (T *begin, size_t size)
template<typename T >
ArrayView< T > makeArrayView (T *begin, T *end)
template<typename T , size_t N>
ArrayView< T > makeArrayView (T(&buffer)[N])
std::string getName (VkResult value)
bool listDirectoryFiles (std::string const &folderPath, StringArray &files, bool recursive=false)
List all files in a directory, recursively or not.
std::string getExecutableDirectory ()
std::string getPath (std::string const &path)
Retrieves the given path's parent folder.
std::string getFileName (std::string const &path)
Retrieves the given path's file name.
template<typename T , typename U >
bool checkFlag (T const &value, U const &flag) noexcept
Checks if the given flag is part of the given combination.
template<typename FlagType >
bool checkFlag (FlagCombination< FlagType > const &value, FlagType const &flag) noexcept
Checks if the given flag is part of the given combination.
template<typename FlagType , typename Type >
bool checkFlag (FlagCombination< FlagType > const &value, Type const &flag) noexcept
Checks if the given flag is part of the given combination.
template<typename FlagType >
FlagCombination< FlagType > & addFlag (FlagCombination< FlagType > &value, FlagType const &flag) noexcept
Adds a flag to given combination.
template<typename FlagType >
FlagCombination< FlagType > & remFlag (FlagCombination< FlagType > &value, FlagType const &flag) noexcept
Removes a flag from given combination.
template<typename FlagType >
FlagCombination< FlagType > addFlag (FlagCombination< FlagType > const &value, FlagType const &flag) noexcept
Adds a flag to given combination.
template<typename FlagType >
FlagCombination< FlagType > remFlag (FlagCombination< FlagType > const &value, FlagType const &flag) noexcept
Removes a flag from given combination.
VkDeviceSize getAlignedSize (VkDeviceSize size, VkDeviceSize align)
Computes an aligned size.
uint32_t getSize (VkFormat format) noexcept
Retrieves the byte size of given non compressed pixel format.
uint32_t getCount (VkFormat format) noexcept
uint32_t getBCSize (VkFormat format) noexcept
Retrieves the byte size of given BC compressed pixel format, for a 4x4 pixels block.
uint32_t getETC2Size (VkFormat format) noexcept
Retrieves the byte size of given ETC2 compressed pixel format, for a 4x4 pixels block.
uint32_t getEACSize (VkFormat format) noexcept
Retrieves the byte size of given EAC compressed pixel format, for a 4x4 pixels block.
bool isDepthStencilFormat (VkFormat format) noexcept
Tells if the given VkFormat is usable in depth and stencil buffers.
bool isStencilFormat (VkFormat format) noexcept
Tells if the given VkFormat is usable in stencil buffers.
bool isDepthFormat (VkFormat format) noexcept
Tells if the given VkFormat is usable in depth buffers.
bool isBCFormat (VkFormat format) noexcept
Tells if given pixel format is a BC compressed pixel format.
bool isETC2Format (VkFormat format) noexcept
Tells if given pixel format is a ETC2 compressed pixel format.
bool isEACFormat (VkFormat format) noexcept
Tells if given pixel format is a EAC compressed pixel format.
bool isASTCFormat (VkFormat format) noexcept
Tells if given pixel format is a ASTC compressed pixel format.
bool isYCBCRFormat (VkFormat format) noexcept
Tells if given pixel format is a YCBCR pixel format.
bool isPVRTCFormat (VkFormat format) noexcept
Tells if given pixel format is a PVRTC pixel format.
bool isCompressedFormat (VkFormat format) noexcept
Tells if given pixel format is a compressed pixel format.
bool isDepthOrStencilFormat (VkFormat format) noexcept
Tells if the given VkFormat is usable in depth and/or stencil buffers.
std::string getName (VkFormat value)
Gets the name of the given element.
VkExtent2D getMinimalExtent2D (VkFormat format) noexcept
Retrieves the minimal VkExtent2D for given pixel format.
bool checkExtent (VkFormat format, VkExtent2D const &extent)
Checks if the given extent fits the given format.
VkDeviceSize getSize (VkExtent2D const &extent, VkFormat format) noexcept
Retrieves the byte size of given pixel format and dimensions.
VkExtent3D getMinimalExtent3D (VkFormat format) noexcept
Retrieves the minimal VkExtent2D for given pixel format.
bool checkExtent (VkFormat format, VkExtent3D const &extent)
Checks if the given extent fits the given format.
VkDeviceSize getSize (VkExtent3D const &extent, VkFormat format) noexcept
Retrieves the byte size of given pixel format and dimensions.
VkImageAspectFlags getAspectMask (VkFormat format) noexcept
Retrieves the aspects mask matching given VkFormat.
template<typename T >
T getSubresourceDimension (T const &extent, uint32_t mipLevel)
Retrieves the real extent for the given mipmap level.
VkExtent3D getSubresourceDimensions (VkExtent3D const &extent, uint32_t mipLevel)
Retrieves the real extent for the given mipmap level.
VkDeviceSize getSize (VkExtent3D const &extent, VkFormat format, uint32_t mipLevel) noexcept
Retrieves the byte size of given pixel format and dimensions.
VkExtent3D getSubresourceDimensions (VkExtent2D const &extent, uint32_t mipLevel)
Retrieves the real extent for the given mipmap level.
VkDeviceSize getSize (VkExtent2D const &extent, VkFormat format, uint32_t mipLevel) noexcept
Retrieves the byte size of given pixel format and dimensions.
Comparison operators.
template<typename FlagType >
bool operator== (FlagCombination< FlagType > const &lhs, FlagCombination< FlagType > const &rhs) noexcept
template<typename FlagType >
bool operator== (FlagCombination< FlagType > const &lhs, FlagType const &rhs) noexcept
template<typename FlagType >
bool operator!= (FlagCombination< FlagType > const &lhs, FlagCombination< FlagType > const &rhs) noexcept
template<typename FlagType >
bool operator!= (FlagCombination< FlagType > const &lhs, FlagType const &rhs) noexcept
Binary operators.
template<typename FlagType >
FlagCombination< FlagType > operator & (FlagCombination< FlagType > const &lhs, FlagType const &rhs) noexcept
template<typename FlagType >
FlagCombination< FlagType > operator| (FlagCombination< FlagType > const &lhs, FlagType const &rhs) noexcept
template<typename FlagType >
FlagCombination< FlagType > operator & (FlagCombination< FlagType > const &lhs, typename FlagCombination< FlagType >::BaseType const &rhs) noexcept
template<typename FlagType >
FlagCombination< FlagType > operator| (FlagCombination< FlagType > const &lhs, typename FlagCombination< FlagType >::BaseType const &rhs) noexcept
Variables
static VkDeviceSize constexpr WholeSize = ~(0ull)
Typedef Documentation
ByteArray
using ashes::ByteArray = typedef std::vector< uint8_t >
CharPtrArray
using ashes::CharPtrArray = typedef std::vector< char const * >
FloatArray
using ashes::FloatArray = typedef std::vector< float >
Optional
template<typename T > using ashes::Optional = typedef std::optional< T >
StringArray
typedef std::vector< std::string > ashes::StringArray
UInt16Array
using ashes::UInt16Array = typedef std::vector< uint16_t >
UInt32Array
using ashes::UInt32Array = typedef std::vector< uint32_t >
UInt64Array
using ashes::UInt64Array = typedef std::vector< uint64_t >
VkAttachmentDescriptionArray
using ashes::VkAttachmentDescriptionArray = typedef std::vector< VkAttachmentDescription >
VkAttachmentReferenceArray
using ashes::VkAttachmentReferenceArray = typedef std::vector< VkAttachmentReference >
VkBufferArray
using ashes::VkBufferArray = typedef std::vector< VkBuffer >
VkBufferCopyArray
using ashes::VkBufferCopyArray = typedef std::vector< VkBufferCopy >
VkBufferImageCopyArray
using ashes::VkBufferImageCopyArray = typedef std::vector< VkBufferImageCopy >
VkBufferMemoryBarrierArray
using ashes::VkBufferMemoryBarrierArray = typedef std::vector< VkBufferMemoryBarrier >
VkClearAttachmentArray
using ashes::VkClearAttachmentArray = typedef std::vector< VkClearAttachment >
VkClearRectArray
using ashes::VkClearRectArray = typedef std::vector< VkClearRect >
VkClearValueArray
using ashes::VkClearValueArray = typedef std::vector< VkClearValue >
VkCommandBufferArray
using ashes::VkCommandBufferArray = typedef std::vector< VkCommandBuffer >
VkDescriptorPoolSizeArray
using ashes::VkDescriptorPoolSizeArray = typedef std::vector< VkDescriptorPoolSize >
VkDescriptorSetArray
using ashes::VkDescriptorSetArray = typedef std::vector< VkDescriptorSet >
VkDescriptorSetLayoutArray
using ashes::VkDescriptorSetLayoutArray = typedef std::vector< VkDescriptorSetLayout >
VkDescriptorSetLayoutBindingArray
using ashes::VkDescriptorSetLayoutBindingArray = typedef std::vector< VkDescriptorSetLayoutBinding >
VkDeviceQueueCreateInfoArray
using ashes::VkDeviceQueueCreateInfoArray = typedef std::vector< VkDeviceQueueCreateInfo >
VkDeviceSizeArray
using ashes::VkDeviceSizeArray = typedef std::vector< VkDeviceSize >
VkDynamicStateArray
using ashes::VkDynamicStateArray = typedef std::vector< VkDynamicState >
VkEventArray
using ashes::VkEventArray = typedef std::vector< VkEvent >
VkExtensionPropertiesArray
using ashes::VkExtensionPropertiesArray = typedef std::vector< VkExtensionProperties >
VkImageArray
using ashes::VkImageArray = typedef std::vector< VkImage >
VkImageBlitArray
using ashes::VkImageBlitArray = typedef std::vector< VkImageBlit >
VkImageCopyArray
using ashes::VkImageCopyArray = typedef std::vector< VkImageCopy >
VkImageMemoryBarrierArray
using ashes::VkImageMemoryBarrierArray = typedef std::vector< VkImageMemoryBarrier >
VkImageSubresourceRangeArray
using ashes::VkImageSubresourceRangeArray = typedef std::vector< VkImageSubresourceRange >
VkImageViewArray
using ashes::VkImageViewArray = typedef std::vector< VkImageView >
VkLayerPropertiesArray
using ashes::VkLayerPropertiesArray = typedef std::vector< VkLayerProperties >
VkMemoryBarrierArray
using ashes::VkMemoryBarrierArray = typedef std::vector< VkMemoryBarrier >
VkPhysicalDeviceArray
using ashes::VkPhysicalDeviceArray = typedef std::vector< VkPhysicalDevice >
VkPipelineCacheArray
using ashes::VkPipelineCacheArray = typedef std::vector< VkPipelineCache >
VkPipelineColorBlendAttachmentStateArray
using ashes::VkPipelineColorBlendAttachmentStateArray = typedef std::vector< VkPipelineColorBlendAttachmentState >
VkPipelineShaderStageCreateInfoArray
using ashes::VkPipelineShaderStageCreateInfoArray = typedef std::vector< VkPipelineShaderStageCreateInfo >
VkPipelineStageFlagsArray
using ashes::VkPipelineStageFlagsArray = typedef std::vector< VkPipelineStageFlags >
VkPresentModeArrayKHR
using ashes::VkPresentModeArrayKHR = typedef std::vector< VkPresentModeKHR >
VkPushConstantRangeArray
using ashes::VkPushConstantRangeArray = typedef std::vector< VkPushConstantRange >
VkQueueFamilyPropertiesArray
using ashes::VkQueueFamilyPropertiesArray = typedef std::vector< VkQueueFamilyProperties >
VkResultArray
using ashes::VkResultArray = typedef std::vector< VkResult >
VkScissorArray
using ashes::VkScissorArray = typedef std::vector< VkRect2D >
VkSemaphoreArray
using ashes::VkSemaphoreArray = typedef std::vector< VkSemaphore >
VkShaderModuleArray
using ashes::VkShaderModuleArray = typedef std::vector< VkShaderModule >
VkSpecializationMapEntryArray
using ashes::VkSpecializationMapEntryArray = typedef std::vector< VkSpecializationMapEntry >
VkSubmitInfoArray
using ashes::VkSubmitInfoArray = typedef std::vector< VkSubmitInfo >
VkSubpassDependencyArray
using ashes::VkSubpassDependencyArray = typedef std::vector< VkSubpassDependency >
VkSubpassDescriptionArray
using ashes::VkSubpassDescriptionArray = typedef std::vector< VkSubpassDescription >
VkSurfaceFormatArrayKHR
using ashes::VkSurfaceFormatArrayKHR = typedef std::vector< VkSurfaceFormatKHR >
VkSwapchainArrayKHR
using ashes::VkSwapchainArrayKHR = typedef std::vector< VkSwapchainKHR >
VkVertexInputAttributeDescriptionArray
using ashes::VkVertexInputAttributeDescriptionArray = typedef std::vector< VkVertexInputAttributeDescription >
VkVertexInputBindingDescriptionArray
using ashes::VkVertexInputBindingDescriptionArray = typedef std::vector< VkVertexInputBindingDescription >
VkViewportArray
using ashes::VkViewportArray = typedef std::vector< VkViewport >
VkWriteDescriptorSetArray
using ashes::VkWriteDescriptorSetArray = typedef std::vector< VkWriteDescriptorSet >
Function Documentation
addFlag() [1/2]
template<typename FlagType > FlagCombination< FlagType >& ashes::addFlag (FlagCombination< FlagType > & value, FlagType const & flag) inline noexcept
Adds a flag to given combination.
Parameters
[in,out] value The combination.
[in] flag The flag to add.
Returns
The combination.
addFlag() [2/2]
template<typename FlagType > FlagCombination< FlagType > ashes::addFlag (FlagCombination< FlagType > const & value, FlagType const & flag) inline noexcept
Adds a flag to given combination.
Parameters
[in] value The combination.
[in] flag The flag to add.
Returns
The new combination.
checkExtent() [1/2]
bool ashes::checkExtent (VkFormat format, VkExtent2D const & extent) inline
Checks if the given extent fits the given format.
Parameters
[in] extent The dimensions.
[in] format The pixel format.
Returns
true if the extent is compatible with the format.
References getMinimalExtent2D().
Referenced by checkExtent().
checkExtent() [2/2]
bool ashes::checkExtent (VkFormat format, VkExtent3D const & extent) inline
Checks if the given extent fits the given format.
Parameters
[in] extent The dimensions.
[in] format The pixel format.
Returns
true if the extent is compatible with the format.
References checkExtent().
checkFlag() [1/4]
uint32_t ashes::checkFlag (uint32_t a, uint32_t b) inline
checkFlag() [2/4]
template<typename T , typename U > bool ashes::checkFlag (T const & value, U const & flag) inline noexcept
Checks if the given flag is part of the given combination.
Parameters
[in] value The combination.
[in] flag The flag.
Returns
true if value contains flag.
checkFlag() [3/4]
template<typename FlagType > bool ashes::checkFlag (FlagCombination< FlagType > const & value, FlagType const & flag) inline noexcept
Checks if the given flag is part of the given combination.
Parameters
[in] value The combination.
[in] flag The flag.
Returns
true if value contains flag.
checkFlag() [4/4]
template<typename FlagType , typename Type > bool ashes::checkFlag (FlagCombination< FlagType > const & value, Type const & flag) inline noexcept
Checks if the given flag is part of the given combination.
Parameters
[in] value The combination.
[in] flag The flag.
Returns
true if value contains flag.
convert() [1/5]
CharPtrArray ashes::convert (StringArray const & values) inline
Referenced by convert().
convert() [2/5]
StringArray ashes::convert (CharPtrArray const & values) inline
convert() [3/5]
template<typename VkType , typename LibType > std::vector< VkType > ashes::convert (std::vector< LibType > const & values)
References convert().
convert() [4/5]
template<typename VkType , typename LibType > std::vector< VkType > ashes::convert (std::vector< std::reference_wrapper< LibType const > > const & values)
References convert().
convert() [5/5]
template<typename VkType , typename ItType > std::vector< VkType > ashes::convert (ItType begin, ItType end)
References convert().
deepCopy() [1/20]
VkSpecializationMapEntry ashes::deepCopy (VkSpecializationMapEntry const & rhs) inline
Referenced by deepCopy(), makeOptional(), and makeVector().
deepCopy() [2/20]
uint8_t ashes::deepCopy (uint8_t const & rhs) inline
deepCopy() [3/20]
VkSpecializationInfo ashes::deepCopy (VkSpecializationInfo const & rhs, VkSpecializationMapEntryArray & entries, ByteArray & data) inline
References makeVector().
deepCopy() [4/20]
VkPipelineShaderStageCreateInfo ashes::deepCopy (VkPipelineShaderStageCreateInfo const & rhs, Optional< VkSpecializationInfo > & specializationInfo, VkSpecializationMapEntryArray & entries, ByteArray & data) inline
References deepCopy().
deepCopy() [5/20]
VkPipelineColorBlendAttachmentState ashes::deepCopy (VkPipelineColorBlendAttachmentState const & rhs) inline
deepCopy() [6/20]
VkPipelineColorBlendStateCreateInfo ashes::deepCopy (VkPipelineColorBlendStateCreateInfo const & rhs, VkPipelineColorBlendAttachmentStateArray & attachments) inline
References makeVector().
deepCopy() [7/20]
VkStencilOpState ashes::deepCopy (VkStencilOpState const & rhs) inline
deepCopy() [8/20]
VkPipelineDepthStencilStateCreateInfo ashes::deepCopy (VkPipelineDepthStencilStateCreateInfo const & rhs) inline
deepCopy() [9/20]
VkDynamicState ashes::deepCopy (VkDynamicState const & rhs) inline
deepCopy() [10/20]
VkPipelineDynamicStateCreateInfo ashes::deepCopy (VkPipelineDynamicStateCreateInfo const & rhs, VkDynamicStateArray & states) inline
References makeVector().
deepCopy() [11/20]
VkPipelineInputAssemblyStateCreateInfo ashes::deepCopy (VkPipelineInputAssemblyStateCreateInfo const & rhs) inline
deepCopy() [12/20]
VkPipelineMultisampleStateCreateInfo ashes::deepCopy (VkPipelineMultisampleStateCreateInfo const & rhs) inline
deepCopy() [13/20]
VkPipelineRasterizationStateCreateInfo ashes::deepCopy (VkPipelineRasterizationStateCreateInfo const & rhs) inline
deepCopy() [14/20]
VkPipelineTessellationStateCreateInfo ashes::deepCopy (VkPipelineTessellationStateCreateInfo const & rhs) inline
deepCopy() [15/20]
VkVertexInputAttributeDescription ashes::deepCopy (VkVertexInputAttributeDescription const & rhs) inline
deepCopy() [16/20]
VkVertexInputBindingDescription ashes::deepCopy (VkVertexInputBindingDescription const & rhs) inline
deepCopy() [17/20]
VkPipelineVertexInputStateCreateInfo ashes::deepCopy (VkPipelineVertexInputStateCreateInfo const & rhs, VkVertexInputBindingDescriptionArray & bindings, VkVertexInputAttributeDescriptionArray & attributes) inline
References makeVector().
deepCopy() [18/20]
VkViewport ashes::deepCopy (VkViewport const & rhs) inline
deepCopy() [19/20]
VkRect2D ashes::deepCopy (VkRect2D const & rhs) inline
deepCopy() [20/20]
VkPipelineViewportStateCreateInfo ashes::deepCopy (VkPipelineViewportStateCreateInfo const & rhs, VkViewportArray & viewports, VkScissorArray & scissors) inline
References makeVector().
getAlignedSize()
VkDeviceSize ashes::getAlignedSize (VkDeviceSize size, VkDeviceSize align) inline
Computes an aligned size.
Parameters
[in] size The unaligned size.
[in] align The alignment value.
Returns
The aligned size.
getAspectMask()
VkImageAspectFlags ashes::getAspectMask (VkFormat format) inline noexcept
Retrieves the aspects mask matching given VkFormat.
Parameters
[in] format The VkFormat.
Returns
The aspects.
References isDepthFormat(), isDepthStencilFormat(), and isStencilFormat().
getBCSize()
uint32_t ashes::getBCSize (VkFormat format) noexcept
Retrieves the byte size of given BC compressed pixel format, for a 4x4 pixels block.
Parameters
[in] format The pixel format.
Returns
The byte size.
getCount()
uint32_t ashes::getCount (VkFormat format) noexcept
Returns
le nombre de composantes du format donné.
Parameters
[in] format Le VkFormat.
getEACSize()
uint32_t ashes::getEACSize (VkFormat format) noexcept
Retrieves the byte size of given EAC compressed pixel format, for a 4x4 pixels block.
Parameters
[in] format The pixel format.
Returns
The byte size.
getETC2Size()
uint32_t ashes::getETC2Size (VkFormat format) noexcept
Retrieves the byte size of given ETC2 compressed pixel format, for a 4x4 pixels block.
Parameters
[in] format The pixel format.
Returns
The byte size.
getExecutableDirectory()
std::string ashes::getExecutableDirectory ()
Returns
The executable folder.
getFileName()
std::string ashes::getFileName (std::string const & path)
Retrieves the given path's file name.
Parameters
[in] path The path.
Returns
The file name.
getMajor()
constexpr uint32_t ashes::getMajor (uint32_t version) inline
getMinimalExtent2D()
VkExtent2D ashes::getMinimalExtent2D (VkFormat format) noexcept
Retrieves the minimal VkExtent2D for given pixel format.
Parameters
[in] format The pixel format.
Returns
The VkExtent2D.
Referenced by checkExtent(), and getMinimalExtent3D().
getMinimalExtent3D()
VkExtent3D ashes::getMinimalExtent3D (VkFormat format) inline noexcept
Retrieves the minimal VkExtent2D for given pixel format.
Parameters
[in] format The pixel format.
Returns
The VkExtent2D.
References getMinimalExtent2D().
getMinor()
constexpr uint32_t ashes::getMinor (uint32_t version) inline
getName() [1/2]
std::string ashes::getName (VkResult value) inline
getName() [2/2]
std::string ashes::getName (VkFormat value)
Gets the name of the given element.
Parameters
[in] value The element.
Returns
The name.
getPatch()
constexpr uint32_t ashes::getPatch (uint32_t version) inline
getPath()
std::string ashes::getPath (std::string const & path)
Retrieves the given path's parent folder.
Parameters
[in] path The path.
Returns
The parent folder.
getSize() [1/5]
uint32_t ashes::getSize (VkFormat format) noexcept
Retrieves the byte size of given non compressed pixel format.
Parameters
[in] format The pixel format.
Returns
The byte size.
Referenced by getSize().
getSize() [2/5]
VkDeviceSize ashes::getSize (VkExtent2D const & extent, VkFormat format) noexcept
Retrieves the byte size of given pixel format and dimensions.
Parameters
[in] extent The dimensions.
[in] format The pixel format.
Returns
The byte size.
getSize() [3/5]
VkDeviceSize ashes::getSize (VkExtent3D const & extent, VkFormat format) inline noexcept
Retrieves the byte size of given pixel format and dimensions.
Parameters
[in] extent The dimensions.
[in] format The pixel format.
Returns
The byte size.
References getSize().
getSize() [4/5]
VkDeviceSize ashes::getSize (VkExtent3D const & extent, VkFormat format, uint32_t mipLevel) inline noexcept
Retrieves the byte size of given pixel format and dimensions.
Parameters
[in] extent The dimensions.
[in] format The pixel format.
Returns
The byte size.
References getSize(), and getSubresourceDimensions().
getSize() [5/5]
VkDeviceSize ashes::getSize (VkExtent2D const & extent, VkFormat format, uint32_t mipLevel) inline noexcept
Retrieves the byte size of given pixel format and dimensions.
Parameters
[in] extent The dimensions.
[in] format The pixel format.
Returns
The byte size.
References getSize(), and getSubresourceDimensions().
getSubresourceDimension()
template<typename T > T ashes::getSubresourceDimension (T const & extent, uint32_t mipLevel) inline
Retrieves the real extent for the given mipmap level.
Parameters
[in] extent The level 0 extent.
[in] mipLevel The mipmap level.
Returns
The mipmap level extent.
Referenced by getSubresourceDimensions().
getSubresourceDimensions() [1/2]
VkExtent3D ashes::getSubresourceDimensions (VkExtent3D const & extent, uint32_t mipLevel) inline
Retrieves the real extent for the given mipmap level.
Parameters
[in] extent The level 0 extent.
[in] mipLevel The mipmap level.
Returns
The dimensions.
References getSubresourceDimension().
Referenced by getSize().
getSubresourceDimensions() [2/2]
VkExtent3D ashes::getSubresourceDimensions (VkExtent2D const & extent, uint32_t mipLevel) inline
Retrieves the real extent for the given mipmap level.
Parameters
[in] extent The level 0 extent.
[in] mipLevel The mipmap level.
Returns
The dimensions.
References getSubresourceDimension().
isASTCFormat()
bool ashes::isASTCFormat (VkFormat format) noexcept
Tells if given pixel format is a ASTC compressed pixel format.
Parameters
[in] format The pixel format.
Referenced by isCompressedFormat().
isBCFormat()
bool ashes::isBCFormat (VkFormat format) noexcept
Tells if given pixel format is a BC compressed pixel format.
Parameters
[in] format The pixel format.
Referenced by isCompressedFormat().
isCompressedFormat()
bool ashes::isCompressedFormat (VkFormat format) inline noexcept
Tells if given pixel format is a compressed pixel format.
Parameters
[in] format The pixel format.
References isASTCFormat(), isBCFormat(), isEACFormat(), isETC2Format(), isPVRTCFormat(), and isYCBCRFormat().
isDepthFormat()
bool ashes::isDepthFormat (VkFormat format) noexcept
Tells if the given VkFormat is usable in depth buffers.
Parameters
[in] format The VkFormat.
Returns
true if it is usable in depth buffers.
Referenced by getAspectMask(), and isDepthOrStencilFormat().
isDepthOrStencilFormat()
bool ashes::isDepthOrStencilFormat (VkFormat format) inline noexcept
Tells if the given VkFormat is usable in depth and/or stencil buffers.
Parameters
[in] format The VkFormat.
Returns
true if it is usable in depth and/or stencil buffers.
References isDepthFormat(), isDepthStencilFormat(), and isStencilFormat().
isDepthStencilFormat()
bool ashes::isDepthStencilFormat (VkFormat format) noexcept
Tells if the given VkFormat is usable in depth and stencil buffers.
Parameters
[in] format The VkFormat.
Returns
true if it is usable in depth and stencil buffers.
Referenced by getAspectMask(), and isDepthOrStencilFormat().
isEACFormat()
bool ashes::isEACFormat (VkFormat format) noexcept
Tells if given pixel format is a EAC compressed pixel format.
Parameters
[in] format The pixel format.
Referenced by isCompressedFormat().
isETC2Format()
bool ashes::isETC2Format (VkFormat format) noexcept
Tells if given pixel format is a ETC2 compressed pixel format.
Parameters
[in] format The pixel format.
Referenced by isCompressedFormat().
isPVRTCFormat()
bool ashes::isPVRTCFormat (VkFormat format) noexcept
Tells if given pixel format is a PVRTC pixel format.
Parameters
[in] format The pixel format.
Referenced by isCompressedFormat().
isStencilFormat()
bool ashes::isStencilFormat (VkFormat format) noexcept
Tells if the given VkFormat is usable in stencil buffers.
Parameters
[in] format The VkFormat.
Returns
true if it is usable in stencil buffers.
Referenced by getAspectMask(), and isDepthOrStencilFormat().
isYCBCRFormat()
bool ashes::isYCBCRFormat (VkFormat format) noexcept
Tells if given pixel format is a YCBCR pixel format.
Parameters
[in] format The pixel format.
Referenced by isCompressedFormat().
listDirectoryFiles()
bool ashes::listDirectoryFiles (std::string const & folderPath, StringArray & files, bool recursive = false)
List all files in a directory, recursively or not.
Parameters
[in] folderPath The directory path.
[out] files Receives the files list.
[in] recursive Tells if search must be recursive.
Returns
true if the directory is listed.
makeArrayView() [1/4]
template<typename T > ArrayView< T > ashes::makeArrayView (T * begin, uint32_t size)
Referenced by makeVector().
makeArrayView() [2/4]
template<typename T > ArrayView< T > ashes::makeArrayView (T * begin, size_t size)
makeArrayView() [3/4]
template<typename T > ArrayView< T > ashes::makeArrayView (T * begin, T * end)
makeArrayView() [4/4]
template<typename T , size_t N> ArrayView< T > ashes::makeArrayView (T(&) buffer[N])
makeClearValue() [1/2]
VkClearValue ashes::makeClearValue (VkClearColorValue v) inline
makeClearValue() [2/2]
VkClearValue ashes::makeClearValue (VkClearDepthStencilValue v) inline
makeOptional()
template<typename Type , typename ... Params> Optional< Type > ashes::makeOptional (Type const * ptr, Params &&... params) inline
References deepCopy().
makeVector() [1/2]
template<typename Type , typename ... Params> std::vector< Type > ashes::makeVector (Type const * ptr, size_t count, Params &&... params) inline
References deepCopy(), and makeArrayView().
Referenced by deepCopy().
makeVector() [2/2]
template<typename Type , typename ... Params> std::vector< Type > ashes::makeVector (Type const * ptr, uint32_t count, Params &&... params) inline
References deepCopy(), and makeArrayView().
makeVersion()
constexpr uint32_t ashes::makeVersion (uint32_t major, uint32_t minor, uint32_t patch) inline
makeVkArray() [1/4]
template<typename VkType , typename LibType > std::vector< VkType > ashes::makeVkArray (std::vector< LibType > const & input) inline
makeVkArray() [2/4]
template<typename VkType , typename LibType > std::vector< VkType > ashes::makeVkArray (std::vector< std::reference_wrapper< LibType > > const & input) inline
makeVkArray() [3/4]
template<typename VkType , typename LibType > std::vector< VkType > ashes::makeVkArray (std::vector< std::unique_ptr< LibType > > const & input) inline
makeVkArray() [4/4]
template<typename VkType , typename LibType > std::vector< VkType > ashes::makeVkArray (std::vector< std::reference_wrapper< LibType const > > const & input) inline
operator &() [1/2]
template<typename FlagType > FlagCombination< FlagType > ashes::operator & (FlagCombination< FlagType > const & lhs, FlagType const & rhs) inline noexcept
operator &() [2/2]
template<typename FlagType > FlagCombination< FlagType > ashes::operator & (FlagCombination< FlagType > const & lhs, typename FlagCombination< FlagType >::BaseType const & rhs) inline noexcept
operator!=() [1/2]
template<typename FlagType > bool ashes::operator!= (FlagCombination< FlagType > const & lhs, FlagCombination< FlagType > const & rhs) inline noexcept
operator!=() [2/2]
template<typename FlagType > bool ashes::operator!= (FlagCombination< FlagType > const & lhs, FlagType const & rhs) inline noexcept
operator==() [1/3]
template<typename T > bool ashes::operator== (ArrayView< T > const & lhs, ArrayView< T > const & rhs)
References ashes::ArrayView< T >::begin(), ashes::ArrayView< T >::end(), and ashes::ArrayView< T >::size().
operator==() [2/3]
template<typename FlagType > bool ashes::operator== (FlagCombination< FlagType > const & lhs, FlagCombination< FlagType > const & rhs) inline noexcept
operator==() [3/3]
template<typename FlagType > bool ashes::operator== (FlagCombination< FlagType > const & lhs, FlagType const & rhs) inline noexcept
operator|() [1/2]
template<typename FlagType > FlagCombination< FlagType > ashes::operator| (FlagCombination< FlagType > const & lhs, FlagType const & rhs) inline noexcept
operator|() [2/2]
template<typename FlagType > FlagCombination< FlagType > ashes::operator| (FlagCombination< FlagType > const & lhs, typename FlagCombination< FlagType >::BaseType const & rhs) inline noexcept
remFlag() [1/2]
template<typename FlagType > FlagCombination< FlagType >& ashes::remFlag (FlagCombination< FlagType > & value, FlagType const & flag) inline noexcept
Removes a flag from given combination.
Parameters
[in,out] value The combination.
[in] flag The flag to remove.
Returns
The combination.
remFlag() [2/2]
template<typename FlagType > FlagCombination< FlagType > ashes::remFlag (FlagCombination< FlagType > const & value, FlagType const & flag) inline noexcept
Removes a flag from given combination.
Parameters
[in] value The combination.
[in] flag The flag to remove.
Returns
The new combination.
Variable Documentation
WholeSize
VkDeviceSize constexpr ashes::WholeSize = ~(0ull) static