ashespp: ashes::BufferBase Class Reference
ashes::BufferBase Class Reference
GPU buffer class.
Public Member Functions
BufferBase (Device const &device, VkDeviceSize size, VkBufferUsageFlags target)
Constructor.
~BufferBase ()
Destructor.
void bindMemory (DeviceMemoryPtr memory)
Binds this buffer to given device memory object.
uint8_t * lock (VkDeviceSize offset, VkDeviceSize size, VkMemoryMapFlags flags) const
Maps a range of the buffer's memory in RAM.
void invalidate (VkDeviceSize offset, VkDeviceSize size) const
Invalidates the buffer content.
void flush (VkDeviceSize offset, VkDeviceSize size) const
Updates the VRAM.
void unlock () const
Unmaps the buffer's memory from RAM.
VkPipelineStageFlags getCompatibleStageFlags () const
VkBufferMemoryBarrier makeTransferDestination (uint32_t srcQueueFamily=~(0u), uint32_t dstQueueFamily=~(0u)) const
Prepares a buffer memory barrier, to a transfer destination layout.
VkBufferMemoryBarrier makeTransferSource (uint32_t srcQueueFamily=~(0u), uint32_t dstQueueFamily=~(0u)) const
Prepares a buffer memory barrier, to a transfer source layout.
VkBufferMemoryBarrier makeVertexShaderInputResource (uint32_t srcQueueFamily=~(0u), uint32_t dstQueueFamily=~(0u)) const
Prepares a buffer memory barrier, to a vertex shader input layout.
VkBufferMemoryBarrier makeUniformBufferInput (uint32_t srcQueueFamily=~(0u), uint32_t dstQueueFamily=~(0u)) const
Prepares a buffer memory barrier, to a uniform buffer input layout.
VkBufferMemoryBarrier makeMemoryTransitionBarrier (VkAccessFlags dstAccessFlags, uint32_t srcQueueFamily=~(0u), uint32_t dstQueueFamily=~(0u)) const
Prepares a buffer memory barrier, to a given memory layout.
VkMemoryRequirements getMemoryRequirements () const
VkDeviceSize getSize () const
VkBufferUsageFlags getTargets () const
operator VkBuffer const & () const
VkBuffer implicit cast operator.
Detailed Description
GPU buffer class.
Constructor & Destructor Documentation
BufferBase()
ashes::BufferBase::BufferBase (Device const & device, VkDeviceSize size, VkBufferUsageFlags target)
Constructor.
Parameters
[in] device The logical device.
[in] size The buffer size.
[in] target The buffer usage flags.
~BufferBase()
ashes::BufferBase::~BufferBase ()
Destructor.
Member Function Documentation
bindMemory()
void ashes::BufferBase::bindMemory (DeviceMemoryPtr memory)
Binds this buffer to given device memory object.
Parameters
[in] memory The memory object.
flush()
void ashes::BufferBase::flush (VkDeviceSize offset, VkDeviceSize size) const
Updates the VRAM.
Parameters
[in] offset The mapped memory starting offset.
[in] size The range size.
Referenced by ashes::UniformBuffer< T >::upload().
getCompatibleStageFlags()
VkPipelineStageFlags ashes::BufferBase::getCompatibleStageFlags () const inline
Returns
The compatible pipeline stage flags for current access.
getMemoryRequirements()
VkMemoryRequirements ashes::BufferBase::getMemoryRequirements () const
Returns
The memory requirements for this buffer.
getSize()
VkDeviceSize ashes::BufferBase::getSize () const inline
Returns
The buffer size.
getTargets()
VkBufferUsageFlags ashes::BufferBase::getTargets () const inline
Returns
The buffer usage flags.
invalidate()
void ashes::BufferBase::invalidate (VkDeviceSize offset, VkDeviceSize size) const
Invalidates the buffer content.
Parameters
[in] offset The mapped memory starting offset.
[in] size The range size.
lock()
uint8_t* ashes::BufferBase::lock (VkDeviceSize offset, VkDeviceSize size, VkMemoryMapFlags flags) const
Maps a range of the buffer's memory in RAM.
Parameters
[in] offset The range beginning offset.
[in] size The range size.
[in] flags The mapping flags.
Returns
nullptr if mapping failed.
Referenced by ashes::UniformBuffer< T >::upload().
makeMemoryTransitionBarrier()
VkBufferMemoryBarrier ashes::BufferBase::makeMemoryTransitionBarrier (VkAccessFlags dstAccessFlags, uint32_t srcQueueFamily = ~(0u), uint32_t dstQueueFamily = ~(0u)) const
Prepares a buffer memory barrier, to a given memory layout.
Parameters
[in] dstAccessFlags The wanted access flags, after the transition.
[in] srcQueueFamily The source queue family, if a responsibility transfer must happen.
[in] dstQueueFamily The destination queue family, if a responsibility transfer must happen.
Returns
The memory barrier.
makeTransferDestination()
VkBufferMemoryBarrier ashes::BufferBase::makeTransferDestination (uint32_t srcQueueFamily = ~(0u), uint32_t dstQueueFamily = ~(0u)) const
Prepares a buffer memory barrier, to a transfer destination layout.
Returns
The memory barrier.
makeTransferSource()
VkBufferMemoryBarrier ashes::BufferBase::makeTransferSource (uint32_t srcQueueFamily = ~(0u), uint32_t dstQueueFamily = ~(0u)) const
Prepares a buffer memory barrier, to a transfer source layout.
Returns
The memory barrier.
makeUniformBufferInput()
VkBufferMemoryBarrier ashes::BufferBase::makeUniformBufferInput (uint32_t srcQueueFamily = ~(0u), uint32_t dstQueueFamily = ~(0u)) const
Prepares a buffer memory barrier, to a uniform buffer input layout.
Returns
The memory barrier.
makeVertexShaderInputResource()
VkBufferMemoryBarrier ashes::BufferBase::makeVertexShaderInputResource (uint32_t srcQueueFamily = ~(0u), uint32_t dstQueueFamily = ~(0u)) const
Prepares a buffer memory barrier, to a vertex shader input layout.
Returns
The memory barrier.
operator VkBuffer const &()
ashes::BufferBase::operator VkBuffer const & () const inline
VkBuffer implicit cast operator.
unlock()
void ashes::BufferBase::unlock () const
Unmaps the buffer's memory from RAM.
Referenced by ashes::UniformBuffer< T >::upload().
The documentation for this class was generated from the following file:
Z:/Projets/C++/Ashes/include/ashespp/Buffer/Buffer.hpp