Renderer: renderer::Debug::Backtrace Struct Reference
renderer::Debug::Backtrace Struct Reference
Public Member Functions
Backtrace (int p_toCapture=20, int p_toSkip=2)
Public Attributes
int const m_toCapture
int const m_toSkip
Constructor & Destructor Documentation
Backtrace()
renderer::Debug::Backtrace::Backtrace (int p_toCapture = 20, int p_toSkip = 2) inline
References renderer::Debug::cleanup(), renderer::Debug::initialise(), and renderer::Debug::operator<<().
Member Data Documentation
m_toCapture
int const renderer::Debug::Backtrace::m_toCapture
m_toSkip
int const renderer::Debug::Backtrace::m_toSkip
The documentation for this struct was generated from the following file:
Z:/Projets/C++/RenderLib/source/Renderer/Renderer/Src/Utils/CallStack.hpp